// Generated by scripts/generate-conversation-creation.mjs from contracts/http/conversation-creation.json.
// Do not edit this file directly.

import {
  parseConversationDetailSnapshot,
  type ChannelConversationSnapshotSummary,
  type ConversationDetailSnapshot,
  type DirectConversationSnapshotSummary,
  type GroupDirectConversationSnapshotSummary,
} from "./conversation-snapshot.js";
import type { HostEntityReference } from "./conversation.js";
import type { UserId } from "./identifiers.js";

const PARTICIPANT_IDENTITY_PREFIX = "{{PARTICIPANT_IDENTITY_PREFIX}}";

const TRUSTED_IDENTITY_FIELDS = new Set([
{{TRUSTED_IDENTITY_FIELDS}}
]);

/** Compile-time guard for identity and authorization derived from the host session. */
export interface NoTrustedConversationCreationIdentity {
{{TRUSTED_IDENTITY_PROPERTIES}}
}

type UntrustedEntityReference = HostEntityReference &
  NoTrustedConversationCreationIdentity;

interface ConversationCreationInputBase
  extends NoTrustedConversationCreationIdentity {
  readonly operation: "create_conversation";
  readonly idempotencyKey: string;
  /** Correlates the authoritative response with one client-side request. */
  readonly clientRequestId: string;
}

/** Creates a named channel. Initial channel membership is server policy, not input. */
export interface CreateChannelConversationInput
  extends ConversationCreationInputBase {
  readonly type: "channel";
  readonly name: string;
  readonly visibility: "public" | "private";
  readonly entity?: UntrustedEntityReference;
  readonly intendedMemberUserIds?: never;
  readonly parentConversationId?: never;
  readonly rootMessageId?: never;
}

/** Identifies exactly one other directory member; the trusted actor is added server-side. */
export interface CreateDirectConversationInput
  extends ConversationCreationInputBase {
  readonly type: "direct";
  readonly visibility: "private";
  readonly intendedMemberUserIds: readonly [UserId];
  readonly name?: never;
  readonly entity?: never;
  readonly parentConversationId?: never;
  readonly rootMessageId?: never;
}

/** Identifies at least two other directory members; the trusted actor is added server-side. */
export interface CreateGroupDirectConversationInput
  extends ConversationCreationInputBase {
  readonly type: "group_direct";
  readonly visibility: "private";
  readonly intendedMemberUserIds: readonly [UserId, UserId, ...UserId[]];
  readonly name?: never;
  readonly entity?: never;
  readonly parentConversationId?: never;
  readonly rootMessageId?: never;
}

export type ConversationCreationInput =
  | CreateChannelConversationInput
  | CreateDirectConversationInput
  | CreateGroupDirectConversationInput;

declare const canonicalParticipantIdentityKeyBrand: unique symbol;

/** Opaque, deterministic encoding of a complete, canonically ordered participant set. */
export type CanonicalParticipantIdentityKey = string & {
  readonly [canonicalParticipantIdentityKeyBrand]: "canonical-participant-identity";
};

export interface CanonicalParticipantIdentity {
  /** Complete set, including the server-derived actor, in canonical string order. */
  readonly participantUserIds: readonly UserId[];
  readonly key: CanonicalParticipantIdentityKey;
}

export type ConversationCreationReconciliationStatus =
  /** This request persisted a new conversation. */
  | "created"
  /** A direct/group-direct with the same complete participant identity already existed. */
  | "existing_equivalent"
  /** The idempotency key replayed its previously authoritative outcome. */
  | "replayed";

type CreationDetailSnapshot<Summary> = Omit<
  ConversationDetailSnapshot,
  "conversation"
> & {
  readonly conversation: Summary;
};

interface ConversationCreationResultBase<
  Type extends "channel" | "direct" | "group_direct",
  Summary,
> {
  readonly operation: "create_conversation";
  readonly type: Type;
  readonly reconciliationStatus: ConversationCreationReconciliationStatus;
  /** Exact echo used to reconcile a pending client-side request. */
  readonly clientRequestId: string;
  readonly conversation: CreationDetailSnapshot<Summary>;
}

export interface ChannelConversationCreationResult
  extends ConversationCreationResultBase<
    "channel",
    ChannelConversationSnapshotSummary
  > {
  readonly reconciliationStatus: "created" | "replayed";
  readonly participantIdentity?: never;
}

export interface DirectConversationCreationResult
  extends ConversationCreationResultBase<
    "direct",
    DirectConversationSnapshotSummary
  > {
  readonly participantIdentity: CanonicalParticipantIdentity;
}

export interface GroupDirectConversationCreationResult
  extends ConversationCreationResultBase<
    "group_direct",
    GroupDirectConversationSnapshotSummary
  > {
  readonly participantIdentity: CanonicalParticipantIdentity;
}

export type ConversationCreationResult =
  | ChannelConversationCreationResult
  | DirectConversationCreationResult
  | GroupDirectConversationCreationResult;

export type ConversationCreationParseErrorCode =
  | "malformed_input"
  | "trusted_identity_field"
  | "malformed_entity"
  | "invalid_member_cardinality"
  | "malformed_member_id"
  | "duplicate_member_id"
  | "malformed_participant_identity"
  | "malformed_result"
  | "incoherent_result";

export class ConversationCreationParseError extends Error {
  readonly code: ConversationCreationParseErrorCode;

  constructor(code: ConversationCreationParseErrorCode, message: string) {
    super(message);
    this.name = "ConversationCreationParseError";
    this.code = code;
  }
}

const BASE_INPUT_KEYS = [
  "operation",
  "type",
  "idempotencyKey",
  "clientRequestId",
] as const;
const CHANNEL_INPUT_KEYS = [
  ...BASE_INPUT_KEYS,
  "name",
  "visibility",
  "entity",
] as const;
const DIRECT_INPUT_KEYS = [
  ...BASE_INPUT_KEYS,
  "visibility",
  "intendedMemberUserIds",
] as const;
const BASE_RESULT_KEYS = [
  "operation",
  "type",
  "reconciliationStatus",
  "clientRequestId",
  "conversation",
] as const;

export function parseCreateChannelConversationInput(
  value: unknown,
): CreateChannelConversationInput {
  const input = parseInputRecord(value);
  return parseChannelInputRecord(input);
}

export function parseCreateDirectConversationInput(
  value: unknown,
): CreateDirectConversationInput {
  const input = parseInputRecord(value);
  return parseDirectInputRecord(input);
}

export function parseCreateGroupDirectConversationInput(
  value: unknown,
): CreateGroupDirectConversationInput {
  const input = parseInputRecord(value);
  return parseGroupDirectInputRecord(input);
}

export function parseConversationCreationInput(
  value: unknown,
): ConversationCreationInput {
  const input = parseInputRecord(value);
  if (input.type === "channel") return parseChannelInputRecord(input);
  if (input.type === "direct") return parseDirectInputRecord(input);
  if (input.type === "group_direct") return parseGroupDirectInputRecord(input);
  throw creationError(
    "malformed_input",
    "input.type must be channel, direct, or group_direct; thread creation is separate",
  );
}

/**
 * Derives direct/group-direct identity from the complete participant set.
 * The actor is supplied separately from trusted context; ordering never affects
 * the returned IDs or key. Intended members must not contain the actor.
 */
export function deriveCanonicalParticipantIdentity(
  trustedActorUserId: UserId,
  intendedMemberUserIds: readonly UserId[],
): CanonicalParticipantIdentity {
  const actor = parseNonBlankMemberId(
    trustedActorUserId,
    "trustedActorUserId",
  );
  if (!Array.isArray(intendedMemberUserIds) || intendedMemberUserIds.length < 1) {
    throw creationError(
      "invalid_member_cardinality",
      "at least one intended other member is required",
    );
  }

  const intended = parseUniqueMemberIds(
    intendedMemberUserIds,
    "intendedMemberUserIds",
  );
  if (intended.includes(actor)) {
    throw creationError(
      "duplicate_member_id",
      "intendedMemberUserIds cannot contain the trusted actor",
    );
  }

  return createParticipantIdentity([actor, ...intended]);
}

export function parseChannelConversationCreationResult(
  value: unknown,
  expectedInput?: CreateChannelConversationInput,
): ChannelConversationCreationResult {
  return parseResultRecord(value, "channel", expectedInput);
}

export function parseDirectConversationCreationResult(
  value: unknown,
  expectedInput?: CreateDirectConversationInput,
): DirectConversationCreationResult {
  return parseResultRecord(value, "direct", expectedInput);
}

export function parseGroupDirectConversationCreationResult(
  value: unknown,
  expectedInput?: CreateGroupDirectConversationInput,
): GroupDirectConversationCreationResult {
  return parseResultRecord(value, "group_direct", expectedInput);
}

export function parseConversationCreationResult(
  value: unknown,
  expectedInput?: ConversationCreationInput,
): ConversationCreationResult {
  const result = requireRecord(value, "result", "malformed_result");
  if (result.type === "channel") {
    const expected = expectedInput?.type === "channel" ? expectedInput : undefined;
    if (expectedInput !== undefined && expected === undefined) {
      throw creationError("incoherent_result", "result.type does not match the request type");
    }
    return parseResultRecord(result, "channel", expected);
  }
  if (result.type === "direct") {
    const expected = expectedInput?.type === "direct" ? expectedInput : undefined;
    if (expectedInput !== undefined && expected === undefined) {
      throw creationError("incoherent_result", "result.type does not match the request type");
    }
    return parseResultRecord(result, "direct", expected);
  }
  if (result.type === "group_direct") {
    const expected = expectedInput?.type === "group_direct" ? expectedInput : undefined;
    if (expectedInput !== undefined && expected === undefined) {
      throw creationError("incoherent_result", "result.type does not match the request type");
    }
    return parseResultRecord(result, "group_direct", expected);
  }
  throw creationError(
    "malformed_result",
    "result.type must be channel, direct, or group_direct",
  );
}

function parseInputRecord(value: unknown): Record<string, unknown> {
  rejectTrustedIdentityFields(value);
  const input = requireRecord(value, "input", "malformed_input");
  if (input.operation !== "create_conversation") {
    throw creationError(
      "malformed_input",
      "input.operation must be create_conversation",
    );
  }
  return input;
}

function parseChannelInputRecord(
  input: Record<string, unknown>,
): CreateChannelConversationInput {
  assertAllowedKeys(input, CHANNEL_INPUT_KEYS, "input", "malformed_input");
  assertType(input, "channel", "malformed_input");
  if (input.visibility !== "public" && input.visibility !== "private") {
    throw creationError(
      "malformed_input",
      "channel visibility must be public or private",
    );
  }

  const output: {
    operation: "create_conversation";
    type: "channel";
    name: string;
    visibility: "public" | "private";
    idempotencyKey: string;
    clientRequestId: string;
    entity?: UntrustedEntityReference;
  } = {
    operation: "create_conversation",
    type: "channel",
    name: readNonBlankString(input.name, "input.name", "malformed_input"),
    visibility: input.visibility,
    idempotencyKey: readNonBlankString(
      input.idempotencyKey,
      "input.idempotencyKey",
      "malformed_input",
    ),
    clientRequestId: readNonBlankString(
      input.clientRequestId,
      "input.clientRequestId",
      "malformed_input",
    ),
  };

  if (input.entity !== undefined) output.entity = parseEntity(input.entity);
  return output;
}

function parseDirectInputRecord(
  input: Record<string, unknown>,
): CreateDirectConversationInput {
  assertAllowedKeys(input, DIRECT_INPUT_KEYS, "input", "malformed_input");
  assertType(input, "direct", "malformed_input");
  assertPrivateVisibility(input, "direct");
  const members = parseIntendedMembers(input.intendedMemberUserIds, 1, "direct");
  return {
    operation: "create_conversation",
    type: "direct",
    visibility: "private",
    intendedMemberUserIds: members as [UserId],
    idempotencyKey: readNonBlankString(
      input.idempotencyKey,
      "input.idempotencyKey",
      "malformed_input",
    ),
    clientRequestId: readNonBlankString(
      input.clientRequestId,
      "input.clientRequestId",
      "malformed_input",
    ),
  };
}

function parseGroupDirectInputRecord(
  input: Record<string, unknown>,
): CreateGroupDirectConversationInput {
  assertAllowedKeys(input, DIRECT_INPUT_KEYS, "input", "malformed_input");
  assertType(input, "group_direct", "malformed_input");
  assertPrivateVisibility(input, "group_direct");
  const members = parseIntendedMembers(
    input.intendedMemberUserIds,
    2,
    "group_direct",
  );
  return {
    operation: "create_conversation",
    type: "group_direct",
    visibility: "private",
    intendedMemberUserIds: members as [UserId, UserId, ...UserId[]],
    idempotencyKey: readNonBlankString(
      input.idempotencyKey,
      "input.idempotencyKey",
      "malformed_input",
    ),
    clientRequestId: readNonBlankString(
      input.clientRequestId,
      "input.clientRequestId",
      "malformed_input",
    ),
  };
}

function parseIntendedMembers(
  value: unknown,
  minimum: 1 | 2,
  kind: "direct" | "group_direct",
): UserId[] {
  if (!Array.isArray(value) || value.length < minimum || (minimum === 1 && value.length !== 1)) {
    const cardinality = minimum === 1 ? "exactly one" : "at least two";
    throw creationError(
      "invalid_member_cardinality",
      `${kind} creation requires ${cardinality} intended other member${minimum === 1 ? "" : "s"}`,
    );
  }
  return parseUniqueMemberIds(value, "input.intendedMemberUserIds");
}

function parseUniqueMemberIds(value: readonly unknown[], path: string): UserId[] {
  const result: UserId[] = [];
  const seen = new Set<string>();
  for (let index = 0; index < value.length; index += 1) {
    const member = parseNonBlankMemberId(value[index], `${path}[${index}]`);
    if (seen.has(member)) {
      throw creationError(
        "duplicate_member_id",
        `${path} cannot contain duplicate member ID ${JSON.stringify(member)}`,
      );
    }
    seen.add(member);
    result.push(member);
  }
  return result;
}

function parseNonBlankMemberId(value: unknown, path: string): UserId {
  return readNonBlankString(value, path, "malformed_member_id") as UserId;
}

function parseEntity(value: unknown): UntrustedEntityReference {
  const entity = requireRecord(value, "input.entity", "malformed_entity");
  assertAllowedKeys(entity, ["type", "id"], "input.entity", "malformed_entity");
  return {
    type: readNonBlankString(entity.type, "input.entity.type", "malformed_entity"),
    id: readNonBlankString(entity.id, "input.entity.id", "malformed_entity"),
  };
}

function assertPrivateVisibility(
  input: Record<string, unknown>,
  kind: "direct" | "group_direct",
): void {
  if (input.visibility !== "private") {
    throw creationError(
      "malformed_input",
      `${kind} visibility must be private`,
    );
  }
}

function assertType(
  input: Record<string, unknown>,
  type: "channel" | "direct" | "group_direct",
  code: "malformed_input" | "malformed_result",
): void {
  if (input.type !== type) {
    throw creationError(code, `${code === "malformed_input" ? "input" : "result"}.type must be ${type}`);
  }
}

function parseResultRecord(
  value: unknown,
  expectedType: "channel",
  expectedInput?: CreateChannelConversationInput,
): ChannelConversationCreationResult;
function parseResultRecord(
  value: unknown,
  expectedType: "direct",
  expectedInput?: CreateDirectConversationInput,
): DirectConversationCreationResult;
function parseResultRecord(
  value: unknown,
  expectedType: "group_direct",
  expectedInput?: CreateGroupDirectConversationInput,
): GroupDirectConversationCreationResult;
function parseResultRecord(
  value: unknown,
  expectedType: "channel" | "direct" | "group_direct",
  expectedInput?: ConversationCreationInput,
): ConversationCreationResult {
  const result = requireRecord(value, "result", "malformed_result");
  const allowedKeys = expectedType === "channel"
    ? BASE_RESULT_KEYS
    : [...BASE_RESULT_KEYS, "participantIdentity"];
  assertAllowedKeys(result, allowedKeys, "result", "malformed_result");
  if (result.operation !== "create_conversation") {
    throw creationError(
      "malformed_result",
      "result.operation must be create_conversation",
    );
  }
  assertType(result, expectedType, "malformed_result");

  const status = parseReconciliationStatus(result.reconciliationStatus);
  if (expectedType === "channel" && status === "existing_equivalent") {
    throw creationError(
      "incoherent_result",
      "existing_equivalent is reserved for direct and group_direct identity matches",
    );
  }
  const clientRequestId = readNonBlankString(
    result.clientRequestId,
    "result.clientRequestId",
    "malformed_result",
  );

  let conversation: ConversationDetailSnapshot;
  try {
    conversation = parseConversationDetailSnapshot(result.conversation);
  } catch (error) {
    throw creationError(
      "malformed_result",
      `result.conversation must be a valid conversation detail snapshot${error instanceof Error ? `: ${error.message}` : ""}`,
    );
  }
  if (conversation.conversation.type !== expectedType) {
    throw creationError(
      "incoherent_result",
      "result type must match result.conversation.conversation.type",
    );
  }
  if (expectedInput !== undefined && expectedInput.clientRequestId !== clientRequestId) {
    throw creationError(
      "incoherent_result",
      "result.clientRequestId must echo the request clientRequestId",
    );
  }

  if (expectedType === "channel") {
    return {
      operation: "create_conversation",
      type: "channel",
      reconciliationStatus: status as "created" | "replayed",
      clientRequestId,
      conversation: conversation as CreationDetailSnapshot<ChannelConversationSnapshotSummary>,
    };
  }

  const identity = parseCanonicalParticipantIdentity(
    result.participantIdentity,
    expectedType,
  );
  const actorUserId = conversation.conversation.currentMember.userId;
  if (!identity.participantUserIds.includes(actorUserId)) {
    throw creationError(
      "incoherent_result",
      "participant identity must include the snapshot's server-derived current actor",
    );
  }

  if (expectedInput !== undefined) {
    if (expectedInput.type === "channel") {
      throw creationError(
        "incoherent_result",
        "participant identity cannot be reconciled against a channel request",
      );
    }
    const expectedIdentity = deriveCanonicalParticipantIdentity(
      actorUserId,
      expectedInput.intendedMemberUserIds,
    );
    if (identity.key !== expectedIdentity.key) {
      throw creationError(
        "incoherent_result",
        "participant identity does not match the request members plus trusted actor",
      );
    }
  }

  const common = {
    operation: "create_conversation" as const,
    reconciliationStatus: status,
    clientRequestId,
    participantIdentity: identity,
  };
  if (expectedType === "direct") {
    return {
      ...common,
      type: "direct",
      conversation: conversation as CreationDetailSnapshot<DirectConversationSnapshotSummary>,
    };
  }
  return {
    ...common,
    type: "group_direct",
    conversation: conversation as CreationDetailSnapshot<GroupDirectConversationSnapshotSummary>,
  };
}

function parseCanonicalParticipantIdentity(
  value: unknown,
  kind: "direct" | "group_direct",
): CanonicalParticipantIdentity {
  const identity = requireRecord(
    value,
    "result.participantIdentity",
    "malformed_participant_identity",
  );
  assertAllowedKeys(
    identity,
    ["participantUserIds", "key"],
    "result.participantIdentity",
    "malformed_participant_identity",
  );
  if (!Array.isArray(identity.participantUserIds)) {
    throw creationError(
      "malformed_participant_identity",
      "result.participantIdentity.participantUserIds must be an array",
    );
  }
  const ids = parseUniqueMemberIds(
    identity.participantUserIds,
    "result.participantIdentity.participantUserIds",
  );
  const requiredCount = kind === "direct" ? 2 : 3;
  if ((kind === "direct" && ids.length !== requiredCount) || ids.length < requiredCount) {
    throw creationError(
      "malformed_participant_identity",
      `${kind} participant identity must contain ${kind === "direct" ? "exactly two" : "at least three"} users`,
    );
  }
  const canonical = createParticipantIdentity(ids);
  if (identity.key !== canonical.key) {
    throw creationError(
      "malformed_participant_identity",
      "participant identity key does not match its canonical participantUserIds",
    );
  }
  if (!sameStrings(ids, canonical.participantUserIds)) {
    throw creationError(
      "malformed_participant_identity",
      "participantUserIds must be in canonical order",
    );
  }
  return canonical;
}

function createParticipantIdentity(
  participantUserIds: readonly UserId[],
): CanonicalParticipantIdentity {
  const sorted = [...participantUserIds].sort(compareStrings);
  return {
    participantUserIds: sorted,
    key: `${PARTICIPANT_IDENTITY_PREFIX}${encodeURIComponent(JSON.stringify(sorted))}` as CanonicalParticipantIdentityKey,
  };
}

function parseReconciliationStatus(
  value: unknown,
): ConversationCreationReconciliationStatus {
  if (value !== "created" && value !== "existing_equivalent" && value !== "replayed") {
    throw creationError(
      "malformed_result",
      "result.reconciliationStatus must be created, existing_equivalent, or replayed",
    );
  }
  return value;
}

function rejectTrustedIdentityFields(value: unknown, path = "input"): void {
  if (Array.isArray(value)) {
    value.forEach((entry, index) => rejectTrustedIdentityFields(entry, `${path}[${index}]`));
    return;
  }
  if (!isRecord(value)) return;
  for (const [key, nested] of Object.entries(value)) {
    const normalizedKey = key.replaceAll(/[^a-zA-Z0-9]/g, "").toLowerCase();
    if (TRUSTED_IDENTITY_FIELDS.has(normalizedKey)) {
      throw creationError(
        "trusted_identity_field",
        `${path}.${key} is server-derived and cannot be supplied by a client`,
      );
    }
    rejectTrustedIdentityFields(nested, `${path}.${key}`);
  }
}

function assertAllowedKeys(
  value: Record<string, unknown>,
  allowed: readonly string[],
  path: string,
  code:
    | "malformed_input"
    | "malformed_entity"
    | "malformed_participant_identity"
    | "malformed_result",
): void {
  const allowedSet = new Set(allowed);
  for (const key of Object.keys(value)) {
    if (!allowedSet.has(key)) {
      throw creationError(code, `${path}.${key} is not supported`);
    }
  }
}

function requireRecord(
  value: unknown,
  path: string,
  code:
    | "malformed_input"
    | "malformed_entity"
    | "malformed_participant_identity"
    | "malformed_result",
): Record<string, unknown> {
  if (!isRecord(value)) {
    throw creationError(code, `${path} must be an object`);
  }
  return value;
}

function readNonBlankString(
  value: unknown,
  path: string,
  code:
    | "malformed_input"
    | "malformed_entity"
    | "malformed_member_id"
    | "malformed_result",
): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw creationError(code, `${path} must be a nonblank string`);
  }
  return value;
}

function sameStrings(left: readonly string[], right: readonly string[]): boolean {
  return left.length === right.length && left.every((value, index) => value === right[index]);
}

function compareStrings(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function creationError(
  code: ConversationCreationParseErrorCode,
  message: string,
): ConversationCreationParseError {
  return new ConversationCreationParseError(code, message);
}
