// Generated by scripts/generate-delete-message.mjs from contracts/http/delete-message.json.
// Do not edit this file directly.

import type { MessageId } from "../identifiers.js";
import type { Message, MessageBlock } from "../message.js";
import {
  MessageMutationParseError,
  parseSendMessageResult,
} from "./send-message.js";
import type {
  MessageMutationParseErrorCode,
  MessageMutationReconciliationStatus,
  NoTrustedMessageMutationIdentity,
} from "./send-message.js";

const TRUSTED_IDENTITY_FIELDS = new Set([
{{TRUSTED_IDENTITY_FIELDS}}
]);

const INPUT_KEYS = [
{{INPUT_KEYS}}
] as const;

const RESULT_KEYS = [
{{RESULT_KEYS}}
] as const;

/** Optimistic-concurrency input for retaining a redacted message shell. */
export interface SoftDeleteMessageInput
  extends NoTrustedMessageMutationIdentity {
  readonly operation: "{{OPERATION}}";
  readonly messageId: MessageId;
  readonly expectedRevision: number;
  readonly idempotencyKey: string;
}

interface SoftDeleteMessageResultBase<
  Block extends MessageBlock,
  Status extends MessageMutationReconciliationStatus | "revision_conflict",
> {
  readonly operation: "{{OPERATION}}";
  readonly reconciliationStatus: Status;
  /** Exact echo of the optimistic-concurrency revision supplied by the caller. */
  readonly expectedRevision: number;
  readonly message: Message<Block>;
  /** Current authoritative revision; always equal to message.revision.revision. */
  readonly canonicalRevision: number;
}

type SoftDeleteMessageSuccess<Block extends MessageBlock> =
  SoftDeleteMessageResultBase<Block, MessageMutationReconciliationStatus>;

type SoftDeleteMessageConflict<Block extends MessageBlock> =
  SoftDeleteMessageResultBase<Block, "revision_conflict">;

export type SoftDeleteMessageResult<
  Block extends MessageBlock = MessageBlock,
> =
  | SoftDeleteMessageSuccess<Block>
  | SoftDeleteMessageConflict<Block>;

export function parseSoftDeleteMessageInput(
  value: unknown,
): SoftDeleteMessageInput {
  const input = requireRecord(value, "input", "malformed_input");
  rejectTrustedIdentityFields(input);
  assertExactKeys(input, INPUT_KEYS, "input", "malformed_input");
  if (input.operation !== "{{OPERATION}}") {
    throw mutationError("malformed_input", "operation must be {{OPERATION}}");
  }

  return {
    operation: "{{OPERATION}}",
    messageId: readNonBlankString(
      input.messageId,
      "input.messageId",
      "malformed_input",
    ) as MessageId,
    expectedRevision: readPositiveSafeInteger(
      input.expectedRevision,
      "input.expectedRevision",
      "malformed_input",
    ),
    idempotencyKey: readNonBlankString(
      input.idempotencyKey,
      "input.idempotencyKey",
      "malformed_input",
    ),
  };
}

export function parseSoftDeleteMessageResult<
  Block extends MessageBlock = MessageBlock,
>(value: unknown): SoftDeleteMessageResult<Block> {
  const result = requireRecord(value, "result", "malformed_result");
  assertExactKeys(result, RESULT_KEYS, "result", "malformed_result");
  if (result.operation !== "{{OPERATION}}") {
    throw mutationError("malformed_result", "operation must be {{OPERATION}}");
  }

  const expectedRevision = readPositiveSafeInteger(
    result.expectedRevision,
    "result.expectedRevision",
    "malformed_result",
  );
  const canonicalRevision = readPositiveSafeInteger(
    result.canonicalRevision,
    "result.canonicalRevision",
    "malformed_result",
  );
  const messageRecord = requireRecord(
    result.message,
    "result.message",
    "malformed_result",
  );
  const revisionRecord = requireRecord(
    messageRecord.revision,
    "result.message.revision",
    "malformed_result",
  );
  const messageRevision = readPositiveSafeInteger(
    revisionRecord.revision,
    "result.message.revision.revision",
    "malformed_result",
  );
  if (canonicalRevision !== messageRevision) {
    throw mutationError(
      "revision_mismatch",
      "canonicalRevision must equal message.revision.revision",
    );
  }

  // Reuse the canonical generated Message validator while neutralizing the
  // send-only revision-one invariant in its surrounding mutation envelope.
  parseSendMessageResult<Block>({
    operation: "send",
    reconciliationStatus: "applied",
    clientMessageId: "delete-message-validation",
    message: {
      ...messageRecord,
      revision: { ...revisionRecord, revision: 1 },
    },
    canonicalRevision: 1,
  });
  const message = messageRecord as unknown as Message<Block>;
  const isDeletionShell = Object.hasOwn(messageRecord, "deletedAt");
  if (isDeletionShell && messageRecord.content !== null) {
    throw mutationError(
      "malformed_result",
      "a soft-delete tombstone must have null content",
    );
  }

  if (result.reconciliationStatus === "revision_conflict") {
    if (canonicalRevision === expectedRevision) {
      throw mutationError(
        "revision_mismatch",
        "a revision conflict must report a different canonical revision",
      );
    }
    return {
      operation: "{{OPERATION}}",
      reconciliationStatus: "revision_conflict",
      expectedRevision,
      message,
      canonicalRevision,
    };
  }

  const reconciliationStatus = readSuccessStatus(result.reconciliationStatus);
  if (canonicalRevision !== expectedRevision + 1) {
    throw mutationError(
      "revision_mismatch",
      "a successful soft-delete must advance expectedRevision by exactly one",
    );
  }
  if (!isDeletionShell) {
    throw mutationError(
      "malformed_result",
      "a successful soft-delete result must contain a deleted message shell",
    );
  }
  return {
    operation: "{{OPERATION}}",
    reconciliationStatus,
    expectedRevision,
    message,
    canonicalRevision,
  };
}

function rejectTrustedIdentityFields(input: Record<string, unknown>): void {
  for (const key of Object.keys(input)) {
    const normalizedKey = key.replaceAll(/[^a-zA-Z0-9]/g, "").toLowerCase();
    if (TRUSTED_IDENTITY_FIELDS.has(normalizedKey)) {
      throw mutationError(
        "trusted_identity_field",
        "input." + key + " is server-derived and cannot be supplied by a client",
      );
    }
  }
}

function readSuccessStatus(
  value: unknown,
): MessageMutationReconciliationStatus {
  if (value !== "applied" && value !== "replayed") {
    throw mutationError(
      "malformed_result",
      "reconciliationStatus must be applied, replayed, or revision_conflict",
    );
  }
  return value;
}

function assertExactKeys(
  value: Record<string, unknown>,
  expected: readonly string[],
  path: string,
  code: "malformed_input" | "malformed_result",
): void {
  const expectedSet = new Set(expected);
  for (const key of Object.keys(value)) {
    if (!expectedSet.has(key)) {
      throw mutationError(code, path + "." + key + " is not supported");
    }
  }
  for (const key of expected) {
    if (!Object.hasOwn(value, key)) {
      throw mutationError(code, path + "." + key + " is required");
    }
  }
}

function requireRecord(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw mutationError(code, path + " must be an object");
  }
  return value as Record<string, unknown>;
}

function readNonBlankString(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw mutationError(code, path + " must be a non-blank string");
  }
  return value;
}

function readPositiveSafeInteger(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): number {
  if (!Number.isSafeInteger(value) || (value as number) < 1) {
    throw mutationError(code, path + " must be a positive safe integer");
  }
  return value as number;
}

function mutationError(
  code: MessageMutationParseErrorCode,
  message: string,
): MessageMutationParseError {
  return new MessageMutationParseError(code, message);
}
