// Generated by scripts/generate-delete-message.mjs from contracts/http/delete-message.json.
// Do not edit this file directly.

import 'identifiers.dart';
import 'message.dart';

const _trustedIdentityFields = <String>{
{{TRUSTED_IDENTITY_FIELDS}}
};
const _maxSafeInteger = 9007199254740991;

enum SoftDeleteMessageReconciliationStatus {
  applied('applied'),
  replayed('replayed'),
  revisionConflict('revision_conflict');

  const SoftDeleteMessageReconciliationStatus(this.wireValue);

  factory SoftDeleteMessageReconciliationStatus.fromJson(Object? json) =>
      switch (json) {
        'applied' => SoftDeleteMessageReconciliationStatus.applied,
        'replayed' => SoftDeleteMessageReconciliationStatus.replayed,
        'revision_conflict' =>
          SoftDeleteMessageReconciliationStatus.revisionConflict,
        _ => throw const SoftDeleteMessageFormatException(
            SoftDeleteMessageParseErrorCode.malformedResult,
            'SoftDeleteMessageResult.reconciliationStatus is unsupported.',
          ),
      };

  final String wireValue;
  String toJson() => wireValue;
}

enum SoftDeleteMessageParseErrorCode {
  malformedInput,
  trustedIdentityField,
  malformedResult,
  revisionMismatch,
}

final class SoftDeleteMessageFormatException extends FormatException {
  const SoftDeleteMessageFormatException(this.code, String message)
      : super(message);

  final SoftDeleteMessageParseErrorCode code;
}

final class SoftDeleteMessageRequest {
  const SoftDeleteMessageRequest({
    required this.messageId,
    required this.expectedRevision,
    required this.idempotencyKey,
  });

  factory SoftDeleteMessageRequest.fromJson(Object? json) {
    final object = _readObject(
      json,
      'SoftDeleteMessageRequest',
      SoftDeleteMessageParseErrorCode.malformedInput,
    );
    _rejectTrustedIdentityFields(object);
    _ensureExactFields(
      object,
      const {
{{INPUT_KEYS}}
      },
      'SoftDeleteMessageRequest',
      SoftDeleteMessageParseErrorCode.malformedInput,
    );
    if (object['operation'] != '{{OPERATION}}') {
      throw const SoftDeleteMessageFormatException(
        SoftDeleteMessageParseErrorCode.malformedInput,
        'SoftDeleteMessageRequest.operation must be {{OPERATION}}.',
      );
    }

    return SoftDeleteMessageRequest(
      messageId: MessageId(
        _readNonBlankString(
          object['messageId'],
          'SoftDeleteMessageRequest.messageId',
          SoftDeleteMessageParseErrorCode.malformedInput,
        ),
      ),
      expectedRevision: _readPositiveSafeInteger(
        object['expectedRevision'],
        'SoftDeleteMessageRequest.expectedRevision',
        SoftDeleteMessageParseErrorCode.malformedInput,
      ),
      idempotencyKey: _readNonBlankString(
        object['idempotencyKey'],
        'SoftDeleteMessageRequest.idempotencyKey',
        SoftDeleteMessageParseErrorCode.malformedInput,
      ),
    );
  }

  String get operation => '{{OPERATION}}';
  final MessageId messageId;
  final int expectedRevision;
  final String idempotencyKey;

  Map<String, Object?> toJson() => {
        'operation': operation,
        'messageId': messageId.toJson(),
        'expectedRevision': expectedRevision,
        'idempotencyKey': idempotencyKey,
      };
}

final class SoftDeleteMessageResult {
  const SoftDeleteMessageResult({
    required this.reconciliationStatus,
    required this.expectedRevision,
    required this.message,
    required this.canonicalRevision,
  });

  factory SoftDeleteMessageResult.fromJson(Object? json) {
    final object = _readObject(
      json,
      'SoftDeleteMessageResult',
      SoftDeleteMessageParseErrorCode.malformedResult,
    );
    _ensureExactFields(
      object,
      const {
{{RESULT_KEYS}}
      },
      'SoftDeleteMessageResult',
      SoftDeleteMessageParseErrorCode.malformedResult,
    );
    if (object['operation'] != '{{OPERATION}}') {
      throw const SoftDeleteMessageFormatException(
        SoftDeleteMessageParseErrorCode.malformedResult,
        'SoftDeleteMessageResult.operation must be {{OPERATION}}.',
      );
    }

    final expectedRevision = _readPositiveSafeInteger(
      object['expectedRevision'],
      'SoftDeleteMessageResult.expectedRevision',
      SoftDeleteMessageParseErrorCode.malformedResult,
    );
    final canonicalRevision = _readPositiveSafeInteger(
      object['canonicalRevision'],
      'SoftDeleteMessageResult.canonicalRevision',
      SoftDeleteMessageParseErrorCode.malformedResult,
    );
    Message message;
    try {
      message = Message.fromJson(object['message']);
    } on FormatException catch (error) {
      throw SoftDeleteMessageFormatException(
        SoftDeleteMessageParseErrorCode.malformedResult,
        'SoftDeleteMessageResult.message is malformed: ${error.message}',
      );
    }
    if (canonicalRevision != message.revision.revision) {
      throw const SoftDeleteMessageFormatException(
        SoftDeleteMessageParseErrorCode.revisionMismatch,
        'canonicalRevision must equal message.revision.revision.',
      );
    }
    if (message is DeletedMessage && message.content != null) {
      throw const SoftDeleteMessageFormatException(
        SoftDeleteMessageParseErrorCode.malformedResult,
        'A soft-delete tombstone must have null content.',
      );
    }

    final status = SoftDeleteMessageReconciliationStatus.fromJson(
      object['reconciliationStatus'],
    );
    if (status == SoftDeleteMessageReconciliationStatus.revisionConflict) {
      if (canonicalRevision == expectedRevision) {
        throw const SoftDeleteMessageFormatException(
          SoftDeleteMessageParseErrorCode.revisionMismatch,
          'A revision conflict must report a different canonical revision.',
        );
      }
    } else {
      if (canonicalRevision != expectedRevision + 1) {
        throw const SoftDeleteMessageFormatException(
          SoftDeleteMessageParseErrorCode.revisionMismatch,
          'A successful soft-delete must advance expectedRevision by exactly one.',
        );
      }
      if (message is! DeletedMessage) {
        throw const SoftDeleteMessageFormatException(
          SoftDeleteMessageParseErrorCode.malformedResult,
          'A successful soft-delete result must contain a deleted message shell.',
        );
      }
    }

    return SoftDeleteMessageResult(
      reconciliationStatus: status,
      expectedRevision: expectedRevision,
      message: message,
      canonicalRevision: canonicalRevision,
    );
  }

  String get operation => '{{OPERATION}}';
  final SoftDeleteMessageReconciliationStatus reconciliationStatus;
  final int expectedRevision;
  final Message message;
  final int canonicalRevision;

  Map<String, Object?> toJson() => {
        'operation': operation,
        'reconciliationStatus': reconciliationStatus.toJson(),
        'expectedRevision': expectedRevision,
        'message': message.toJson(),
        'canonicalRevision': canonicalRevision,
      };
}

void _rejectTrustedIdentityFields(Map<String, Object?> input) {
  for (final key in input.keys) {
    final normalized = key.replaceAll(RegExp('[^a-zA-Z0-9]'), '').toLowerCase();
    if (_trustedIdentityFields.contains(normalized)) {
      throw SoftDeleteMessageFormatException(
        SoftDeleteMessageParseErrorCode.trustedIdentityField,
        'SoftDeleteMessageRequest.$key is server-derived and cannot be supplied by a client.',
      );
    }
  }
}

Map<String, Object?> _readObject(
  Object? value,
  String path,
  SoftDeleteMessageParseErrorCode code,
) {
  if (value is! Map<String, Object?>) {
    throw SoftDeleteMessageFormatException(
        code, '$path must be a JSON object.');
  }
  return value;
}

void _ensureExactFields(
  Map<String, Object?> object,
  Set<String> expected,
  String path,
  SoftDeleteMessageParseErrorCode code,
) {
  for (final key in object.keys) {
    if (!expected.contains(key)) {
      throw SoftDeleteMessageFormatException(
        code,
        '$path.$key is not supported.',
      );
    }
  }
  for (final key in expected) {
    if (!object.containsKey(key)) {
      throw SoftDeleteMessageFormatException(code, '$path.$key is required.');
    }
  }
}

String _readNonBlankString(
  Object? value,
  String path,
  SoftDeleteMessageParseErrorCode code,
) {
  if (value is! String || value.trim().isEmpty) {
    throw SoftDeleteMessageFormatException(
      code,
      '$path must be a non-blank string.',
    );
  }
  return value;
}

int _readPositiveSafeInteger(
  Object? value,
  String path,
  SoftDeleteMessageParseErrorCode code,
) {
  if (value is! int || value < 1 || value > _maxSafeInteger) {
    throw SoftDeleteMessageFormatException(
      code,
      '$path must be a positive safe integer.',
    );
  }
  return value;
}
