// Generated by scripts/generate-draft.mjs from contracts/http/draft.json.
// Do not edit the generated output directly.

import type {
  AttachmentId,
  ConversationId,
  IsoTimestamp,
  TenantId,
  UserId,
} from "./identifiers.js";
import type { MessageMention, MessageReplyReference } from "./message.js";
import { parseChatEvent, type ChatEvent } from "./realtime.js";

/** Descriptor-owned wire metadata for draft synchronization. */
export const DRAFT_MUTATION_METHOD = "{{METHOD}}" as const;
export const DRAFT_MUTATION_PATH = "{{PATH}}" as const;
export const DRAFT_MUTATION_OPERATION = "{{OPERATION}}" as const;
export const DRAFT_UPDATED_EVENT_TYPE = "{{EVENT_TYPE}}" as const;

/** Safe transport bound for one draft body, measured after UTF-8 encoding. */
export const MAX_DRAFT_TEXT_UTF8_BYTES = __MAX_TEXT_UTF8_BYTES__;

/** Matches persisted chat identifier and idempotency-key UTF-8 bounds. */
export const MAX_DRAFT_IDENTIFIER_UTF8_BYTES = __MAX_IDENTIFIER_UTF8_BYTES__;

/** Matches `chat_idempotency_keys.client_key`. */
export const MAX_DRAFT_IDEMPOTENCY_KEY_UTF8_BYTES =
  __MAX_IDEMPOTENCY_UTF8_BYTES__;

/** Prevents one draft mutation from carrying an unbounded reference list. */
export const MAX_DRAFT_MENTION_REFERENCES = __MAX_MENTION_REFERENCES__;

/** Prevents one draft mutation from carrying an unbounded reference list. */
export const MAX_DRAFT_ATTACHMENT_REFERENCES = __MAX_ATTACHMENT_REFERENCES__;

const ISO_TIMESTAMP_PATTERN =
  /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;

const SERVER_DERIVED_FIELDS = new Set([
  "tenant",
  "tenantid",
  "organization",
  "organizationid",
  "actor",
  "actorid",
  "actorcontext",
  "actoruserid",
  "currentactor",
  "currentactorid",
  "currentuser",
  "currentuserid",
  "user",
  "userid",
  "principal",
  "principalid",
  "subject",
  "subjectid",
  "authenticateduser",
  "authenticateduserid",
  "identity",
  "session",
  "sessionid",
  "auth",
  "authorization",
  "role",
  "roles",
  "capability",
  "capabilities",
  "permission",
  "permissions",
]);

/** Compile-time guard for identity and authorization resolved by the server. */
export interface NoTrustedDraftMutationContext {
  readonly tenant?: never;
  readonly tenantId?: never;
  readonly organization?: never;
  readonly organizationId?: never;
  readonly actor?: never;
  readonly actorId?: never;
  readonly actorContext?: never;
  readonly actorUserId?: never;
  readonly currentActor?: never;
  readonly currentActorId?: never;
  readonly currentUser?: never;
  readonly currentUserId?: never;
  readonly user?: never;
  readonly userId?: never;
  readonly principal?: never;
  readonly principalId?: never;
  readonly subject?: never;
  readonly subjectId?: never;
  readonly authenticatedUser?: never;
  readonly authenticatedUserId?: never;
  readonly identity?: never;
  readonly session?: never;
  readonly sessionId?: never;
  readonly auth?: never;
  readonly authorization?: never;
  readonly role?: never;
  readonly roles?: never;
  readonly capability?: never;
  readonly capabilities?: never;
  readonly permission?: never;
  readonly permissions?: never;
}

export interface DraftAttachmentReference {
  readonly attachmentId: AttachmentId;
}

/** Drafts deliberately support only renderer-safe text formats and references. */
export type DraftContent = {
  readonly format: "plain" | "markdown";
  readonly text: string;
  /** Composition metadata for top-level send replyTo, never editable MessageContent. */
  readonly replyTo?: MessageReplyReference;
  readonly mentions?: readonly MessageMention[];
  readonly attachments: readonly DraftAttachmentReference[];
};

export type DraftMutationIntent = "replace" | "clear";

interface DraftMutationInputBase<Intent extends DraftMutationIntent>
  extends NoTrustedDraftMutationContext {
  readonly operation: "synchronize_draft";
  readonly intent: Intent;
  readonly conversationId: ConversationId;
  /** Zero means the caller has not observed a persisted draft yet. */
  readonly baseRevision: number;
  /** Caller-generated identity for reconciling this device-local mutation. */
  readonly deviceMutationId: string;
  readonly idempotencyKey: string;
}

export interface ReplaceDraftInput
  extends DraftMutationInputBase<"replace"> {
  readonly content: DraftContent;
}

export interface ClearDraftInput extends DraftMutationInputBase<"clear"> {
  readonly content?: never;
}

/** Explicit replace/clear intent; boolean and toggle semantics are unsupported. */
export type SynchronizeDraftInput = ReplaceDraftInput | ClearDraftInput;

export interface CanonicalReplacedDraft {
  readonly kind: "replaced";
  readonly content: DraftContent;
}

/** A retained tombstone prevents an older device from restoring cleared text. */
export interface CanonicalClearDraftTombstone {
  readonly kind: "clear_tombstone";
  readonly content: null;
}

export type CanonicalDraftState =
  | CanonicalReplacedDraft
  | CanonicalClearDraftTombstone;

export type DraftMutationReconciliationStatus =
  | "applied"
  | "replayed"
  | "stale_base";

interface DraftMutationResultBase<Intent extends DraftMutationIntent> {
  readonly operation: "synchronize_draft";
  readonly intent: Intent;
  readonly reconciliationStatus: DraftMutationReconciliationStatus;
  readonly conversationId: ConversationId;
  /** Exact request echoes used to settle the correct local mutation. */
  readonly baseRevision: number;
  readonly deviceMutationId: string;
  readonly idempotencyKey: string;
  readonly canonicalRevision: number;
  readonly canonicalUpdatedAt: IsoTimestamp;
}

type RequestedCanonicalDraftState<Intent extends DraftMutationIntent> =
  Intent extends "replace"
    ? CanonicalReplacedDraft
    : CanonicalClearDraftTombstone;

type SettledDraftMutationResult<Intent extends DraftMutationIntent> =
  DraftMutationResultBase<Intent> & {
    readonly reconciliationStatus: "applied" | "replayed";
    readonly draft: RequestedCanonicalDraftState<Intent>;
  };

type StaleDraftMutationResult<Intent extends DraftMutationIntent> =
  DraftMutationResultBase<Intent> & {
    /** Deterministic conflict carrying the current authoritative draft state. */
    readonly reconciliationStatus: "stale_base";
    readonly draft: CanonicalDraftState;
  };

export type ReplaceDraftResult =
  | SettledDraftMutationResult<"replace">
  | StaleDraftMutationResult<"replace">;

export type ClearDraftResult =
  | SettledDraftMutationResult<"clear">
  | StaleDraftMutationResult<"clear">;

export type SynchronizeDraftResult = ReplaceDraftResult | ClearDraftResult;

/** Exact server-emitted payload for a private cross-device draft update. */
export interface ConversationDraftUpdatedPayload {
  /** Trusted user whose private draft stream owns this event. */
  readonly actorUserId: UserId;
  readonly input: SynchronizeDraftInput;
  readonly result: SynchronizeDraftResult;
}

export type DraftUpdatedPayload = ConversationDraftUpdatedPayload;
export type DraftUpdatedUserStreamId = `user:${string}`;

/** Draft updates are private to the actor and never use conversation streams. */
export interface ConversationDraftUpdatedEvent
  extends ChatEvent<ConversationDraftUpdatedPayload> {
  readonly type: "conversation.draft.updated";
  readonly streamId: DraftUpdatedUserStreamId;
}

export type DraftUpdatedEvent = ConversationDraftUpdatedEvent;

export type DraftMutationParseErrorCode =
  | "malformed_input"
  | "trusted_identity_field"
  | "malformed_identifier"
  | "malformed_revision"
  | "malformed_content"
  | "unsafe_content"
  | "duplicate_mention_reference"
  | "duplicate_attachment_reference"
  | "malformed_result"
  | "incoherent_result"
  | "malformed_event";

export class DraftMutationParseError extends Error {
  readonly code: DraftMutationParseErrorCode;

  constructor(code: DraftMutationParseErrorCode, message: string) {
    super(message);
    this.name = "DraftMutationParseError";
    this.code = code;
  }
}

const BASE_INPUT_KEYS = [
  "operation",
  "intent",
  "conversationId",
  "baseRevision",
  "deviceMutationId",
  "idempotencyKey",
] as const;
const REPLACE_INPUT_KEYS = [...BASE_INPUT_KEYS, "content"] as const;
const RESULT_KEYS = [
  "operation",
  "intent",
  "reconciliationStatus",
  "conversationId",
  "baseRevision",
  "deviceMutationId",
  "idempotencyKey",
  "canonicalRevision",
  "canonicalUpdatedAt",
  "draft",
] as const;

export function parseReplaceDraftInput(value: unknown): ReplaceDraftInput {
  const input = parseInputRecord(value);
  if (input.intent !== "replace") {
    throw draftError("malformed_input", "input.intent must be replace");
  }
  return parseReplaceInputRecord(input);
}

export function parseClearDraftInput(value: unknown): ClearDraftInput {
  const input = parseInputRecord(value);
  if (input.intent !== "clear") {
    throw draftError("malformed_input", "input.intent must be clear");
  }
  return parseClearInputRecord(input);
}

export function parseSynchronizeDraftInput(
  value: unknown,
): SynchronizeDraftInput {
  const input = parseInputRecord(value);
  if (input.intent === "replace") return parseReplaceInputRecord(input);
  if (input.intent === "clear") return parseClearInputRecord(input);
  throw draftError(
    "malformed_input",
    "input.intent must be replace or clear; toggle semantics are not supported",
  );
}

/** Parses an authoritative result and proves coherence with its exact request. */
export function parseSynchronizeDraftResult(
  value: unknown,
  expectedInput: SynchronizeDraftInput,
): SynchronizeDraftResult {
  const request = parseSynchronizeDraftInput(expectedInput);
  const result = requireRecord(value, "result", "malformed_result");
  assertExactKeys(result, RESULT_KEYS, "result", "malformed_result");

  if (result.operation !== "synchronize_draft") {
    throw draftError(
      "malformed_result",
      "result.operation must be synchronize_draft",
    );
  }

  const intent = readIntent(result.intent, "malformed_result");
  const reconciliationStatus = readReconciliationStatus(
    result.reconciliationStatus,
  );
  const conversationId = readIdentifier(
    result.conversationId,
    "result.conversationId",
    "malformed_result",
  ) as ConversationId;
  const baseRevision = readBaseRevision(
    result.baseRevision,
    "result.baseRevision",
    "malformed_result",
  );
  const deviceMutationId = readIdentifier(
    result.deviceMutationId,
    "result.deviceMutationId",
    "malformed_result",
  );
  const idempotencyKey = readBoundedIdempotencyKey(
    result.idempotencyKey,
    "result.idempotencyKey",
    "malformed_result",
  );
  const canonicalRevision = readCanonicalRevision(result.canonicalRevision);
  const canonicalUpdatedAt = readIsoTimestamp(result.canonicalUpdatedAt);
  const draft = parseCanonicalDraftState(result.draft);

  if (
    intent !== request.intent ||
    conversationId !== request.conversationId ||
    baseRevision !== request.baseRevision ||
    deviceMutationId !== request.deviceMutationId ||
    idempotencyKey !== request.idempotencyKey
  ) {
    throw draftError(
      "incoherent_result",
      "result intent and request identity fields must exactly match the request",
    );
  }

  if (reconciliationStatus === "stale_base") {
    if (canonicalRevision <= baseRevision) {
      throw draftError(
        "incoherent_result",
        "a stale-base result must carry a canonical revision newer than baseRevision",
      );
    }
  } else {
    if (canonicalRevision !== baseRevision + 1) {
      throw draftError(
        "incoherent_result",
        "an applied or replayed result must advance baseRevision by one",
      );
    }
    assertRequestedStateMatches(request, draft);
  }

  return {
    operation: "synchronize_draft",
    intent,
    reconciliationStatus,
    conversationId,
    baseRevision,
    deviceMutationId,
    idempotencyKey,
    canonicalRevision,
    canonicalUpdatedAt,
    draft,
  } as SynchronizeDraftResult;
}

/** Parses the private durable envelope emitted by the existing server command. */
export function parseConversationDraftUpdatedEvent(
  value: unknown,
  expectedTenantId: TenantId,
): ConversationDraftUpdatedEvent {
  const record = requireRecord(value, "event", "malformed_event");
  assertExactKeys(
    record,
    [
      "eventId",
      "protocolVersion",
      "tenantId",
      "streamId",
      "type",
      "occurredAt",
      "payload",
    ],
    "event",
    "malformed_event",
  );

  let event: ChatEvent<ConversationDraftUpdatedPayload>;
  try {
    event = parseChatEvent(record, expectedTenantId, parseDraftUpdatedPayload);
  } catch (error) {
    if (error instanceof DraftMutationParseError) throw error;
    throw draftError(
      "malformed_event",
      error instanceof Error ? error.message : "event is malformed",
    );
  }

  if (event.type !== "conversation.draft.updated") {
    throw draftError(
      "malformed_event",
      "event.type must be conversation.draft.updated",
    );
  }
  if (event.streamId !== `user:${event.payload.actorUserId}`) {
    throw draftError(
      "malformed_event",
      "event.streamId must identify the actor's private user stream",
    );
  }

  return {
    ...event,
    type: "conversation.draft.updated",
    streamId: event.streamId as DraftUpdatedUserStreamId,
  };
}

/** Short alias matching the generated model name used by Dart. */
export const parseDraftUpdatedEvent = parseConversationDraftUpdatedEvent;

function parseDraftUpdatedPayload(
  value: unknown,
): ConversationDraftUpdatedPayload {
  const payload = requireRecord(value, "event.payload", "malformed_event");
  assertExactKeys(
    payload,
    ["actorUserId", "input", "result"],
    "event.payload",
    "malformed_event",
  );
  const actorUserId = readIdentifier(
    payload.actorUserId,
    "event.payload.actorUserId",
    "malformed_event",
  ) as UserId;
  const input = parseSynchronizeDraftInput(payload.input);
  const result = parseSynchronizeDraftResult(payload.result, input);
  return { actorUserId, input, result };
}

function parseInputRecord(value: unknown): Record<string, unknown> {
  rejectServerDerivedFields(value);
  const input = requireRecord(value, "input", "malformed_input");
  if (input.operation !== "synchronize_draft") {
    throw draftError(
      "malformed_input",
      "input.operation must be synchronize_draft",
    );
  }
  return input;
}

function parseReplaceInputRecord(
  input: Record<string, unknown>,
): ReplaceDraftInput {
  assertExactKeys(input, REPLACE_INPUT_KEYS, "input", "malformed_input");
  return {
    ...parseInputBase(input, "replace"),
    content: parseDraftContent(
      input.content,
      "input.content",
      "malformed_content",
    ),
  };
}

function parseClearInputRecord(input: Record<string, unknown>): ClearDraftInput {
  assertExactKeys(input, BASE_INPUT_KEYS, "input", "malformed_input");
  return parseInputBase(input, "clear");
}

function parseInputBase<Intent extends DraftMutationIntent>(
  input: Record<string, unknown>,
  intent: Intent,
): DraftMutationInputBase<Intent> {
  if (input.intent !== intent) {
    throw draftError("malformed_input", `input.intent must be ${intent}`);
  }
  return {
    operation: "synchronize_draft",
    intent,
    conversationId: readIdentifier(
      input.conversationId,
      "input.conversationId",
      "malformed_input",
    ) as ConversationId,
    baseRevision: readBaseRevision(
      input.baseRevision,
      "input.baseRevision",
      "malformed_input",
    ),
    deviceMutationId: readIdentifier(
      input.deviceMutationId,
      "input.deviceMutationId",
      "malformed_input",
    ),
    idempotencyKey: readBoundedIdempotencyKey(
      input.idempotencyKey,
      "input.idempotencyKey",
      "malformed_input",
    ),
  };
}

function parseCanonicalDraftState(value: unknown): CanonicalDraftState {
  const state = requireRecord(
    value,
    "result.draft",
    "malformed_result",
  );
  if (state.kind === "replaced") {
    assertExactKeys(
      state,
      ["kind", "content"],
      "result.draft",
      "malformed_result",
    );
    return {
      kind: "replaced",
      content: parseDraftContent(
        state.content,
        "result.draft.content",
        "malformed_result",
      ),
    };
  }
  if (state.kind === "clear_tombstone") {
    assertExactKeys(
      state,
      ["kind", "content"],
      "result.draft",
      "malformed_result",
    );
    if (state.content !== null) {
      throw draftError(
        "malformed_result",
        "a clear tombstone must carry null content",
      );
    }
    return { kind: "clear_tombstone", content: null };
  }
  throw draftError(
    "malformed_result",
    "result.draft.kind must be replaced or clear_tombstone",
  );
}

function parseDraftContent(
  value: unknown,
  path: string,
  code: "malformed_content" | "malformed_result",
): DraftContent {
  const content = requireRecord(value, path, code);
  assertExactKeys(
    content,
    [
      "format", "text", "attachments",
      ...(Object.hasOwn(content, "mentions") ? ["mentions"] : []),
      ...(Object.hasOwn(content, "replyTo") ? ["replyTo"] : []),
    ],
    path,
    code,
  );
  if (content.format !== "plain" && content.format !== "markdown") {
    throw draftError(code, `${path}.format must be plain or markdown`);
  }
  if (typeof content.text !== "string") {
    throw draftError(code, `${path}.text must be a string`);
  }
  if (containsUnsafeUnicode(content.text)) {
    throw draftError(
      "unsafe_content",
      `${path}.text contains unsafe control characters or malformed Unicode`,
    );
  }
  if (utf8ByteLength(content.text) > MAX_DRAFT_TEXT_UTF8_BYTES) {
    throw draftError(
      code,
      `${path}.text cannot exceed ${MAX_DRAFT_TEXT_UTF8_BYTES} UTF-8 bytes`,
    );
  }
  let mentions: readonly MessageMention[] | undefined;
  if (Object.hasOwn(content, "mentions")) {
    if (!Array.isArray(content.mentions)) {
      throw draftError(code, `${path}.mentions must be an array`);
    }
    if (content.mentions.length > MAX_DRAFT_MENTION_REFERENCES) {
      throw draftError(
        code,
        `${path}.mentions cannot contain more than ${MAX_DRAFT_MENTION_REFERENCES} references`,
      );
    }
    const seenMentionIdentities = new Set<string>();
    mentions = content.mentions.map((value, index) => {
      const mention = parseDraftMention(value, `${path}.mentions[${index}]`, code);
      const identity = mentionIdentity(mention);
      if (seenMentionIdentities.has(identity)) {
        throw draftError(
          "duplicate_mention_reference",
          `${path}.mentions cannot contain duplicate mention references`,
        );
      }
      seenMentionIdentities.add(identity);
      return mention;
    });
  }
  if (!Array.isArray(content.attachments)) {
    throw draftError(code, `${path}.attachments must be an array`);
  }
  if (content.attachments.length > MAX_DRAFT_ATTACHMENT_REFERENCES) {
    throw draftError(
      code,
      `${path}.attachments cannot contain more than ${MAX_DRAFT_ATTACHMENT_REFERENCES} references`,
    );
  }

  const seenAttachmentIds = new Set<string>();
  const attachments = content.attachments.map((value, index) => {
    const referencePath = `${path}.attachments[${index}]`;
    const reference = requireRecord(value, referencePath, code);
    assertExactKeys(reference, ["attachmentId"], referencePath, code);
    const attachmentId = readIdentifier(
      reference.attachmentId,
      `${referencePath}.attachmentId`,
      code,
    ) as AttachmentId;
    if (seenAttachmentIds.has(attachmentId)) {
      throw draftError(
        "duplicate_attachment_reference",
        `${path}.attachments cannot contain duplicate attachmentId values`,
      );
    }
    seenAttachmentIds.add(attachmentId);
    return { attachmentId };
  });

  return {
    format: content.format,
    text: content.text,
    ...(Object.hasOwn(content, "replyTo")
      ? { replyTo: parseDraftReplyReference(content.replyTo, `${path}.replyTo`, code) }
      : {}),
    ...(mentions === undefined ? {} : { mentions }),
    attachments,
  };
}

/** @internal Shared by draft mutation and actor-private snapshot parsers. */
export function parseDraftReplyReference(
  value: unknown,
  path: string,
  code: "malformed_content" | "malformed_result",
): MessageReplyReference {
  const reference = requireRecord(value, path, code);
  assertExactKeys(reference, ["messageId", "notifyAuthor"], path, code);
  const messageId = readIdentifier(reference.messageId, `${path}.messageId`, code);
  if (/[\x00-\x1f\x7f-\x9f\u2028\u2029]/u.test(messageId)) {
    throw draftError(
      "malformed_identifier",
      `${path}.messageId must be a safe identifier`,
    );
  }
  if (typeof reference.notifyAuthor !== "boolean") {
    throw draftError(code, `${path}.notifyAuthor must be a boolean`);
  }
  return {
    messageId: messageId as MessageReplyReference["messageId"],
    notifyAuthor: reference.notifyAuthor,
  };
}

function parseDraftMention(
  value: unknown,
  path: string,
  code: "malformed_content" | "malformed_result",
): MessageMention {
  const mention = requireRecord(value, path, code);
  if (mention.type === "user") {
    assertExactKeys(mention, ["type", "userId"], path, code);
    return {
      type: "user",
      userId: readIdentifier(mention.userId, `${path}.userId`, code) as UserId,
    };
  }
  if (mention.type === "conversation") {
    assertExactKeys(mention, ["type", "conversationId"], path, code);
    return {
      type: "conversation",
      conversationId: readIdentifier(
        mention.conversationId,
        `${path}.conversationId`,
        code,
      ) as ConversationId,
    };
  }
  if (mention.type === "entity") {
    assertExactKeys(mention, ["type", "entity"], path, code);
    const entity = requireRecord(mention.entity, `${path}.entity`, code);
    assertExactKeys(entity, ["type", "id"], `${path}.entity`, code);
    return {
      type: "entity",
      entity: {
        type: readIdentifier(entity.type, `${path}.entity.type`, code),
        id: readIdentifier(entity.id, `${path}.entity.id`, code),
      },
    };
  }
  throw draftError(code, `${path}.type must be user, conversation, or entity`);
}

function mentionIdentity(mention: MessageMention): string {
  switch (mention.type) {
    case "user":
      return `user:${mention.userId}`;
    case "conversation":
      return `conversation:${mention.conversationId}`;
    case "entity":
      return `entity:${mention.entity.type}\u0000${mention.entity.id}`;
  }
}

function assertRequestedStateMatches(
  request: SynchronizeDraftInput,
  draft: CanonicalDraftState,
): void {
  if (request.intent === "clear") {
    if (draft.kind !== "clear_tombstone") {
      throw draftError(
        "incoherent_result",
        "a settled clear result must carry a clear tombstone",
      );
    }
    return;
  }
  if (
    draft.kind !== "replaced" ||
    !draftContentEquals(draft.content, request.content)
  ) {
    throw draftError(
      "incoherent_result",
      "a settled replace result must carry the exact requested canonical content",
    );
  }
}

function draftContentEquals(left: DraftContent, right: DraftContent): boolean {
  return (
    left.format === right.format &&
    left.text === right.text &&
    left.replyTo?.messageId === right.replyTo?.messageId &&
    left.replyTo?.notifyAuthor === right.replyTo?.notifyAuthor &&
    (left.mentions === undefined
      ? right.mentions === undefined
      : right.mentions !== undefined &&
        left.mentions.length === right.mentions.length &&
        left.mentions.every(
          (mention, index) =>
            mentionIdentity(mention) === mentionIdentity(right.mentions![index]!),
        )) &&
    left.attachments.length === right.attachments.length &&
    left.attachments.every(
      (reference, index) =>
        reference.attachmentId === right.attachments[index]?.attachmentId,
    )
  );
}

function readIntent(
  value: unknown,
  code: "malformed_input" | "malformed_result",
): DraftMutationIntent {
  if (value !== "replace" && value !== "clear") {
    throw draftError(code, "intent must be replace or clear");
  }
  return value;
}

function readReconciliationStatus(
  value: unknown,
): DraftMutationReconciliationStatus {
  if (value !== "applied" && value !== "replayed" && value !== "stale_base") {
    throw draftError(
      "malformed_result",
      "result.reconciliationStatus must be applied, replayed, or stale_base",
    );
  }
  return value;
}

function readBaseRevision(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): number {
  if (
    !Number.isSafeInteger(value) ||
    (value as number) < 0 ||
    (value as number) >= Number.MAX_SAFE_INTEGER
  ) {
    throw draftError(
      "malformed_revision",
      `${path} must be a nonnegative safe integer that can advance by one`,
    );
  }
  return value as number;
}

function readCanonicalRevision(value: unknown): number {
  if (!Number.isSafeInteger(value) || (value as number) < 1) {
    throw draftError(
      "malformed_revision",
      "result.canonicalRevision must be a positive safe integer",
    );
  }
  return value as number;
}

function readIdentifier(
  value: unknown,
  path: string,
  code:
    | "malformed_input"
    | "malformed_result"
    | "malformed_content"
    | "malformed_event",
): string {
  if (
    typeof value !== "string" ||
    value.length === 0 ||
    value.trim() !== value ||
    value !== value.normalize("NFC") ||
    containsUnsafeUnicode(value) ||
    utf8ByteLength(value) > MAX_DRAFT_IDENTIFIER_UTF8_BYTES
  ) {
    throw draftError(
      "malformed_identifier",
      `${path} must be a safe, NFC-normalized identifier of at most ${MAX_DRAFT_IDENTIFIER_UTF8_BYTES} UTF-8 bytes`,
    );
  }
  return value;
}

function readBoundedIdempotencyKey(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): string {
  if (
    typeof value !== "string" ||
    value.trim().length === 0 ||
    value.trim() !== value ||
    containsUnsafeUnicode(value) ||
    utf8ByteLength(value) > MAX_DRAFT_IDEMPOTENCY_KEY_UTF8_BYTES
  ) {
    throw draftError(
      code,
      `${path} must be a safe nonblank string of at most ${MAX_DRAFT_IDEMPOTENCY_KEY_UTF8_BYTES} UTF-8 bytes`,
    );
  }
  return value;
}

function readIsoTimestamp(value: unknown): IsoTimestamp {
  if (
    typeof value !== "string" ||
    !ISO_TIMESTAMP_PATTERN.test(value) ||
    !Number.isFinite(Date.parse(value))
  ) {
    throw draftError(
      "malformed_result",
      "result.canonicalUpdatedAt must be an ISO-8601 timestamp",
    );
  }
  return value;
}

function rejectServerDerivedFields(value: unknown, path = "input"): void {
  if (Array.isArray(value)) {
    value.forEach((entry, index) =>
      rejectServerDerivedFields(entry, `${path}[${index}]`),
    );
    return;
  }
  if (!isRecord(value)) return;

  for (const [key, nested] of Object.entries(value)) {
    const normalizedKey = key.replaceAll(/[^a-zA-Z0-9]/g, "").toLowerCase();
    const isDraftUserMentionId =
      key === "userId" &&
      value.type === "user" &&
      /^input\.content\.mentions\[\d+\]$/.test(path);
    if (SERVER_DERIVED_FIELDS.has(normalizedKey) && !isDraftUserMentionId) {
      throw draftError(
        "trusted_identity_field",
        `${path}.${key} is server-derived and cannot be supplied by a client`,
      );
    }
    rejectServerDerivedFields(nested, `${path}.${key}`);
  }
}

function assertExactKeys(
  value: Record<string, unknown>,
  expected: readonly string[],
  path: string,
  code:
    | "malformed_input"
    | "malformed_result"
    | "malformed_content"
    | "malformed_event",
): void {
  const expectedSet = new Set(expected);
  for (const key of Object.keys(value)) {
    if (!expectedSet.has(key)) {
      throw draftError(code, `${path}.${key} is not supported`);
    }
  }
  for (const key of expected) {
    if (!Object.hasOwn(value, key)) {
      throw draftError(code, `${path}.${key} is required`);
    }
  }
}

function requireRecord(
  value: unknown,
  path: string,
  code:
    | "malformed_input"
    | "malformed_result"
    | "malformed_content"
    | "malformed_event",
): Record<string, unknown> {
  if (!isRecord(value)) {
    throw draftError(code, `${path} must be an object`);
  }
  return value;
}

function containsUnsafeUnicode(value: string): boolean {
  for (let index = 0; index < value.length; index += 1) {
    const codeUnit = value.charCodeAt(index);
    if (
      (codeUnit <= 0x1f &&
        codeUnit !== 0x09 &&
        codeUnit !== 0x0a &&
        codeUnit !== 0x0d) ||
      (codeUnit >= 0x7f && codeUnit <= 0x9f)
    ) {
      return true;
    }
    if (codeUnit >= 0xd800 && codeUnit <= 0xdbff) {
      const next = value.charCodeAt(index + 1);
      if (index + 1 >= value.length || next < 0xdc00 || next > 0xdfff) return true;
      index += 1;
    } else if (codeUnit >= 0xdc00 && codeUnit <= 0xdfff) {
      return true;
    }
  }
  return false;
}

function utf8ByteLength(value: string): number {
  return new TextEncoder().encode(value).byteLength;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function draftError(
  code: DraftMutationParseErrorCode,
  message: string,
): DraftMutationParseError {
  return new DraftMutationParseError(code, message);
}
