// Generated by scripts/generate-ephemeral-signals.mjs from contracts/realtime/ephemeral.json.
// Do not edit this file directly.

import type {
  ConversationId,
  DeviceId,
  IsoTimestamp,
  SessionId,
  TenantId,
  UserId,
} from "../identifiers.js";
import { parseChatEvent, type ChatEvent, type EnabledFeatures } from "../realtime.js";

export const MAX_TYPING_SIGNAL_TTL_MS = {{TYPING_MAX_TTL}};
export const MAX_PRESENCE_SIGNAL_TTL_MS = {{PRESENCE_MAX_TTL}};
export const MIN_EPHEMERAL_SIGNAL_SEQUENCE = {{MIN_SEQUENCE}};
export const MAX_EPHEMERAL_SIGNAL_SEQUENCE = {{MAX_SEQUENCE}};

export type EphemeralSignalFeature = "typing" | "presence";

export interface PrivateConversationSignalScope {
  readonly type: "conversation";
  readonly conversationId: ConversationId;
  readonly visibility: "{{PRIVATE_VISIBILITY}}";
  readonly audience: "{{PRIVATE_AUDIENCE}}";
}

export interface PublicConversationSignalScope {
  readonly type: "conversation";
  readonly conversationId: ConversationId;
  readonly visibility: "{{PUBLIC_VISIBILITY}}";
  readonly audience: "{{PUBLIC_AUDIENCE}}";
}

export type TypingSignalScope = PrivateConversationSignalScope | PublicConversationSignalScope;

export interface UserPrivateSignalScope {
  readonly type: "{{USER_PRIVATE_SCOPE}}";
  readonly userId: UserId;
}

interface EphemeralSignalBase<Feature extends EphemeralSignalFeature> {
  readonly capability: Feature;
  readonly durability: "{{DURABILITY}}";
  readonly actorUserId: UserId;
  readonly deviceId: DeviceId;
  readonly sessionId: SessionId;
  readonly sequence: number;
  readonly sentAt: IsoTimestamp;
  readonly expiresAt: IsoTimestamp;
}

export interface TypingSignalPayload extends EphemeralSignalBase<"typing"> {
  readonly state: {{TYPING_STATE_UNION_TS}};
  readonly scope: TypingSignalScope;
}

export interface PresenceSignalPayload extends EphemeralSignalBase<"presence"> {
  readonly state: {{PRESENCE_STATE_UNION_TS}};
  readonly scope: UserPrivateSignalScope;
}

export type EphemeralSignalPayload = TypingSignalPayload | PresenceSignalPayload;

export interface TypingSignalEvent extends ChatEvent<TypingSignalPayload> {
  readonly type: "{{TYPING_EVENT_TYPE}}";
  readonly streamId: ConversationId;
}

export type UserPrivateStreamId = `{{USER_PRIVATE_PREFIX}}${string}`;

export interface PresenceSignalEvent extends ChatEvent<PresenceSignalPayload> {
  readonly type: "{{PRESENCE_EVENT_TYPE}}";
  readonly streamId: UserPrivateStreamId;
}

export type EphemeralSignalEvent = TypingSignalEvent | PresenceSignalEvent;

export interface EphemeralSignalAcceptedSessionIdentity {
  readonly actorUserId: UserId;
  readonly deviceId: DeviceId;
  readonly sessionId: SessionId;
}

export interface EphemeralSignalParseOptions {
  readonly expectedTenantId: TenantId;
  readonly enabledFeatures: EnabledFeatures<EphemeralSignalFeature>;
  readonly now: number;
  /** Pass only while parsing frames sent by this authenticated session. */
  readonly trustedAcceptedSessionIdentity?: EphemeralSignalAcceptedSessionIdentity;
}

export type EphemeralSignalParseErrorCode =
  | "malformed_signal"
  | "unsupported_capability"
  | "expired_signal"
  | "identity_mismatch";

export class EphemeralSignalParseError extends Error {
  readonly code: EphemeralSignalParseErrorCode;
  constructor(code: EphemeralSignalParseErrorCode, message: string) {
    super(message);
    this.name = "EphemeralSignalParseError";
    this.code = code;
  }
}

export function parseEphemeralSignalEvent(
  value: unknown,
  options: EphemeralSignalParseOptions,
): EphemeralSignalEvent {
  if (!Number.isFinite(options.now)) throw new TypeError("now must be a finite millisecond timestamp");
  if (!isRecord(value)) throw malformedSignal("signal event must be an object");
  assertExactKeys(value, ["eventId", "protocolVersion", "tenantId", "streamId", "type", "occurredAt", "payload"]);
  const event = parseChatEvent(value, options.expectedTenantId);

  if (event.type === "{{TYPING_EVENT_TYPE}}") {
    assertCapabilityEnabled("typing", options.enabledFeatures);
    const payload = parseTypingSignalPayload(event.payload, options);
    if (event.streamId !== payload.scope.conversationId) throw malformedSignal("typing streamId must match scope.conversationId");
    if (event.occurredAt !== payload.sentAt) throw malformedSignal("occurredAt must match payload.sentAt");
    return { ...event, type: "{{TYPING_EVENT_TYPE}}", streamId: event.streamId as ConversationId, payload };
  }
  if (event.type === "{{PRESENCE_EVENT_TYPE}}") {
    assertCapabilityEnabled("presence", options.enabledFeatures);
    const payload = parsePresenceSignalPayload(event.payload, options);
    if (event.streamId !== `{{USER_PRIVATE_PREFIX}}${payload.scope.userId}`) throw malformedSignal("presence streamId must match its user-private scope");
    if (event.occurredAt !== payload.sentAt) throw malformedSignal("occurredAt must match payload.sentAt");
    if (options.trustedAcceptedSessionIdentity !== undefined && payload.scope.userId !== options.trustedAcceptedSessionIdentity.actorUserId) {
      throw identityMismatch("presence must target the accepted actor's private user stream");
    }
    return { ...event, type: "{{PRESENCE_EVENT_TYPE}}", streamId: event.streamId as UserPrivateStreamId, payload };
  }
  throw malformedSignal("event type must be {{TYPING_EVENT_TYPE}} or {{PRESENCE_EVENT_TYPE}}");
}

function parseTypingSignalPayload(value: unknown, options: EphemeralSignalParseOptions): TypingSignalPayload {
  const payload = parseSignalBase(value, "typing", MAX_TYPING_SIGNAL_TTL_MS, options);
  const state = readEnum(payload, "state", [{{TYPING_STATES_TS}}] as const);
  return { ...payload, capability: "typing", state, scope: parseTypingScope(payload.scope) };
}

function parsePresenceSignalPayload(value: unknown, options: EphemeralSignalParseOptions): PresenceSignalPayload {
  const payload = parseSignalBase(value, "presence", MAX_PRESENCE_SIGNAL_TTL_MS, options);
  const state = readEnum(payload, "state", [{{PRESENCE_STATES_TS}}] as const);
  return { ...payload, capability: "presence", state, scope: parseUserPrivateScope(payload.scope) };
}

function parseSignalBase(
  value: unknown,
  feature: EphemeralSignalFeature,
  maximumTtl: number,
  options: EphemeralSignalParseOptions,
) {
  if (!isRecord(value)) throw malformedSignal("signal payload must be an object");
  assertExactKeys(value, ["capability", "durability", "actorUserId", "deviceId", "sessionId", "sequence", "sentAt", "expiresAt", "state", "scope"]);
  if (value.capability !== feature) throw malformedSignal(`capability must be ${feature}`);
  if (value.durability !== "{{DURABILITY}}") throw malformedSignal("durability must be {{DURABILITY}}");
  const actorUserId = readId(value, "actorUserId") as UserId;
  const deviceId = readId(value, "deviceId") as DeviceId;
  const sessionId = readId(value, "sessionId") as SessionId;
  const sequence = readSequence(value.sequence);
  const sentAt = readTimestamp(value, "sentAt");
  const expiresAt = readTimestamp(value, "expiresAt");
  const ttl = Date.parse(expiresAt) - Date.parse(sentAt);
  if (ttl <= 0 || ttl > maximumTtl) throw malformedSignal(`signal TTL must be between 1 and ${maximumTtl} milliseconds`);
  if (Date.parse(expiresAt) <= options.now) throw new EphemeralSignalParseError("expired_signal", "signal has already expired");
  const trusted = options.trustedAcceptedSessionIdentity;
  if (trusted !== undefined && (actorUserId !== trusted.actorUserId || deviceId !== trusted.deviceId || sessionId !== trusted.sessionId)) {
    throw identityMismatch("signal provenance does not match the accepted session");
  }
  return {
    durability: "{{DURABILITY}}" as const,
    actorUserId,
    deviceId,
    sessionId,
    sequence,
    sentAt,
    expiresAt,
    state: value.state,
    scope: value.scope,
  };
}

function parseTypingScope(value: unknown): TypingSignalScope {
  if (!isRecord(value)) throw malformedSignal("typing scope must be an object");
  assertExactKeys(value, ["type", "conversationId", "visibility", "audience"]);
  if (value.type !== "conversation") throw malformedSignal("typing scope must be conversation-scoped");
  const conversationId = readId(value, "conversationId") as ConversationId;
  if (value.visibility === "{{PRIVATE_VISIBILITY}}" && value.audience === "{{PRIVATE_AUDIENCE}}") return { type: "conversation", conversationId, visibility: "{{PRIVATE_VISIBILITY}}", audience: "{{PRIVATE_AUDIENCE}}" };
  if (value.visibility === "{{PUBLIC_VISIBILITY}}" && value.audience === "{{PUBLIC_AUDIENCE}}") return { type: "conversation", conversationId, visibility: "{{PUBLIC_VISIBILITY}}", audience: "{{PUBLIC_AUDIENCE}}" };
  throw malformedSignal("public typing scope must target {{PUBLIC_AUDIENCE}}; private scope must target {{PRIVATE_AUDIENCE}}");
}

function parseUserPrivateScope(value: unknown): UserPrivateSignalScope {
  if (!isRecord(value)) throw malformedSignal("presence scope must be an object");
  assertExactKeys(value, ["type", "userId"]);
  if (value.type !== "{{USER_PRIVATE_SCOPE}}") throw malformedSignal("presence scope must be {{USER_PRIVATE_SCOPE}}");
  return { type: "{{USER_PRIVATE_SCOPE}}", userId: readId(value, "userId") as UserId };
}

function assertCapabilityEnabled(capability: EphemeralSignalFeature, enabled: EnabledFeatures<EphemeralSignalFeature>): void {
  if (enabled[capability] !== true) throw new EphemeralSignalParseError("unsupported_capability", `${capability} was not advertised by the server`);
}

function assertExactKeys(value: Record<string, unknown>, expected: readonly string[]): void {
  const keys = Object.keys(value);
  const allowed = new Set(expected);
  if (keys.length !== expected.length || keys.some((key) => !allowed.has(key))) throw malformedSignal("signal contains missing or unknown fields");
}

function readId(value: Record<string, unknown>, field: string): string {
  const item = value[field];
  if (typeof item !== "string" || item.trim().length === 0) throw malformedSignal(`${field} must be a non-empty string`);
  return item;
}

function readSequence(value: unknown): number {
  if (!Number.isSafeInteger(value) || (value as number) < MIN_EPHEMERAL_SIGNAL_SEQUENCE || (value as number) > MAX_EPHEMERAL_SIGNAL_SEQUENCE) throw malformedSignal("sequence must be a positive safe integer");
  return value as number;
}

function readTimestamp(value: Record<string, unknown>, field: string): IsoTimestamp {
  const item = value[field];
  if (typeof item !== "string" || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z$/.test(item) || !isValidUtcTimestamp(item)) throw malformedSignal(`${field} must be a UTC ISO-8601 timestamp`);
  return item;
}

function isValidUtcTimestamp(value: string): boolean {
  if (!Number.isFinite(Date.parse(value))) return false;
  const year = Number(value.slice(0, 4));
  const month = Number(value.slice(5, 7));
  const day = Number(value.slice(8, 10));
  const days = [31, year % 400 === 0 || (year % 4 === 0 && year % 100 !== 0) ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][month - 1];
  return days !== undefined && day >= 1 && day <= days && Number(value.slice(11, 13)) <= 23 && Number(value.slice(14, 16)) <= 59 && Number(value.slice(17, 19)) <= 59;
}

function readEnum<const Values extends readonly string[]>(value: Record<string, unknown>, field: string, allowed: Values): Values[number] {
  const item = value[field];
  if (typeof item !== "string" || !allowed.includes(item)) throw malformedSignal(`${field} has an unsupported value`);
  return item as Values[number];
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function malformedSignal(message: string): EphemeralSignalParseError {
  return new EphemeralSignalParseError("malformed_signal", message);
}

function identityMismatch(message: string): EphemeralSignalParseError {
  return new EphemeralSignalParseError("identity_mismatch", message);
}
