// Generated by scripts/generate-forward-message.mjs from contracts/http/forward-message.json.
// Do not edit this file directly.

import type {
  ConversationId,
  IsoTimestamp,
  MessageId,
  MessageSequence,
  TenantId,
  UserId,
} from "../identifiers.js";
import type {
  ConversationMention,
  EntityMention,
  ForwardedMessageSnapshot,
  Message,
  MessageBlock,
  MessageContent,
  MessageMention,
  UserMention,
} from "../message.js";

const ISO_TIMESTAMP_PATTERN =
  /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;

const TRUSTED_IDENTITY_FIELDS = new Set([
{{TRUSTED_IDENTITY_FIELDS}}
]);
const SERVER_OWNED_FIELDS = new Set([
{{SERVER_OWNED_FIELDS}}
]);

export interface NoTrustedForwardMessageIdentity {
{{TRUSTED_IDENTITY_PROPERTIES}}
}

export interface NoClientAuthoredForwardDestination {
{{SERVER_OWNED_PROPERTIES}}
}

/** The only client-authored data accepted for a forward operation. */
export interface ForwardMessageInput
  extends NoTrustedForwardMessageIdentity,
    NoClientAuthoredForwardDestination {
  readonly operation: "{{OPERATION}}";
  readonly sourceMessageId: MessageId;
  readonly destinationConversationId: ConversationId;
  readonly clientCorrelationId: string;
  readonly idempotencyKey: string;
}

export type ForwardMessageReconciliationStatus = "applied" | "replayed";

export interface ForwardMessageResult<Block extends MessageBlock = MessageBlock> {
  readonly operation: "{{OPERATION}}";
  readonly reconciliationStatus: ForwardMessageReconciliationStatus;
  readonly clientCorrelationId: string;
  readonly destinationConversationId: ConversationId;
  readonly message: Message<Block>;
  readonly canonicalRevision: 1;
}

export type ForwardMessageErrorCode =
  | "malformed_input"
  | "trusted_identity_field"
  | "server_owned_field"
  | "malformed_result"
  | "correlation_mismatch"
  | "destination_conversation_mismatch"
  | "source_message_mismatch"
  | "noncanonical_destination"
  | "malformed_attribution"
  | "source_attachments_unsupported"
  | "source_message_not_found"
  | "source_message_forbidden"
  | "destination_conversation_not_found"
  | "destination_conversation_forbidden"
  | "idempotency_conflict";

export class ForwardMessageParseError extends Error {
  readonly code: ForwardMessageErrorCode;

  constructor(code: ForwardMessageErrorCode, message: string) {
    super(message);
    this.name = "ForwardMessageParseError";
    this.code = code;
  }
}

export function parseForwardMessageInput(value: unknown): ForwardMessageInput {
  rejectReservedFields(value);
  const input = requireRecord(value, "input", "malformed_input");
  assertAllowedKeys(
    input,
    [
      "operation",
      "sourceMessageId",
      "destinationConversationId",
      "clientCorrelationId",
      "idempotencyKey",
    ],
    "input",
    "malformed_input",
  );
  if (input.operation !== "{{OPERATION}}") {
    throw forwardError("malformed_input", "input.operation must be {{OPERATION}}");
  }
  return {
    operation: "{{OPERATION}}",
    sourceMessageId: readNonBlank(input.sourceMessageId, "input.sourceMessageId", "malformed_input") as MessageId,
    destinationConversationId: readNonBlank(
      input.destinationConversationId,
      "input.destinationConversationId",
      "malformed_input",
    ) as ConversationId,
    clientCorrelationId: readNonBlank(
      input.clientCorrelationId,
      "input.clientCorrelationId",
      "malformed_input",
    ),
    idempotencyKey: readNonBlank(input.idempotencyKey, "input.idempotencyKey", "malformed_input"),
  };
}

/**
 * Parses an authoritative result against its originating request. Requiring the
 * request makes correlation, source, and destination mismatches impossible to
 * accept accidentally during optimistic reconciliation.
 */
export function parseForwardMessageResult<Block extends MessageBlock = MessageBlock>(
  value: unknown,
  input: ForwardMessageInput,
): ForwardMessageResult<Block> {
  const result = requireRecord(value, "result", "malformed_result");
  assertAllowedKeys(
    result,
    [
      "operation",
      "reconciliationStatus",
      "clientCorrelationId",
      "destinationConversationId",
      "message",
      "canonicalRevision",
    ],
    "result",
    "malformed_result",
  );
  if (result.operation !== "{{OPERATION}}") {
    throw forwardError("malformed_result", "result.operation must be {{OPERATION}}");
  }
  const status = result.reconciliationStatus;
  if (status !== "applied" && status !== "replayed") {
    throw forwardError("malformed_result", "result.reconciliationStatus must be applied or replayed");
  }
  const correlation = readNonBlank(
    result.clientCorrelationId,
    "result.clientCorrelationId",
    "malformed_result",
  );
  if (correlation !== input.clientCorrelationId) {
    throw forwardError("correlation_mismatch", "result.clientCorrelationId must echo input.clientCorrelationId");
  }
  const destinationConversationId = readNonBlank(
    result.destinationConversationId,
    "result.destinationConversationId",
    "malformed_result",
  ) as ConversationId;
  if (destinationConversationId !== input.destinationConversationId) {
    throw forwardError(
      "destination_conversation_mismatch",
      "result.destinationConversationId must echo input.destinationConversationId",
    );
  }

  validateRawForwardedState(result.message);
  const message = parseCanonicalForwardMessage<Block>(result.message);

  if (result.canonicalRevision !== 1 || message.revision.revision !== 1) {
    throw forwardError("noncanonical_destination", "a forwarded destination must have canonical revision 1");
  }
  if (message.conversationId !== destinationConversationId) {
    throw forwardError(
      "destination_conversation_mismatch",
      "result.message.conversationId must equal the destination conversation",
    );
  }
  if (message.content === null) {
    throw forwardError("noncanonical_destination", "a forwarded destination must be active");
  }
  const snapshot = message.content.forwarded;
  if (snapshot === undefined) {
    throw forwardError("malformed_attribution", "result.message.content.forwarded is required");
  }
  if (snapshot.sourceMessageId !== input.sourceMessageId) {
    throw forwardError(
      "source_message_mismatch",
      "forwarded.sourceMessageId must equal input.sourceMessageId",
    );
  }

  return {
    operation: "{{OPERATION}}",
    reconciliationStatus: status,
    clientCorrelationId: correlation,
    destinationConversationId,
    message,
    canonicalRevision: 1,
  };
}

function parseCanonicalForwardMessage<Block extends MessageBlock>(value: unknown): Message<Block> {
  const message = requireRecord(value, "result.message", "malformed_result");
  assertAllowedKeys(
    message,
    [
      "id",
      "tenantId",
      "conversationId",
      "author",
      "sequence",
      "createdAt",
      "updatedAt",
      "revision",
      "content",
    ],
    "result.message",
    "noncanonical_destination",
  );
  const author = requireRecord(message.author, "result.message.author", "malformed_result");
  assertAllowedKeys(author, ["type", "userId"], "result.message.author", "malformed_result");
  if (author.type !== "user") {
    throw forwardError("malformed_result", "result.message.author.type must be user");
  }
  const revision = requireRecord(message.revision, "result.message.revision", "malformed_result");
  assertAllowedKeys(revision, ["revision"], "result.message.revision", "noncanonical_destination");
  if (revision.revision !== 1) {
    throw forwardError("noncanonical_destination", "result.message.revision.revision must be 1");
  }
  return {
    id: readNonBlank(message.id, "result.message.id", "malformed_result") as MessageId,
    tenantId: readNonBlank(message.tenantId, "result.message.tenantId", "malformed_result") as TenantId,
    conversationId: readNonBlank(
      message.conversationId,
      "result.message.conversationId",
      "malformed_result",
    ) as ConversationId,
    author: {
      type: "user",
      userId: readNonBlank(author.userId, "result.message.author.userId", "malformed_result") as UserId,
    },
    sequence: readPositiveInteger(message.sequence, "result.message.sequence") as MessageSequence,
    createdAt: readTimestamp(message.createdAt, "result.message.createdAt"),
    updatedAt: readTimestamp(message.updatedAt, "result.message.updatedAt"),
    revision: { revision: 1 },
    content: parseForwardedContent<Block>(message.content),
  };
}

function parseForwardedContent<Block extends MessageBlock>(value: unknown): MessageContent<Block> {
  const content = requireRecord(value, "result.message.content", "malformed_result");
  if (content.format !== "plain" && content.format !== "markdown") {
    throw forwardError("malformed_result", "result.message.content.format must be plain or markdown");
  }
  if (typeof content.text !== "string") {
    throw forwardError("malformed_result", "result.message.content.text must be a string");
  }
  const output: {
    format: "plain" | "markdown";
    text: string;
    mentions?: MessageMention[];
    forwarded: ForwardedMessageSnapshot;
  } = {
    format: content.format,
    text: content.text,
    forwarded: parseSnapshot(content.forwarded),
  };
  if (content.mentions !== undefined) {
    if (!Array.isArray(content.mentions)) {
      throw forwardError("malformed_result", "result.message.content.mentions must be an array");
    }
    output.mentions = content.mentions.map((mention, index) =>
      parseMention(mention, `result.message.content.mentions[${index}]`),
    );
  }
  return output as MessageContent<Block>;
}

function parseSnapshot(value: unknown): ForwardedMessageSnapshot {
  const path = "result.message.content.forwarded";
  const snapshot = requireRecord(value, path, "malformed_attribution");
  const author = requireRecord(snapshot.originalAuthor, `${path}.originalAuthor`, "malformed_attribution");
  const displayName = readNonBlank(
    author.displayName,
    `${path}.originalAuthor.displayName`,
    "malformed_attribution",
  );
  if (displayName.length > 256) {
    throw forwardError("malformed_attribution", `${path}.originalAuthor.displayName must be at most 256 characters`);
  }
  return {
    sourceMessageId: readNonBlank(
      snapshot.sourceMessageId,
      `${path}.sourceMessageId`,
      "malformed_attribution",
    ) as MessageId,
    originalAuthor: {
      userId: readNonBlank(
        author.userId,
        `${path}.originalAuthor.userId`,
        "malformed_attribution",
      ) as UserId,
      displayName,
    },
    originalCreatedAt: readTimestamp(
      snapshot.originalCreatedAt,
      `${path}.originalCreatedAt`,
      "malformed_attribution",
    ),
  };
}

function parseMention(value: unknown, path: string): MessageMention {
  const mention = requireRecord(value, path, "malformed_result");
  if (mention.type === "user") {
    assertAllowedKeys(mention, ["type", "userId"], path, "malformed_result");
    return {
      type: "user",
      userId: readNonBlank(mention.userId, `${path}.userId`, "malformed_result") as UserId,
    } satisfies UserMention;
  }
  if (mention.type === "conversation") {
    assertAllowedKeys(mention, ["type", "conversationId"], path, "malformed_result");
    return {
      type: "conversation",
      conversationId: readNonBlank(
        mention.conversationId,
        `${path}.conversationId`,
        "malformed_result",
      ) as ConversationId,
    } satisfies ConversationMention;
  }
  if (mention.type === "entity") {
    assertAllowedKeys(mention, ["type", "entity"], path, "malformed_result");
    const entity = requireRecord(mention.entity, `${path}.entity`, "malformed_result");
    assertAllowedKeys(entity, ["type", "id"], `${path}.entity`, "malformed_result");
    return {
      type: "entity",
      entity: {
        type: readNonBlank(entity.type, `${path}.entity.type`, "malformed_result"),
        id: readNonBlank(entity.id, `${path}.entity.id`, "malformed_result"),
      },
    } satisfies EntityMention;
  }
  throw forwardError("malformed_result", `${path}.type must be user, conversation, or entity`);
}

function validateRawForwardedState(value: unknown): void {
  const message = requireRecord(value, "result.message", "malformed_result");
  const content = requireRecord(message.content, "result.message.content", "malformed_result");
  if (Object.hasOwn(content, "attachments")) {
    throw forwardError(
      "source_attachments_unsupported",
      "forwarded destination content must not contain attachment reference state",
    );
  }
  if (Object.hasOwn(content, "blocks")) {
    throw forwardError("malformed_result", "forwarded destination content must not contain blocks");
  }
  assertAllowedKeys(
    content,
    ["format", "text", "mentions", "forwarded"],
    "result.message.content",
    "malformed_result",
  );
  const snapshot = requireRecord(
    content.forwarded,
    "result.message.content.forwarded",
    "malformed_attribution",
  );
  assertAllowedKeys(
    snapshot,
    ["sourceMessageId", "originalAuthor", "originalCreatedAt"],
    "result.message.content.forwarded",
    "malformed_attribution",
  );
  const author = requireRecord(
    snapshot.originalAuthor,
    "result.message.content.forwarded.originalAuthor",
    "malformed_attribution",
  );
  assertAllowedKeys(
    author,
    ["userId", "displayName"],
    "result.message.content.forwarded.originalAuthor",
    "malformed_attribution",
  );
}

function rejectReservedFields(value: unknown, path = "input"): void {
  if (Array.isArray(value)) {
    value.forEach((item, index) => rejectReservedFields(item, `${path}[${index}]`));
    return;
  }
  if (typeof value !== "object" || value === null) return;
  for (const [key, nested] of Object.entries(value as Record<string, unknown>)) {
    const normalized = key.replaceAll(/[^a-zA-Z0-9]/g, "").toLowerCase();
    if (TRUSTED_IDENTITY_FIELDS.has(normalized)) {
      throw forwardError("trusted_identity_field", `${path}.${key} must come from trusted server context`);
    }
    if (SERVER_OWNED_FIELDS.has(normalized)) {
      throw forwardError("server_owned_field", `${path}.${key} is server-authored`);
    }
    rejectReservedFields(nested, `${path}.${key}`);
  }
}

function requireRecord(
  value: unknown,
  path: string,
  code: ForwardMessageErrorCode,
): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw forwardError(code, `${path} must be an object`);
  }
  return value as Record<string, unknown>;
}

function assertAllowedKeys(
  value: Record<string, unknown>,
  allowed: readonly string[],
  path: string,
  code: ForwardMessageErrorCode,
): void {
  const allowedSet = new Set(allowed);
  for (const key of Object.keys(value)) {
    if (!allowedSet.has(key)) throw forwardError(code, `${path}.${key} is not supported`);
  }
}

function readNonBlank(value: unknown, path: string, code: ForwardMessageErrorCode): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw forwardError(code, `${path} must be a non-blank string`);
  }
  return value;
}

function readPositiveInteger(value: unknown, path: string): number {
  if (!Number.isSafeInteger(value) || (value as number) < 1) {
    throw forwardError("malformed_result", `${path} must be a positive safe integer`);
  }
  return value as number;
}

function readTimestamp(
  value: unknown,
  path: string,
  code: ForwardMessageErrorCode = "malformed_result",
): IsoTimestamp {
  if (
    typeof value !== "string" ||
    !ISO_TIMESTAMP_PATTERN.test(value) ||
    !Number.isFinite(Date.parse(value))
  ) {
    throw forwardError(code, `${path} must be an ISO-8601 timestamp`);
  }
  return value as IsoTimestamp;
}

function forwardError(code: ForwardMessageErrorCode, message: string): ForwardMessageParseError {
  return new ForwardMessageParseError(code, message);
}
