// Generated by scripts/generate-reactions.mjs from contracts/http/reactions.json.
// Do not edit this file directly.

import 'dart:convert';

import 'package:unorm_dart/unorm_dart.dart' as unorm;

import 'identifiers.dart';

const int maxReactionKeyUtf8Bytes = {{MAX_REACTION_KEY_UTF8_BYTES}};
const int maxReactionIdempotencyKeyUtf8Bytes = {{MAX_IDEMPOTENCY_KEY_UTF8_BYTES}};
const int _maxSafeInteger = 9007199254740991;

const _trustedIdentityFields = <String>{
{{TRUSTED_IDENTITY_FIELDS}}
};

enum ReactionMutationOperation {
  addReaction('{{ADD_OPERATION}}'),
  removeReaction('{{REMOVE_OPERATION}}');

  const ReactionMutationOperation(this.wireValue);

  final String wireValue;
  String toJson() => wireValue;
}

enum ReactionMutationReconciliationStatus {
  applied('{{APPLIED_STATUS}}'),
  replayed('{{REPLAYED_STATUS}}');

  const ReactionMutationReconciliationStatus(this.wireValue);

  factory ReactionMutationReconciliationStatus.fromJson(Object? value) =>
      switch (value) {
        '{{APPLIED_STATUS}}' => ReactionMutationReconciliationStatus.applied,
        '{{REPLAYED_STATUS}}' => ReactionMutationReconciliationStatus.replayed,
        _ => throw _error(
            ReactionMutationParseErrorCode.malformedResult,
            'result.reconciliationStatus must be {{APPLIED_STATUS}} or {{REPLAYED_STATUS}}',
          ),
      };

  final String wireValue;
  String toJson() => wireValue;
}

enum ReactionMutationParseErrorCode {
  malformedInput,
  trustedIdentityField,
  malformedReactionKey,
  malformedResult,
  incoherentResult,
}

final class ReactionMutationFormatException extends FormatException {
  const ReactionMutationFormatException(this.code, String message)
      : super(message);

  final ReactionMutationParseErrorCode code;
}

sealed class ReactionMutationInput {
  ReactionMutationInput({
    required this.messageId,
    required this.reactionKey,
    required this.idempotencyKey,
  }) {
    _nonBlank(
      messageId.value,
      'input.messageId',
      ReactionMutationParseErrorCode.malformedInput,
    );
    _reactionKey(reactionKey, 'input.reactionKey');
    _idempotencyKey(idempotencyKey);
  }

  factory ReactionMutationInput.fromJson(Object? json) {
    final object = _object(
      json,
      'input',
      ReactionMutationParseErrorCode.malformedInput,
    );
    _rejectTrustedIdentityFields(object);
    final operation = _operation(
      object['operation'],
      'input.operation',
      ReactionMutationParseErrorCode.malformedInput,
    );
    return switch (operation) {
      ReactionMutationOperation.addReaction =>
        AddReactionInput._fromObject(object),
      ReactionMutationOperation.removeReaction =>
        RemoveReactionInput._fromObject(object),
    };
  }

  ReactionMutationOperation get operation;
  final MessageId messageId;
  final String reactionKey;
  final String idempotencyKey;

  Map<String, Object?> toJson() => <String, Object?>{
        'operation': operation.toJson(),
        'messageId': messageId.toJson(),
        'reactionKey': reactionKey,
        'idempotencyKey': idempotencyKey,
      };
}

final class AddReactionInput extends ReactionMutationInput {
  AddReactionInput({
    required super.messageId,
    required super.reactionKey,
    required super.idempotencyKey,
  });

  factory AddReactionInput._fromObject(Map<String, Object?> object) {
    _exactInput(object);
    return AddReactionInput(
      messageId: MessageId(
        _nonBlank(
          object['messageId'],
          'input.messageId',
          ReactionMutationParseErrorCode.malformedInput,
        ),
      ),
      reactionKey: _reactionKey(object['reactionKey'], 'input.reactionKey'),
      idempotencyKey: _idempotencyKey(object['idempotencyKey']),
    );
  }

  @override
  ReactionMutationOperation get operation =>
      ReactionMutationOperation.addReaction;
}

final class RemoveReactionInput extends ReactionMutationInput {
  RemoveReactionInput({
    required super.messageId,
    required super.reactionKey,
    required super.idempotencyKey,
  });

  factory RemoveReactionInput._fromObject(Map<String, Object?> object) {
    _exactInput(object);
    return RemoveReactionInput(
      messageId: MessageId(
        _nonBlank(
          object['messageId'],
          'input.messageId',
          ReactionMutationParseErrorCode.malformedInput,
        ),
      ),
      reactionKey: _reactionKey(object['reactionKey'], 'input.reactionKey'),
      idempotencyKey: _idempotencyKey(object['idempotencyKey']),
    );
  }

  @override
  ReactionMutationOperation get operation =>
      ReactionMutationOperation.removeReaction;
}

sealed class ReactionMutationResult {
  ReactionMutationResult({
    required this.reconciliationStatus,
    required this.messageId,
    required this.reactionKey,
    required this.count,
  }) {
    _nonBlank(
      messageId.value,
      'result.messageId',
      ReactionMutationParseErrorCode.malformedResult,
    );
    _reactionKey(reactionKey, 'result.reactionKey');
    _nonNegativeSafeInteger(count, 'result.count');
  }

  factory ReactionMutationResult.fromJson(Object? json) {
    final object = _object(
      json,
      'result',
      ReactionMutationParseErrorCode.malformedResult,
    );
    final operation = _operation(
      object['operation'],
      'result.operation',
      ReactionMutationParseErrorCode.malformedResult,
    );
    return switch (operation) {
      ReactionMutationOperation.addReaction =>
        AddReactionResult._fromObject(object),
      ReactionMutationOperation.removeReaction =>
        RemoveReactionResult._fromObject(object),
    };
  }

  ReactionMutationOperation get operation;
  bool get reactedByCurrentUser;
  final ReactionMutationReconciliationStatus reconciliationStatus;
  final MessageId messageId;
  final String reactionKey;
  final int count;

  Map<String, Object?> toJson() => <String, Object?>{
        'operation': operation.toJson(),
        'reconciliationStatus': reconciliationStatus.toJson(),
        'messageId': messageId.toJson(),
        'reactionKey': reactionKey,
        'count': count,
        'reactedByCurrentUser': reactedByCurrentUser,
      };
}

final class AddReactionResult extends ReactionMutationResult {
  AddReactionResult({
    required super.reconciliationStatus,
    required super.messageId,
    required super.reactionKey,
    required super.count,
  }) {
    if (count == 0) {
      throw _error(
        ReactionMutationParseErrorCode.incoherentResult,
        'an added current-user reaction requires a positive aggregate count',
      );
    }
  }

  factory AddReactionResult._fromObject(Map<String, Object?> object) {
    _exactResult(object);
    if (object['reactedByCurrentUser'] != true) {
      throw _error(
        ReactionMutationParseErrorCode.incoherentResult,
        '{{ADD_OPERATION}} must report reactedByCurrentUser as true',
      );
    }
    return AddReactionResult(
      reconciliationStatus: ReactionMutationReconciliationStatus.fromJson(
        object['reconciliationStatus'],
      ),
      messageId: MessageId(
        _nonBlank(
          object['messageId'],
          'result.messageId',
          ReactionMutationParseErrorCode.malformedResult,
        ),
      ),
      reactionKey: _reactionKey(object['reactionKey'], 'result.reactionKey'),
      count: _nonNegativeSafeInteger(object['count'], 'result.count'),
    );
  }

  @override
  ReactionMutationOperation get operation =>
      ReactionMutationOperation.addReaction;

  @override
  bool get reactedByCurrentUser => true;
}

final class RemoveReactionResult extends ReactionMutationResult {
  RemoveReactionResult({
    required super.reconciliationStatus,
    required super.messageId,
    required super.reactionKey,
    required super.count,
  });

  factory RemoveReactionResult._fromObject(Map<String, Object?> object) {
    _exactResult(object);
    if (object['reactedByCurrentUser'] != false) {
      throw _error(
        ReactionMutationParseErrorCode.incoherentResult,
        '{{REMOVE_OPERATION}} must report reactedByCurrentUser as false',
      );
    }
    return RemoveReactionResult(
      reconciliationStatus: ReactionMutationReconciliationStatus.fromJson(
        object['reconciliationStatus'],
      ),
      messageId: MessageId(
        _nonBlank(
          object['messageId'],
          'result.messageId',
          ReactionMutationParseErrorCode.malformedResult,
        ),
      ),
      reactionKey: _reactionKey(object['reactionKey'], 'result.reactionKey'),
      count: _nonNegativeSafeInteger(object['count'], 'result.count'),
    );
  }

  @override
  ReactionMutationOperation get operation =>
      ReactionMutationOperation.removeReaction;

  @override
  bool get reactedByCurrentUser => false;
}

void _exactInput(Map<String, Object?> object) {
  _exact(
    object,
    const {
{{DART_INPUT_KEYS}}
    },
    'input',
    ReactionMutationParseErrorCode.malformedInput,
  );
}

void _exactResult(Map<String, Object?> object) {
  _exact(
    object,
    const {
{{DART_RESULT_KEYS}}
    },
    'result',
    ReactionMutationParseErrorCode.malformedResult,
  );
}

ReactionMutationOperation _operation(
  Object? value,
  String path,
  ReactionMutationParseErrorCode code,
) =>
    switch (value) {
      '{{ADD_OPERATION}}' => ReactionMutationOperation.addReaction,
      '{{REMOVE_OPERATION}}' => ReactionMutationOperation.removeReaction,
      _ => throw _error(
          code,
          '$path must be {{ADD_OPERATION}} or {{REMOVE_OPERATION}}; toggle semantics are not supported',
        ),
    };

void _rejectTrustedIdentityFields(Map<String, Object?> input) {
  for (final key in input.keys) {
    final normalized = key.replaceAll(RegExp('[^a-zA-Z0-9]'), '').toLowerCase();
    if (_trustedIdentityFields.contains(normalized)) {
      throw _error(
        ReactionMutationParseErrorCode.trustedIdentityField,
        'input.$key is server-derived and cannot be supplied by a client',
      );
    }
  }
}

Map<String, Object?> _object(
  Object? value,
  String path,
  ReactionMutationParseErrorCode code,
) {
  if (value is! Map<String, Object?>) {
    throw _error(code, '$path must be a JSON object');
  }
  return value;
}

void _exact(
  Map<String, Object?> object,
  Set<String> expected,
  String path,
  ReactionMutationParseErrorCode code,
) {
  for (final key in object.keys) {
    if (!expected.contains(key)) {
      throw _error(code, '$path.$key is not allowed');
    }
  }
  for (final key in expected) {
    if (!object.containsKey(key)) {
      throw _error(code, '$path.$key is required');
    }
  }
}

String _nonBlank(
  Object? value,
  String path,
  ReactionMutationParseErrorCode code,
) {
  if (value is! String || value.trim().isEmpty) {
    throw _error(code, '$path must be a non-empty string');
  }
  return value;
}

String _reactionKey(Object? value, String path) {
  if (value is! String || value.isEmpty) {
    throw _error(
      ReactionMutationParseErrorCode.malformedReactionKey,
      '$path must be a non-empty string',
    );
  }
  if (value.trim() != value) {
    throw _error(
      ReactionMutationParseErrorCode.malformedReactionKey,
      '$path cannot have leading or trailing whitespace',
    );
  }
  if (unorm.nfc(value) != value) {
    throw _error(
      ReactionMutationParseErrorCode.malformedReactionKey,
      '$path must be NFC-normalized',
    );
  }
  if (utf8.encode(value).length > maxReactionKeyUtf8Bytes) {
    throw _error(
      ReactionMutationParseErrorCode.malformedReactionKey,
      '$path cannot exceed $maxReactionKeyUtf8Bytes UTF-8 bytes',
    );
  }
  return value;
}

String _idempotencyKey(Object? value) {
  final key = _nonBlank(
    value,
    'input.idempotencyKey',
    ReactionMutationParseErrorCode.malformedInput,
  );
  if (utf8.encode(key).length > maxReactionIdempotencyKeyUtf8Bytes) {
    throw _error(
      ReactionMutationParseErrorCode.malformedInput,
      'input.idempotencyKey cannot exceed '
      '$maxReactionIdempotencyKeyUtf8Bytes UTF-8 bytes',
    );
  }
  return key;
}

int _nonNegativeSafeInteger(Object? value, String path) {
  if (value is! int || value < 0 || value > _maxSafeInteger) {
    throw _error(
      ReactionMutationParseErrorCode.malformedResult,
      '$path must be a nonnegative safe integer',
    );
  }
  return value;
}

ReactionMutationFormatException _error(
  ReactionMutationParseErrorCode code,
  String message,
) =>
    ReactionMutationFormatException(code, message);
