// Generated by scripts/generate-reactions.mjs from contracts/http/reactions.json.
// Do not edit this file directly.

import type { MessageId } from "./identifiers.js";
import type { UntrustedChatMutationInput } from "../server/contracts.js";

/** Matches the persisted `chat_reactions.reaction_key` UTF-8 byte bound. */
export const MAX_REACTION_KEY_UTF8_BYTES = {{MAX_REACTION_KEY_UTF8_BYTES}};

/** Matches the persisted `chat_idempotency_keys.client_key` UTF-8 byte bound. */
export const MAX_REACTION_IDEMPOTENCY_KEY_UTF8_BYTES = {{MAX_IDEMPOTENCY_KEY_UTF8_BYTES}};

type ReactionMutationInputBase<Operation extends string> =
  UntrustedChatMutationInput<{
    readonly operation: Operation;
    readonly messageId: MessageId;
    readonly reactionKey: string;
    readonly idempotencyKey: string;
  }>;

/** Deterministic intent to ensure the current user's reaction is present. */
export type AddReactionInput = ReactionMutationInputBase<"{{ADD_OPERATION}}">;

/** Deterministic intent to ensure the current user's reaction is absent. */
export type RemoveReactionInput =
  ReactionMutationInputBase<"{{REMOVE_OPERATION}}">;

/**
 * A retry-safe reaction mutation. There is deliberately no toggle operation:
 * replaying either member of this union cannot reverse its requested state.
 */
export type ReactionMutationInput = AddReactionInput | RemoveReactionInput;

export type ReactionMutationReconciliationStatus =
  | "{{APPLIED_STATUS}}"
  | "{{REPLAYED_STATUS}}";

interface ReactionMutationResultBase<Operation extends string> {
  readonly operation: Operation;
  readonly reconciliationStatus: ReactionMutationReconciliationStatus;
  readonly messageId: MessageId;
  readonly reactionKey: string;
  /** Canonical aggregate across all users for this message and reaction key. */
  readonly count: number;
}

export interface AddReactionResult
  extends ReactionMutationResultBase<"{{ADD_OPERATION}}"> {
  readonly reactedByCurrentUser: true;
}

export interface RemoveReactionResult
  extends ReactionMutationResultBase<"{{REMOVE_OPERATION}}"> {
  readonly reactedByCurrentUser: false;
}

export type ReactionMutationResult = AddReactionResult | RemoveReactionResult;

export type ReactionMutationParseErrorCode =
  | "malformed_input"
  | "trusted_identity_field"
  | "malformed_reaction_key"
  | "malformed_result"
  | "incoherent_result";

export class ReactionMutationParseError extends Error {
  readonly code: ReactionMutationParseErrorCode;

  constructor(code: ReactionMutationParseErrorCode, message: string) {
    super(message);
    this.name = "ReactionMutationParseError";
    this.code = code;
  }
}

const TRUSTED_IDENTITY_FIELDS = new Set([
{{TRUSTED_IDENTITY_FIELDS}}
]);

const INPUT_KEYS = [
{{INPUT_KEYS}}
] as const;

const RESULT_KEYS = [
{{RESULT_KEYS}}
] as const;

export function parseAddReactionInput(value: unknown): AddReactionInput {
  return parseInput(value, "{{ADD_OPERATION}}");
}

export function parseRemoveReactionInput(value: unknown): RemoveReactionInput {
  return parseInput(value, "{{REMOVE_OPERATION}}");
}

export function parseReactionMutationInput(
  value: unknown,
): ReactionMutationInput {
  const input = requireRecord(value, "input", "malformed_input");
  rejectTrustedIdentityFields(input);

  if (input.operation === "{{ADD_OPERATION}}") {
    return parseInputRecord(input, "{{ADD_OPERATION}}");
  }
  if (input.operation === "{{REMOVE_OPERATION}}") {
    return parseInputRecord(input, "{{REMOVE_OPERATION}}");
  }
  throw reactionError(
    "malformed_input",
    "operation must be {{ADD_OPERATION}} or {{REMOVE_OPERATION}}; toggle semantics are not supported",
  );
}

export function parseAddReactionResult(value: unknown): AddReactionResult {
  return parseResult(value, "{{ADD_OPERATION}}");
}

export function parseRemoveReactionResult(value: unknown): RemoveReactionResult {
  return parseResult(value, "{{REMOVE_OPERATION}}");
}

export function parseReactionMutationResult(
  value: unknown,
): ReactionMutationResult {
  const result = requireRecord(value, "result", "malformed_result");

  if (result.operation === "{{ADD_OPERATION}}") {
    return parseResultRecord(result, "{{ADD_OPERATION}}");
  }
  if (result.operation === "{{REMOVE_OPERATION}}") {
    return parseResultRecord(result, "{{REMOVE_OPERATION}}");
  }
  throw reactionError(
    "malformed_result",
    "result.operation must be {{ADD_OPERATION}} or {{REMOVE_OPERATION}}",
  );
}

function parseInput<
  Operation extends "{{ADD_OPERATION}}" | "{{REMOVE_OPERATION}}",
>(
  value: unknown,
  operation: Operation,
): Operation extends "{{ADD_OPERATION}}"
  ? AddReactionInput
  : RemoveReactionInput {
  const input = requireRecord(value, "input", "malformed_input");
  rejectTrustedIdentityFields(input);
  return parseInputRecord(input, operation);
}

function parseInputRecord<
  Operation extends "{{ADD_OPERATION}}" | "{{REMOVE_OPERATION}}",
>(
  input: Record<string, unknown>,
  operation: Operation,
): Operation extends "{{ADD_OPERATION}}"
  ? AddReactionInput
  : RemoveReactionInput {
  assertAllowedKeys(input, INPUT_KEYS, "input", "malformed_input");
  if (input.operation !== operation) {
    throw reactionError("malformed_input", `operation must be ${operation}`);
  }

  return {
    operation,
    messageId: readNonEmptyString(
      input,
      "messageId",
      "malformed_input",
    ) as MessageId,
    reactionKey: parseReactionKey(input.reactionKey, "input.reactionKey"),
    idempotencyKey: parseIdempotencyKey(input.idempotencyKey),
  } as Operation extends "{{ADD_OPERATION}}"
    ? AddReactionInput
    : RemoveReactionInput;
}

function parseResult<
  Operation extends "{{ADD_OPERATION}}" | "{{REMOVE_OPERATION}}",
>(
  value: unknown,
  operation: Operation,
): Operation extends "{{ADD_OPERATION}}"
  ? AddReactionResult
  : RemoveReactionResult {
  const result = requireRecord(value, "result", "malformed_result");
  return parseResultRecord(result, operation);
}

function parseResultRecord<
  Operation extends "{{ADD_OPERATION}}" | "{{REMOVE_OPERATION}}",
>(
  result: Record<string, unknown>,
  operation: Operation,
): Operation extends "{{ADD_OPERATION}}"
  ? AddReactionResult
  : RemoveReactionResult {
  assertAllowedKeys(result, RESULT_KEYS, "result", "malformed_result");
  if (result.operation !== operation) {
    throw reactionError(
      "malformed_result",
      `result.operation must be ${operation}`,
    );
  }
  if (
    result.reconciliationStatus !== "{{APPLIED_STATUS}}" &&
    result.reconciliationStatus !== "{{REPLAYED_STATUS}}"
  ) {
    throw reactionError(
      "malformed_result",
      "result.reconciliationStatus must be {{APPLIED_STATUS}} or {{REPLAYED_STATUS}}",
    );
  }

  const count = readNonNegativeSafeInteger(result.count, "result.count");
  const expectedCurrentUserState = operation === "{{ADD_OPERATION}}";
  if (result.reactedByCurrentUser !== expectedCurrentUserState) {
    throw reactionError(
      "incoherent_result",
      `${operation} must report reactedByCurrentUser as ${expectedCurrentUserState}`,
    );
  }
  if (expectedCurrentUserState && count === 0) {
    throw reactionError(
      "incoherent_result",
      "an added current-user reaction requires a positive aggregate count",
    );
  }

  return {
    operation,
    reconciliationStatus: result.reconciliationStatus,
    messageId: readNonEmptyString(
      result,
      "messageId",
      "malformed_result",
    ) as MessageId,
    reactionKey: parseReactionKey(result.reactionKey, "result.reactionKey"),
    count,
    reactedByCurrentUser: expectedCurrentUserState,
  } as Operation extends "{{ADD_OPERATION}}"
    ? AddReactionResult
    : RemoveReactionResult;
}

function parseReactionKey(value: unknown, path: string): string {
  if (typeof value !== "string" || value.length === 0) {
    throw reactionError(
      "malformed_reaction_key",
      `${path} must be a non-empty string`,
    );
  }
  if (/^\s|\s$/u.test(value)) {
    throw reactionError(
      "malformed_reaction_key",
      `${path} cannot have leading or trailing whitespace`,
    );
  }
  if (value !== value.normalize("NFC")) {
    throw reactionError(
      "malformed_reaction_key",
      `${path} must be NFC-normalized`,
    );
  }
  if (utf8ByteLength(value) > MAX_REACTION_KEY_UTF8_BYTES) {
    throw reactionError(
      "malformed_reaction_key",
      `${path} cannot exceed ${MAX_REACTION_KEY_UTF8_BYTES} UTF-8 bytes`,
    );
  }
  return value;
}

function parseIdempotencyKey(value: unknown): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw reactionError(
      "malformed_input",
      "input.idempotencyKey must be a non-empty string",
    );
  }
  if (utf8ByteLength(value) > MAX_REACTION_IDEMPOTENCY_KEY_UTF8_BYTES) {
    throw reactionError(
      "malformed_input",
      `input.idempotencyKey cannot exceed ${MAX_REACTION_IDEMPOTENCY_KEY_UTF8_BYTES} UTF-8 bytes`,
    );
  }
  return value;
}

function rejectTrustedIdentityFields(input: Record<string, unknown>): void {
  for (const key of Object.keys(input)) {
    const normalizedKey = key.replaceAll(/[^a-zA-Z0-9]/g, "").toLowerCase();
    if (TRUSTED_IDENTITY_FIELDS.has(normalizedKey)) {
      throw reactionError(
        "trusted_identity_field",
        `input.${key} is server-derived and cannot be supplied by a client`,
      );
    }
  }
}

function requireRecord(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw reactionError(code, `${path} must be an object`);
  }
  return value as Record<string, unknown>;
}

function assertAllowedKeys(
  value: Record<string, unknown>,
  allowedKeys: readonly string[],
  path: string,
  code: "malformed_input" | "malformed_result",
): void {
  const allowed = new Set(allowedKeys);
  for (const key of Object.keys(value)) {
    if (!allowed.has(key)) {
      throw reactionError(code, `${path}.${key} is not allowed`);
    }
  }
}

function readNonEmptyString(
  value: Record<string, unknown>,
  key: string,
  code: "malformed_input" | "malformed_result",
): string {
  const field = value[key];
  if (typeof field !== "string" || field.trim().length === 0) {
    throw reactionError(code, `${key} must be a non-empty string`);
  }
  return field;
}

function readNonNegativeSafeInteger(value: unknown, path: string): number {
  if (!Number.isSafeInteger(value) || (value as number) < 0) {
    throw reactionError(
      "malformed_result",
      `${path} must be a nonnegative safe integer`,
    );
  }
  return value as number;
}

function utf8ByteLength(value: string): number {
  return new TextEncoder().encode(value).byteLength;
}

function reactionError(
  code: ReactionMutationParseErrorCode,
  message: string,
): ReactionMutationParseError {
  return new ReactionMutationParseError(code, message);
}
