// Generated by scripts/generate-thread-lifecycle.mjs from contracts/http/thread-lifecycle.json.
// Do not edit. Descriptor SHA-256: {{HASH}}
import { validateThreadLifecycle, type ThreadLifecycle } from './conversation.js';
import type { ConversationId } from './identifiers.js';

/** Reserved contract gate; this constant does not advertise runtime support. */
export const THREAD_LIFECYCLE_FEATURE = '{{FEATURE}}';
export const THREAD_LIFECYCLE_PATH = '{{PATH}}';
const intents = [{{INTENTS}}] as const;
const statuses = [{{STATUSES}}] as const;
export type ThreadLifecycleIntent = typeof intents[number];
export type ThreadLifecycleReconciliationStatus = typeof statuses[number];
export interface ThreadLifecycleInput {
  readonly operation: '{{OPERATION}}';
  readonly intent: ThreadLifecycleIntent;
  readonly threadId: ConversationId;
  readonly expectedLifecycleRevision: number;
  readonly idempotencyKey: string;
}
export interface ThreadLifecycleResult extends ThreadLifecycleInput {
  readonly reconciliationStatus: ThreadLifecycleReconciliationStatus;
  /** Canonical snapshot immediately before the original evaluation. */
  readonly previousLifecycle: ThreadLifecycle;
  /** Original committed/evaluated snapshot; a replay may be older than local state. */
  readonly threadLifecycle: ThreadLifecycle;
}
export type ThreadLifecycleParseErrorCode = 'malformed_input' | 'trusted_identity_field' | 'malformed_result' | 'incoherent_result';
export class ThreadLifecycleParseError extends TypeError {
  constructor(readonly code: ThreadLifecycleParseErrorCode, message: string) {
    super(message);
    this.name = 'ThreadLifecycleParseError';
  }
}
const inputKeys = [{{INPUT_KEYS}}];
const resultKeys = [{{RESULT_KEYS}}];
const trusted = new Set([{{TRUSTED}}]);
const transitions = {{TS_TRANSITIONS}} as const;
type State = keyof typeof transitions;
function state(value: ThreadLifecycle): State {
  return value.locked ? 'locked' : value.closedAt !== undefined ? 'closed' : 'open';
}
function fail(code: ThreadLifecycleParseErrorCode, message: string): never {
  throw new ThreadLifecycleParseError(code, message);
}
function object(value: unknown, keys: readonly string[], code: ThreadLifecycleParseErrorCode): Record<string, unknown> {
  if (!value || typeof value !== 'object' || Array.isArray(value)) fail(code, 'Expected a JSON object');
  const result = value as Record<string, unknown>;
  if (Object.keys(result).length !== keys.length || keys.some(key => !Object.hasOwn(result, key))) {
    fail(code, 'Missing or unknown fields');
  }
  return result;
}
function nonblank(value: unknown, code: ThreadLifecycleParseErrorCode): string {
  if (typeof value !== 'string' || !value.trim()) fail(code, 'Expected a nonblank string');
  return value;
}
function revision(value: unknown, code: ThreadLifecycleParseErrorCode): number {
  if (typeof value !== 'number' || !Number.isSafeInteger(value) || value < 1 || value > {{MAX_REVISION}}) {
    fail(code, 'Expected a positive safe integer revision');
  }
  return value;
}
function rejectTrusted(value: unknown): void {
  if (!value || typeof value !== 'object') return;
  for (const [key, child] of Object.entries(value)) {
    if (trusted.has(key.replaceAll(/[^a-zA-Z0-9]/g, '').toLowerCase())) {
      fail('trusted_identity_field', key + ' is server-derived');
    }
    rejectTrusted(child);
  }
}
function correlation(value: Record<string, unknown>, code: ThreadLifecycleParseErrorCode): ThreadLifecycleInput {
  if (value.operation !== '{{OPERATION}}' || !intents.includes(value.intent as ThreadLifecycleIntent)) {
    fail(code, 'Unsupported operation or explicit intent');
  }
  return {
    operation: '{{OPERATION}}', intent: value.intent as ThreadLifecycleIntent,
    threadId: nonblank(value.threadId, code) as ConversationId,
    expectedLifecycleRevision: revision(value.expectedLifecycleRevision, code),
    idempotencyKey: nonblank(value.idempotencyKey, code),
  };
}
export function parseThreadLifecycleInput(value: unknown): ThreadLifecycleInput {
  rejectTrusted(value);
  return correlation(object(value, inputKeys, 'malformed_input'), 'malformed_input');
}
export function serializeThreadLifecycleInput(value: ThreadLifecycleInput): ThreadLifecycleInput {
  return parseThreadLifecycleInput(value);
}
/** Normalize the path/body boundary without registering a route. */
export function parseThreadLifecycleHttpInput(threadId: unknown, body: unknown): ThreadLifecycleInput {
  rejectTrusted(body);
  const parsed = object(body, inputKeys.filter(key => key !== 'threadId'), 'malformed_input');
  return parseThreadLifecycleInput({ ...parsed, threadId });
}
export function serializeThreadLifecycleBody(value: ThreadLifecycleInput): Omit<ThreadLifecycleInput, 'threadId'> {
  const { threadId: _threadId, ...body } = parseThreadLifecycleInput(value);
  return body;
}
function lifecycle(value: unknown): ThreadLifecycle {
  try { return validateThreadLifecycle(value); }
  catch (error) { return fail('malformed_result', String(error)); }
}
function same(a: ThreadLifecycle, b: ThreadLifecycle): boolean {
  return a.revision === b.revision && a.locked === b.locked &&
    a.closedAt === b.closedAt && a.closedByUserId === b.closedByUserId;
}
function coherence(result: ThreadLifecycleResult): void {
  const { previousLifecycle: before, threadLifecycle: after, intent, reconciliationStatus: status, expectedLifecycleRevision: expected } = result;
  const target = transitions[state(before)][intent];
  const conflict = before.revision !== expected || target === null;
  if (status === 'lifecycle_conflict') {
    if (!conflict || !same(before, after)) fail('incoherent_result', 'Conflict requires revision mismatch or locked reopen, with unchanged state');
    return;
  }
  if (conflict) fail('incoherent_result', 'Settled result requires matching revision and an eligible transition');
  if (status === 'already_requested_state') {
    if (target !== state(before) || !same(before, after)) fail('incoherent_result', 'No-op must already satisfy intent and preserve state/revision');
    return;
  }
  if (target === state(before) || state(after) !== target || expected === {{MAX_REVISION}} || after.revision !== expected + 1) {
    fail('incoherent_result', 'Applied/replayed must change state exactly once without overflow');
  }
  if (before.closedAt !== undefined && after.closedAt !== undefined &&
      (before.closedAt !== after.closedAt || before.closedByUserId !== after.closedByUserId)) {
    fail('incoherent_result', 'Close/lock/unlock must retain existing closure metadata');
  }
}
export function parseThreadLifecycleResult(value: unknown, expectedInput: ThreadLifecycleInput): ThreadLifecycleResult {
  const expected = parseThreadLifecycleInput(expectedInput);
  const raw = object(value, resultKeys, 'malformed_result');
  const echo = correlation(raw, 'malformed_result');
  if (inputKeys.some(key => raw[key] !== expected[key as keyof ThreadLifecycleInput])) {
    fail('incoherent_result', 'All request correlation fields must match');
  }
  if (!statuses.includes(raw.reconciliationStatus as ThreadLifecycleReconciliationStatus)) {
    fail('malformed_result', 'Unsupported reconciliation status');
  }
  const result: ThreadLifecycleResult = {
    ...echo, reconciliationStatus: raw.reconciliationStatus as ThreadLifecycleReconciliationStatus,
    previousLifecycle: lifecycle(raw.previousLifecycle), threadLifecycle: lifecycle(raw.threadLifecycle),
  };
  coherence(result);
  return result;
}
export function serializeThreadLifecycleResult(value: ThreadLifecycleResult, expectedInput: ThreadLifecycleInput): ThreadLifecycleResult {
  return parseThreadLifecycleResult(value, expectedInput);
}
