// Generated by scripts/generate-thread.mjs from contracts/http/thread.json.
// Do not edit this file directly.

import { validateThreadConversationName } from "./conversation.js";
import {
  parseConversationDetailSnapshot,
  type ConversationDetailSnapshot,
  type ConversationDetailSnapshotConversation,
} from "./conversation-snapshot.js";
import type {
  ConversationId,
  IsoTimestamp,
  MessageId,
  UserId,
} from "./identifiers.js";
import type { ThreadSummary } from "./message.js";

const ISO_TIMESTAMP_PATTERN =
  /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;

const TRUSTED_IDENTITY_FIELDS = new Set([
{{TRUSTED_IDENTITY_FIELDS}}
]);

const INPUT_KEYS = [
{{INPUT_KEYS}}
] as const;

const RESULT_KEYS = [
{{RESULT_KEYS}}
] as const;

/** Compile-time guard for identity and authorization derived from the host session. */
export interface NoTrustedThreadCreationIdentity {
{{TRUSTED_IDENTITY_PROPERTIES}}
}

/** Caller-authored command for resolving one root message to one thread stream. */
export interface ThreadCreationInput extends NoTrustedThreadCreationIdentity {
  readonly operation: "{{OPERATION}}";
  readonly parentConversationId: ConversationId;
  readonly rootMessageId: MessageId;
  /** Optional canonical name; omitted for legacy requests. Never renames an existing thread. */
  readonly name?: string;
  /** Optional initial follow choice; omission leaves the decision to server policy. */
  readonly initialFollow?: boolean;
  readonly idempotencyKey: string;
}

export type ThreadCreationReconciliationStatus =
  /** This request persisted the thread conversation. */
  | "{{CREATED_STATUS}}"
  /** The root already resolved to the returned thread conversation. */
  | "{{EXISTING_STATUS}}"
  /** The idempotency key replayed its previously authoritative result. */
  | "{{REPLAYED_STATUS}}";

export type ThreadCreationDetailSnapshot = Omit<
  ConversationDetailSnapshot,
  "conversation"
> & {
  readonly conversation: Extract<
    ConversationDetailSnapshotConversation,
    { readonly type: "thread" }
  >;
};

/** Canonical state returned for every thread-root reconciliation outcome. */
export interface ThreadCreationResult {
  readonly operation: "{{OPERATION}}";
  readonly reconciliationStatus: ThreadCreationReconciliationStatus;
  readonly parentConversationId: ConversationId;
  readonly rootMessageId: MessageId;
  readonly conversation: ThreadCreationDetailSnapshot;
  readonly rootThreadSummary: ThreadSummary;
}

export type ThreadCreationParseErrorCode =
  | "malformed_input"
  | "trusted_identity_field"
  | "malformed_result"
  | "incoherent_result";

export class ThreadCreationParseError extends Error {
  readonly code: ThreadCreationParseErrorCode;

  constructor(code: ThreadCreationParseErrorCode, message: string) {
    super(message);
    this.name = "ThreadCreationParseError";
    this.code = code;
  }
}

export function parseThreadCreationInput(value: unknown): ThreadCreationInput {
  rejectTrustedIdentityFields(value);
  const input = requireRecord(value, "input", "malformed_input");
  assertAllowedKeys(input, INPUT_KEYS, "input", "malformed_input");

  if (input.operation !== "{{OPERATION}}") {
    throw threadCreationError(
      "malformed_input",
      "input.operation must be {{OPERATION}}",
    );
  }
  if (
    input.initialFollow !== undefined &&
    typeof input.initialFollow !== "boolean"
  ) {
    throw threadCreationError(
      "malformed_input",
      "input.initialFollow must be a boolean when provided",
    );
  }

  return {
    operation: "{{OPERATION}}",
    parentConversationId: readNonBlankString(
      input.parentConversationId,
      "input.parentConversationId",
      "malformed_input",
    ) as ConversationId,
    rootMessageId: readNonBlankString(
      input.rootMessageId,
      "input.rootMessageId",
      "malformed_input",
    ) as MessageId,
    ...(input.name === undefined ? {} : { name: readThreadName(input.name) }),
    ...(input.initialFollow === undefined
      ? {}
      : { initialFollow: input.initialFollow }),
    idempotencyKey: readNonBlankString(
      input.idempotencyKey,
      "input.idempotencyKey",
      "malformed_input",
    ),
  };
}

/** Parses and reconciles an authoritative result against its caller request. */
export function parseThreadCreationResult(
  value: unknown,
  expectedInput: ThreadCreationInput,
): ThreadCreationResult {
  const request = parseThreadCreationInput(expectedInput);
  const result = requireRecord(value, "result", "malformed_result");
  assertAllowedKeys(result, RESULT_KEYS, "result", "malformed_result");

  if (result.operation !== "{{OPERATION}}") {
    throw threadCreationError(
      "malformed_result",
      "result.operation must be {{OPERATION}}",
    );
  }

  const reconciliationStatus = readReconciliationStatus(
    result.reconciliationStatus,
  );
  const parentConversationId = readNonBlankString(
    result.parentConversationId,
    "result.parentConversationId",
    "malformed_result",
  ) as ConversationId;
  const rootMessageId = readNonBlankString(
    result.rootMessageId,
    "result.rootMessageId",
    "malformed_result",
  ) as MessageId;

  let conversation: ConversationDetailSnapshot;
  try {
    conversation = parseConversationDetailSnapshot(result.conversation);
  } catch (error) {
    throw threadCreationError(
      "malformed_result",
      `result.conversation must be a valid conversation detail snapshot${
        error instanceof Error ? `: ${error.message}` : ""
      }`,
    );
  }
  if (conversation.conversation.type !== "thread") {
    throw threadCreationError(
      "incoherent_result",
      "result.conversation must describe a thread conversation",
    );
  }

  const rootThreadSummary = parseThreadSummary(result.rootThreadSummary);
  const thread = conversation.conversation;
  if (
    parentConversationId !== request.parentConversationId ||
    rootMessageId !== request.rootMessageId
  ) {
    throw threadCreationError(
      "incoherent_result",
      "result parentConversationId and rootMessageId must match the request",
    );
  }
  if (
    thread.parentConversationId !== parentConversationId ||
    thread.rootMessageId !== rootMessageId
  ) {
    throw threadCreationError(
      "incoherent_result",
      "result root identifiers must match the returned thread conversation",
    );
  }
  if (rootThreadSummary.threadId !== thread.id) {
    throw threadCreationError(
      "incoherent_result",
      "result.rootThreadSummary.threadId must identify the returned thread conversation",
    );
  }

  return {
    operation: "{{OPERATION}}",
    reconciliationStatus,
    parentConversationId,
    rootMessageId,
    conversation: conversation as ThreadCreationDetailSnapshot,
    rootThreadSummary,
  };
}

function parseThreadSummary(value: unknown): ThreadSummary {
  const summary = requireRecord(
    value,
    "result.rootThreadSummary",
    "malformed_result",
  );
  assertAllowedKeys(
    summary,
    ["threadId", "replyCount", "participantIds", "unreadCount", "lastReplyAt"],
    "result.rootThreadSummary",
    "malformed_result",
  );
  if (!Array.isArray(summary.participantIds)) {
    throw threadCreationError(
      "malformed_result",
      "result.rootThreadSummary.participantIds must be an array",
    );
  }
  const participantIds = summary.participantIds.map((participantId, index) =>
    readNonBlankString(
      participantId,
      `result.rootThreadSummary.participantIds[${index}]`,
      "malformed_result",
    ) as UserId,
  );

  const parsed: {
    threadId: ConversationId;
    replyCount: number;
    participantIds: UserId[];
    unreadCount: number;
    lastReplyAt?: IsoTimestamp;
  } = {
    threadId: readNonBlankString(
      summary.threadId,
      "result.rootThreadSummary.threadId",
      "malformed_result",
    ) as ConversationId,
    replyCount: readNonNegativeSafeInteger(
      summary.replyCount,
      "result.rootThreadSummary.replyCount",
    ),
    participantIds,
    unreadCount: readNonNegativeSafeInteger(
      summary.unreadCount,
      "result.rootThreadSummary.unreadCount",
    ),
  };
  if (summary.lastReplyAt !== undefined) {
    parsed.lastReplyAt = readIsoTimestamp(
      summary.lastReplyAt,
      "result.rootThreadSummary.lastReplyAt",
    );
  }
  return parsed;
}

function readReconciliationStatus(
  value: unknown,
): ThreadCreationReconciliationStatus {
  if (
    value !== "{{CREATED_STATUS}}" &&
    value !== "{{EXISTING_STATUS}}" &&
    value !== "{{REPLAYED_STATUS}}"
  ) {
    throw threadCreationError(
      "malformed_result",
      "result.reconciliationStatus must be {{CREATED_STATUS}}, {{EXISTING_STATUS}}, or {{REPLAYED_STATUS}}",
    );
  }
  return value;
}

function rejectTrustedIdentityFields(value: unknown, path = "input"): void {
  if (Array.isArray(value)) {
    value.forEach((entry, index) =>
      rejectTrustedIdentityFields(entry, `${path}[${index}]`),
    );
    return;
  }
  if (!isRecord(value)) return;

  for (const [key, nested] of Object.entries(value)) {
    const normalizedKey = key.replaceAll(/[^a-zA-Z0-9]/g, "").toLowerCase();
    if (TRUSTED_IDENTITY_FIELDS.has(normalizedKey)) {
      throw threadCreationError(
        "trusted_identity_field",
        `${path}.${key} is server-derived and cannot be supplied by a client`,
      );
    }
    rejectTrustedIdentityFields(nested, `${path}.${key}`);
  }
}

function assertAllowedKeys(
  value: Record<string, unknown>,
  allowed: readonly string[],
  path: string,
  code: "malformed_input" | "malformed_result",
): void {
  const allowedSet = new Set(allowed);
  for (const key of Object.keys(value)) {
    if (!allowedSet.has(key)) {
      throw threadCreationError(code, `${path}.${key} is not supported`);
    }
  }
}

function requireRecord(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): Record<string, unknown> {
  if (!isRecord(value)) {
    throw threadCreationError(code, `${path} must be an object`);
  }
  return value;
}

function readThreadName(value: unknown): string {
  try {
    return validateThreadConversationName(value);
  } catch (error) {
    throw threadCreationError(
      "malformed_input",
      `input.name must be a valid canonical thread name${
        error instanceof Error ? `: ${error.message}` : ""
      }`,
    );
  }
}

function readNonBlankString(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw threadCreationError(code, `${path} must be a nonblank string`);
  }
  return value;
}

function readNonNegativeSafeInteger(value: unknown, path: string): number {
  if (!Number.isSafeInteger(value) || (value as number) < 0) {
    throw threadCreationError(
      "malformed_result",
      `${path} must be a non-negative safe integer`,
    );
  }
  return value as number;
}

function readIsoTimestamp(value: unknown, path: string): IsoTimestamp {
  if (
    typeof value !== "string" ||
    !ISO_TIMESTAMP_PATTERN.test(value) ||
    !Number.isFinite(Date.parse(value))
  ) {
    throw threadCreationError(
      "malformed_result",
      `${path} must be an ISO-8601 timestamp`,
    );
  }
  return value;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function threadCreationError(
  code: ThreadCreationParseErrorCode,
  message: string,
): ThreadCreationParseError {
  return new ThreadCreationParseError(code, message);
}
