// Generated by scripts/generate-thread-lifecycle.mjs from contracts/http/thread-lifecycle.json.
// Do not edit. Descriptor SHA-256: {{HASH}}
import 'conversation.dart';
import 'identifiers.dart';

/// Reserved contract gate; does not advertise runtime support.
const threadLifecycleFeature = '{{FEATURE}}';
const threadLifecyclePath = '{{PATH}}';
const _intents = [{{INTENTS}}];
const _statuses = [{{STATUSES}}];
const _inputKeys = [{{INPUT_KEYS}}];
const _resultKeys = [{{RESULT_KEYS}}];
const _trusted = { {{TRUSTED}} };
const _transitions = {{DART_TRANSITIONS}};

enum ThreadLifecycleIntent {
  close, reopen, lock, unlock;
  String toJson() => name;
  static ThreadLifecycleIntent fromJson(Object? value) {
    if (!_intents.contains(value)) _fail('malformed_input', 'Unsupported explicit intent');
    return values.byName(value as String);
  }
}
enum ThreadLifecycleReconciliationStatus {
  applied('applied'), replayed('replayed'),
  alreadyRequestedState('already_requested_state'), lifecycleConflict('lifecycle_conflict');
  const ThreadLifecycleReconciliationStatus(this.wireValue);
  final String wireValue;
  String toJson() => wireValue;
  static ThreadLifecycleReconciliationStatus fromJson(Object? value) {
    if (!_statuses.contains(value)) _fail('malformed_result', 'Unsupported reconciliation status');
    return values.firstWhere((status) => status.wireValue == value);
  }
}
final class ThreadLifecycleFormatException extends FormatException {
  const ThreadLifecycleFormatException(this.code, String message) : super(message);
  final String code;
}
Never _fail(String code, String message) => throw ThreadLifecycleFormatException(code, message);
Map<String, Object?> _object(Object? value, List<String> keys, String code) {
  if (value is! Map || value.keys.any((key) => key is! String)) _fail(code, 'Expected a JSON object');
  final result = Map<String, Object?>.from(value);
  if (result.length != keys.length || keys.any((key) => !result.containsKey(key))) _fail(code, 'Missing or unknown fields');
  return result;
}
String _nonblank(Object? value, String code) {
  if (value is! String || value.trim().isEmpty) _fail(code, 'Expected a nonblank string');
  return value;
}
int _revision(Object? value, String code) {
  if (value is! int || value < 1 || value > {{MAX_REVISION}}) _fail(code, 'Expected a positive safe integer revision');
  return value;
}
void _rejectTrusted(Object? value) {
  if (value is List) {
    for (final child in value) { _rejectTrusted(child); }
  } else if (value is Map) {
    for (final entry in value.entries) {
      if (entry.key is String && _trusted.contains((entry.key as String).replaceAll(RegExp('[^a-zA-Z0-9]'), '').toLowerCase())) {
        _fail('trusted_identity_field', '${entry.key} is server-derived');
      }
      _rejectTrusted(entry.value);
    }
  }
}
final class ThreadLifecycleInput {
  ThreadLifecycleInput({required this.intent, required this.threadId,
    required this.expectedLifecycleRevision, required this.idempotencyKey}) {
    _nonblank(threadId.value, 'malformed_input');
    _revision(expectedLifecycleRevision, 'malformed_input');
    _nonblank(idempotencyKey, 'malformed_input');
  }
  factory ThreadLifecycleInput.fromJson(Object? value) {
    _rejectTrusted(value);
    return _correlation(_object(value, _inputKeys, 'malformed_input'), 'malformed_input');
  }
  factory ThreadLifecycleInput.fromHttp(Object? threadId, Object? body) {
    _rejectTrusted(body);
    final raw = _object(body, _inputKeys.where((key) => key != 'threadId').toList(), 'malformed_input');
    return ThreadLifecycleInput.fromJson({...raw, 'threadId': threadId});
  }
  String get operation => '{{OPERATION}}';
  final ThreadLifecycleIntent intent;
  final ConversationId threadId;
  final int expectedLifecycleRevision;
  final String idempotencyKey;
  Map<String, Object?> toJson() => {'operation': operation, 'intent': intent.toJson(),
    'threadId': threadId.toJson(), 'expectedLifecycleRevision': expectedLifecycleRevision, 'idempotencyKey': idempotencyKey};
  Map<String, Object?> toHttpBody() => toJson()..remove('threadId');
}
ThreadLifecycleInput _correlation(Map<String, Object?> raw, String code) {
  if (raw['operation'] != '{{OPERATION}}' || !_intents.contains(raw['intent'])) _fail(code, 'Unsupported operation or explicit intent');
  return ThreadLifecycleInput(intent: ThreadLifecycleIntent.fromJson(raw['intent']),
    threadId: ConversationId(_nonblank(raw['threadId'], code)),
    expectedLifecycleRevision: _revision(raw['expectedLifecycleRevision'], code),
    idempotencyKey: _nonblank(raw['idempotencyKey'], code));
}
ThreadLifecycle _lifecycle(Object? value) {
  try { return ThreadLifecycle.fromJson(value); }
  on FormatException catch (error) { return _fail('malformed_result', error.message); }
  on ArgumentError catch (error) { return _fail('malformed_result', error.toString()); }
}
final class ThreadLifecycleResult {
  ThreadLifecycleResult({required this.input, required this.reconciliationStatus,
    required this.previousLifecycle, required this.threadLifecycle}) { _coherence(this); }
  factory ThreadLifecycleResult.fromJson(Object? value, {required ThreadLifecycleInput expectedInput}) {
    final raw = _object(value, _resultKeys, 'malformed_result');
    final input = _correlation(raw, 'malformed_result');
    final expected = expectedInput.toJson();
    if (_inputKeys.any((key) => raw[key] != expected[key])) _fail('incoherent_result', 'All request correlation fields must match');
    return ThreadLifecycleResult(input: input,
      reconciliationStatus: ThreadLifecycleReconciliationStatus.fromJson(raw['reconciliationStatus']),
      previousLifecycle: _lifecycle(raw['previousLifecycle']), threadLifecycle: _lifecycle(raw['threadLifecycle']));
  }
  final ThreadLifecycleInput input;
  final ThreadLifecycleReconciliationStatus reconciliationStatus;
  /// Canonical snapshot immediately before the original evaluation.
  final ThreadLifecycle previousLifecycle;
  /// Original canonical result; a replay may be older than local state.
  final ThreadLifecycle threadLifecycle;
  Map<String, Object?> toJson() => {...input.toJson(), 'reconciliationStatus': reconciliationStatus.toJson(),
    'previousLifecycle': previousLifecycle.toJson(), 'threadLifecycle': threadLifecycle.toJson()};
}
String _state(ThreadLifecycle value) => value.locked ? 'locked' : value.closedAt != null ? 'closed' : 'open';
bool _same(ThreadLifecycle a, ThreadLifecycle b) => a.revision == b.revision && a.locked == b.locked &&
  a.closedAt == b.closedAt && a.closedByUserId == b.closedByUserId;
void _coherence(ThreadLifecycleResult result) {
  final before = result.previousLifecycle, after = result.threadLifecycle;
  final expected = result.input.expectedLifecycleRevision;
  final target = _transitions[_state(before)]![result.input.intent.toJson()];
  final conflict = before.revision != expected || target == null;
  final status = result.reconciliationStatus;
  if (status == ThreadLifecycleReconciliationStatus.lifecycleConflict) {
    if (!conflict || !_same(before, after)) _fail('incoherent_result', 'Conflict requires revision mismatch or locked reopen, with unchanged state');
    return;
  }
  if (conflict) _fail('incoherent_result', 'Settled result requires matching revision and an eligible transition');
  if (status == ThreadLifecycleReconciliationStatus.alreadyRequestedState) {
    if (target != _state(before) || !_same(before, after)) _fail('incoherent_result', 'No-op must already satisfy intent and preserve state/revision');
    return;
  }
  if (target == _state(before) || _state(after) != target || expected == {{MAX_REVISION}} || after.revision != expected + 1) {
    _fail('incoherent_result', 'Applied/replayed must change state exactly once without overflow');
  }
  if (before.closedAt != null && after.closedAt != null &&
      (before.closedAt != after.closedAt || before.closedByUserId != after.closedByUserId)) {
    _fail('incoherent_result', 'Close/lock/unlock must retain existing closure metadata');
  }
}
