// Generated by scripts/generate-thread-follow.mjs from contracts/http/thread-follow.json.
// Do not edit this file directly.

import type { ThreadConversation } from "./conversation.js";
import type { ConversationId, IsoTimestamp } from "./identifiers.js";

/** Matches the persisted chat identifier UTF-8 bound. */
export const MAX_THREAD_FOLLOW_IDENTIFIER_UTF8_BYTES = {{IDENTIFIER_MAX}};

/** Matches `chat_idempotency_keys.client_key`. */
export const MAX_THREAD_FOLLOW_IDEMPOTENCY_KEY_UTF8_BYTES = {{IDEMPOTENCY_MAX}};

const ISO_TIMESTAMP_PATTERN =
  /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;

const TRUSTED_CONTEXT_FIELDS = new Set([
  "tenant",
  "tenantid",
  "organization",
  "organizationid",
  "actor",
  "actorid",
  "actorcontext",
  "actorrole",
  "actorroles",
  "actoruserid",
  "currentactor",
  "currentactorid",
  "currentuser",
  "currentuserid",
  "user",
  "userid",
  "principal",
  "principalid",
  "subject",
  "subjectid",
  "authenticateduser",
  "authenticateduserid",
  "identity",
  "session",
  "sessionid",
  "auth",
  "authentication",
  "authorization",
  "role",
  "roles",
  "capability",
  "capabilities",
  "permission",
  "permissions",
]);

const PARENT_TARGET_FIELDS = new Set([
  "parent",
  "parentid",
  "parentconversation",
  "parentconversationid",
  "channel",
  "channelid",
  "parentchannel",
  "parentchannelid",
]);

const CALLER_AUTHORED_SOURCE_FIELDS = new Set([
  "source",
  "followsource",
  "autofollowsource",
  "participationsource",
  "participationcause",
]);

/** Compile-time guard for identity and authorization resolved by the server. */
export interface NoTrustedThreadFollowMutationContext {
  readonly tenant?: never;
  readonly tenantId?: never;
  readonly organization?: never;
  readonly organizationId?: never;
  readonly actor?: never;
  readonly actorId?: never;
  readonly actorContext?: never;
  readonly actorRole?: never;
  readonly actorRoles?: never;
  readonly actorUserId?: never;
  readonly currentActor?: never;
  readonly currentActorId?: never;
  readonly currentUser?: never;
  readonly currentUserId?: never;
  readonly user?: never;
  readonly userId?: never;
  readonly principal?: never;
  readonly principalId?: never;
  readonly subject?: never;
  readonly subjectId?: never;
  readonly authenticatedUser?: never;
  readonly authenticatedUserId?: never;
  readonly identity?: never;
  readonly session?: never;
  readonly sessionId?: never;
  readonly auth?: never;
  readonly authentication?: never;
  readonly authorization?: never;
  readonly role?: never;
  readonly roles?: never;
  readonly capability?: never;
  readonly capabilities?: never;
  readonly permission?: never;
  readonly permissions?: never;
}

/**
 * A transport target whose discriminator proves the caller intends a thread.
 * Its fields deliberately match the `type` and `id` convention of
 * `ThreadConversation`; an opaque general conversation id is not sufficient.
 */
export type ThreadFollowTarget = Pick<ThreadConversation, "type" | "id">;

export type ThreadFollowMutationIntent = "follow" | "unfollow";

interface ThreadFollowMutationInputBase<
  Intent extends ThreadFollowMutationIntent,
> extends NoTrustedThreadFollowMutationContext {
  readonly operation: "{{OPERATION}}";
  readonly intent: Intent;
  readonly target: ThreadFollowTarget;
  /** Zero means the caller has not observed a persisted follow state yet. */
  readonly expectedFollowRevision: number;
  readonly idempotencyKey: string;
  /** Explicit user intent is always manual and never caller-sourced. */
  readonly source?: never;
  readonly followSource?: never;
  readonly autoFollowSource?: never;
  readonly participationSource?: never;
  readonly participationCause?: never;
  /** Boolean and toggle-style desired-state shapes are deliberately absent. */
  readonly isFollowing?: never;
  readonly following?: never;
  readonly toggle?: never;
  readonly toggleFollow?: never;
  /** Parent-channel and unverified general-conversation targets are absent. */
  readonly conversationId?: never;
  readonly channelId?: never;
  readonly parentConversationId?: never;
  readonly parentChannelId?: never;
}

export interface FollowThreadInput
  extends ThreadFollowMutationInputBase<"follow"> {}

export interface UnfollowThreadInput
  extends ThreadFollowMutationInputBase<"unfollow"> {}

/** Explicit desired state; ambiguous toggle semantics are unsupported. */
export type SetThreadFollowInput = FollowThreadInput | UnfollowThreadInput;

export type ThreadFollowSource = "manual" | "reply" | "mention";
export type ServerDerivedThreadAutoFollowSource = Exclude<
  ThreadFollowSource,
  "manual"
>;

interface CanonicalThreadFollowStateBase {
  readonly target: ThreadFollowTarget;
  readonly updatedAt: IsoTimestamp;
}

/** A manual unfollow is an explicit decision and cannot carry an auto source. */
export interface CanonicalManualThreadUnfollowState
  extends CanonicalThreadFollowStateBase {
  readonly isFollowing: false;
  readonly source: "manual";
}

export interface CanonicalFollowingThreadState
  extends CanonicalThreadFollowStateBase {
  readonly isFollowing: true;
  readonly source: ThreadFollowSource;
}

export type CanonicalThreadFollowState =
  | CanonicalManualThreadUnfollowState
  | CanonicalFollowingThreadState;

/**
 * Participation auto-follow is server-derived policy, never explicit command
 * input. Reply and mention may establish a following state only when they do
 * not overwrite a retained `CanonicalManualThreadUnfollowState`.
 */
export type ServerDerivedThreadParticipationAutoFollow = {
  readonly origin: "server_policy";
  readonly source: ServerDerivedThreadAutoFollowSource;
  readonly whenExplicitlyUnfollowed: "preserve_explicit_unfollow";
  readonly callerAuthored?: never;
};

export type ThreadFollowMutationReconciliationStatus =
  | "applied"
  | "replayed"
  | "already_requested_state"
  | "follow_revision_conflict";

interface ThreadFollowMutationResultBase<
  Intent extends ThreadFollowMutationIntent,
  Status extends ThreadFollowMutationReconciliationStatus,
> {
  readonly operation: "{{OPERATION}}";
  readonly intent: Intent;
  readonly reconciliationStatus: Status;
  readonly target: ThreadFollowTarget;
  readonly expectedFollowRevision: number;
  /** Exact request identity used to reconcile retries. */
  readonly idempotencyKey: string;
  readonly followRevision: number;
  /** Authoritative private state for the trusted current user. */
  readonly follow: CanonicalThreadFollowState;
}

export type SettledThreadFollowMutationResult<
  Intent extends ThreadFollowMutationIntent = ThreadFollowMutationIntent,
> = ThreadFollowMutationResultBase<
  Intent,
  "applied" | "replayed" | "already_requested_state"
>;

export type ConflictingThreadFollowMutationResult<
  Intent extends ThreadFollowMutationIntent = ThreadFollowMutationIntent,
> = ThreadFollowMutationResultBase<Intent, "follow_revision_conflict">;

export type SetThreadFollowResult =
  | SettledThreadFollowMutationResult<"follow">
  | SettledThreadFollowMutationResult<"unfollow">
  | ConflictingThreadFollowMutationResult<"follow">
  | ConflictingThreadFollowMutationResult<"unfollow">;

export type ThreadFollowMutationParseErrorCode =
  | "malformed_input"
  | "trusted_identity_field"
  | "parent_conversation_target"
  | "caller_authored_auto_follow"
  | "malformed_target"
  | "malformed_identifier"
  | "malformed_revision"
  | "malformed_timestamp"
  | "malformed_result"
  | "incoherent_result";

export class ThreadFollowMutationParseError extends Error {
  readonly code: ThreadFollowMutationParseErrorCode;

  constructor(code: ThreadFollowMutationParseErrorCode, message: string) {
    super(message);
    this.name = "ThreadFollowMutationParseError";
    this.code = code;
  }
}

const INPUT_KEYS = [
  "operation",
  "intent",
  "target",
  "expectedFollowRevision",
  "idempotencyKey",
] as const;

const RESULT_KEYS = [
  "operation",
  "intent",
  "reconciliationStatus",
  "target",
  "expectedFollowRevision",
  "idempotencyKey",
  "followRevision",
  "follow",
] as const;

export function parseFollowThreadInput(value: unknown): FollowThreadInput {
  const input = parseSetThreadFollowInput(value);
  if (input.intent !== "follow") {
    throw followError("malformed_input", "input.intent must be follow");
  }
  return input;
}

export function parseUnfollowThreadInput(value: unknown): UnfollowThreadInput {
  const input = parseSetThreadFollowInput(value);
  if (input.intent !== "unfollow") {
    throw followError("malformed_input", "input.intent must be unfollow");
  }
  return input;
}

/** Parses explicit manual follow-or-unfollow intent for one proven thread. */
export function parseSetThreadFollowInput(
  value: unknown,
): SetThreadFollowInput {
  rejectForbiddenInputFields(value);
  const input = requireRecord(value, "input", "malformed_input");
  assertExactKeys(input, INPUT_KEYS, "input", "malformed_input");

  if (input.operation !== "{{OPERATION}}") {
    throw followError(
      "malformed_input",
      "input.operation must be set_thread_follow; toggle semantics are not supported",
    );
  }
  const intent = readIntent(input.intent, "malformed_input");

  return {
    operation: "{{OPERATION}}",
    intent,
    target: parseTarget(input.target, "input.target", "malformed_target"),
    expectedFollowRevision: readExpectedRevision(
      input.expectedFollowRevision,
      "input.expectedFollowRevision",
    ),
    idempotencyKey: readIdempotencyKey(
      input.idempotencyKey,
      "input.idempotencyKey",
      "malformed_input",
    ),
  };
}

/** Parses an authoritative result and proves coherence with its exact request. */
export function parseSetThreadFollowResult(
  value: unknown,
  expectedInput: SetThreadFollowInput,
): SetThreadFollowResult {
  const request = parseSetThreadFollowInput(expectedInput);
  const result = requireRecord(value, "result", "malformed_result");
  assertExactKeys(result, RESULT_KEYS, "result", "malformed_result");

  if (result.operation !== "{{OPERATION}}") {
    throw followError(
      "malformed_result",
      "result.operation must be set_thread_follow",
    );
  }

  const intent = readIntent(result.intent, "malformed_result");
  const reconciliationStatus = readReconciliationStatus(
    result.reconciliationStatus,
  );
  const target = parseTarget(result.target, "result.target", "malformed_result");
  const expectedFollowRevision = readExpectedRevision(
    result.expectedFollowRevision,
    "result.expectedFollowRevision",
  );
  const idempotencyKey = readIdempotencyKey(
    result.idempotencyKey,
    "result.idempotencyKey",
    "malformed_result",
  );
  const followRevision = readCanonicalRevision(result.followRevision);
  const follow = parseCanonicalThreadFollowState(result.follow);

  if (
    intent !== request.intent ||
    !targetEquals(target, request.target) ||
    expectedFollowRevision !== request.expectedFollowRevision ||
    idempotencyKey !== request.idempotencyKey
  ) {
    throw followError(
      "incoherent_result",
      "result intent, target, expectedFollowRevision, and idempotencyKey must exactly match the request",
    );
  }
  if (!targetEquals(follow.target, request.target)) {
    throw followError(
      "incoherent_result",
      "result.follow.target must exactly match the requested thread target",
    );
  }

  const canonicalMatchesIntent =
    follow.isFollowing === (request.intent === "follow");
  if (reconciliationStatus === "applied" || reconciliationStatus === "replayed") {
    if (followRevision !== expectedFollowRevision + 1) {
      throw followError(
        "incoherent_result",
        `${reconciliationStatus} results must advance expectedFollowRevision by one`,
      );
    }
    assertExplicitManualState(follow, canonicalMatchesIntent);
  } else if (reconciliationStatus === "already_requested_state") {
    if (followRevision !== expectedFollowRevision) {
      throw followError(
        "incoherent_result",
        "already-requested-state results must preserve expectedFollowRevision",
      );
    }
    assertExplicitManualState(follow, canonicalMatchesIntent);
  } else {
    if (followRevision === expectedFollowRevision) {
      throw followError(
        "incoherent_result",
        "a follow revision conflict must carry a different authoritative revision",
      );
    }
  }

  return {
    operation: "{{OPERATION}}",
    intent,
    reconciliationStatus,
    target,
    expectedFollowRevision,
    idempotencyKey,
    followRevision,
    follow,
  } as SetThreadFollowResult;
}

function assertExplicitManualState(
  follow: CanonicalThreadFollowState,
  canonicalMatchesIntent: boolean,
): void {
  if (!canonicalMatchesIntent || follow.source !== "manual") {
    throw followError(
      "incoherent_result",
      "settled explicit intent must carry the requested state with manual source",
    );
  }
}

function parseTarget(
  value: unknown,
  path: string,
  code: "malformed_target" | "malformed_result",
): ThreadFollowTarget {
  const target = requireRecord(value, path, code);
  assertExactKeys(target, ["type", "id"], path, code);
  if (target.type !== "thread") {
    throw followError(
      code,
      `${path}.type must be thread; parent channels are not valid follow targets`,
    );
  }
  return {
    type: "thread",
    id: readIdentifier(target.id, `${path}.id`, code),
  };
}

export function parseCanonicalThreadFollowState(value: unknown): CanonicalThreadFollowState {
  const follow = requireRecord(value, "result.follow", "malformed_result");
  assertExactKeys(
    follow,
    ["target", "isFollowing", "source", "updatedAt"],
    "result.follow",
    "malformed_result",
  );
  const target = parseTarget(
    follow.target,
    "result.follow.target",
    "malformed_result",
  );
  if (typeof follow.isFollowing !== "boolean") {
    throw followError(
      "malformed_result",
      "result.follow.isFollowing must be boolean",
    );
  }
  const source = readFollowSource(follow.source);
  if (!follow.isFollowing && source !== "manual") {
    throw followError(
      "incoherent_result",
      "an explicit unfollow cannot carry a reply or mention auto-follow source",
    );
  }
  const updatedAt = readIsoTimestamp(follow.updatedAt);
  return follow.isFollowing
    ? { target, isFollowing: true, source, updatedAt }
    : { target, isFollowing: false, source: "manual", updatedAt };
}

function readIntent(
  value: unknown,
  code: "malformed_input" | "malformed_result",
): ThreadFollowMutationIntent {
  if (value !== "follow" && value !== "unfollow") {
    throw followError(
      code,
      "intent must be follow or unfollow; toggle semantics are not supported",
    );
  }
  return value;
}

function readReconciliationStatus(
  value: unknown,
): ThreadFollowMutationReconciliationStatus {
  if (
    value !== "applied" &&
    value !== "replayed" &&
    value !== "already_requested_state" &&
    value !== "follow_revision_conflict"
  ) {
    throw followError(
      "malformed_result",
      "result.reconciliationStatus is not supported",
    );
  }
  return value;
}

function readFollowSource(value: unknown): ThreadFollowSource {
  if (value !== "manual" && value !== "reply" && value !== "mention") {
    throw followError(
      "malformed_result",
      "result.follow.source must be manual, reply, or mention",
    );
  }
  return value;
}

function readExpectedRevision(value: unknown, path: string): number {
  if (
    !Number.isSafeInteger(value) ||
    (value as number) < 0 ||
    (value as number) >= Number.MAX_SAFE_INTEGER
  ) {
    throw followError(
      "malformed_revision",
      `${path} must be a nonnegative safe integer that can advance by one`,
    );
  }
  return value as number;
}

function readCanonicalRevision(value: unknown): number {
  if (!Number.isSafeInteger(value) || (value as number) < 0) {
    throw followError(
      "malformed_revision",
      "result.followRevision must be a nonnegative safe integer",
    );
  }
  return value as number;
}

function readIdentifier(
  value: unknown,
  path: string,
  code: "malformed_target" | "malformed_result",
): ConversationId {
  if (
    typeof value !== "string" ||
    value.length === 0 ||
    value.trim() !== value ||
    value !== value.normalize("NFC") ||
    containsUnsafeUnicode(value) ||
    utf8ByteLength(value) > MAX_THREAD_FOLLOW_IDENTIFIER_UTF8_BYTES
  ) {
    throw followError(
      "malformed_identifier",
      `${path} must be a safe, NFC-normalized identifier of at most ${MAX_THREAD_FOLLOW_IDENTIFIER_UTF8_BYTES} UTF-8 bytes`,
    );
  }
  return value as ConversationId;
}

function readIdempotencyKey(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): string {
  if (
    typeof value !== "string" ||
    value.trim().length === 0 ||
    value.trim() !== value ||
    value !== value.normalize("NFC") ||
    containsUnsafeUnicode(value) ||
    utf8ByteLength(value) > MAX_THREAD_FOLLOW_IDEMPOTENCY_KEY_UTF8_BYTES
  ) {
    throw followError(
      code,
      `${path} must be a safe, NFC-normalized nonblank string of at most ${MAX_THREAD_FOLLOW_IDEMPOTENCY_KEY_UTF8_BYTES} UTF-8 bytes`,
    );
  }
  return value;
}

function readIsoTimestamp(value: unknown): IsoTimestamp {
  if (typeof value !== "string" || !isFiniteIsoTimestamp(value)) {
    throw followError(
      "malformed_timestamp",
      "result.follow.updatedAt must be a finite ISO-8601 timestamp",
    );
  }
  return value;
}

function isFiniteIsoTimestamp(value: string): boolean {
  const match = ISO_TIMESTAMP_PATTERN.exec(value);
  if (match === null || !Number.isFinite(Date.parse(value))) return false;

  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const hour = Number(match[4]);
  const minute = Number(match[5]);
  const second = Number(match[6]);
  const leapYear = year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);
  const daysInMonth = [
    31,
    leapYear ? 29 : 28,
    31,
    30,
    31,
    30,
    31,
    31,
    30,
    31,
    30,
    31,
  ];
  return (
    month >= 1 &&
    month <= 12 &&
    day >= 1 &&
    day <= (daysInMonth[month - 1] ?? 0) &&
    hour <= 23 &&
    minute <= 59 &&
    second <= 59
  );
}

function rejectForbiddenInputFields(value: unknown, path = "input"): void {
  if (Array.isArray(value)) {
    value.forEach((entry, index) =>
      rejectForbiddenInputFields(entry, `${path}[${index}]`),
    );
    return;
  }
  if (!isRecord(value)) return;

  for (const [key, nested] of Object.entries(value)) {
    const normalized = normalizeFieldName(key);
    if (TRUSTED_CONTEXT_FIELDS.has(normalized)) {
      throw followError(
        "trusted_identity_field",
        `${path}.${key} is server-derived and cannot be supplied by a client`,
      );
    }
    if (PARENT_TARGET_FIELDS.has(normalized)) {
      throw followError(
        "parent_conversation_target",
        `${path}.${key} cannot target a parent channel`,
      );
    }
    if (CALLER_AUTHORED_SOURCE_FIELDS.has(normalized)) {
      throw followError(
        "caller_authored_auto_follow",
        `${path}.${key} is server-derived; explicit follow intent is manual`,
      );
    }
    rejectForbiddenInputFields(nested, `${path}.${key}`);
  }
}

function normalizeFieldName(value: string): string {
  return value.replaceAll(/[^a-zA-Z0-9]/g, "").toLowerCase();
}

function assertExactKeys(
  value: Record<string, unknown>,
  expected: readonly string[],
  path: string,
  code:
    | "malformed_input"
    | "malformed_target"
    | "malformed_result",
): void {
  const actual = Object.keys(value).sort();
  const expectedKeys = expected.slice().sort();
  if (
    actual.length !== expectedKeys.length ||
    actual.some((key, index) => key !== expectedKeys[index])
  ) {
    throw followError(
      code,
      `${path} must contain exactly: ${expectedKeys.join(", ")}`,
    );
  }
}

function requireRecord(
  value: unknown,
  path: string,
  code:
    | "malformed_input"
    | "malformed_target"
    | "malformed_result",
): Record<string, unknown> {
  if (!isRecord(value)) {
    throw followError(code, `${path} must be an object`);
  }
  return value;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function targetEquals(
  left: ThreadFollowTarget,
  right: ThreadFollowTarget,
): boolean {
  return left.type === right.type && left.id === right.id;
}

function containsUnsafeUnicode(value: string): boolean {
  return /[\u0000-\u001f\u007f-\u009f\u2028\u2029]/u.test(value);
}

function utf8ByteLength(value: string): number {
  return new TextEncoder().encode(value).byteLength;
}

function followError(
  code: ThreadFollowMutationParseErrorCode,
  message: string,
): ThreadFollowMutationParseError {
  return new ThreadFollowMutationParseError(code, message);
}
