// Generated by scripts/generate-conversation-membership.mjs from contracts/http/conversation-membership.json.
// Do not edit this file directly.

import type {
  ConversationId,
  IsoTimestamp,
  UserId,
} from "./identifiers.js";
import type {
  ConversationMemberRole,
  ConversationMemberState,
} from "./member-read-state.js";

/** Matches the persisted `chat_idempotency_keys.client_key` UTF-8 bound. */
export const MAX_CONVERSATION_MEMBERSHIP_IDEMPOTENCY_KEY_UTF8_BYTES = 255;

const ISO_TIMESTAMP_PATTERN =
  /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;

const SERVER_DERIVED_FIELDS = new Set([
  "tenant",
  "tenantid",
  "organization",
  "organizationid",
  "actor",
  "actorid",
  "actorcontext",
  "actorrole",
  "actorroles",
  "actoruserid",
  "currentactor",
  "currentactorid",
  "currentuser",
  "currentuserid",
  "user",
  "userid",
  "principal",
  "principalid",
  "subject",
  "subjectid",
  "authenticateduser",
  "authenticateduserid",
  "identity",
  "session",
  "sessionid",
  "auth",
  "authorization",
  "role",
  "roles",
  "capability",
  "capabilities",
  "permission",
  "permissions",
  "visibility",
  "visibilityauthorization",
  "entity",
  "entityid",
  "entitytype",
  "hostentity",
  "hostentityid",
  "hostentitytype",
  "hostentityauthorization",
]);

/** Compile-time guard for all identity and authorization resolved by the server. */
export interface NoTrustedConversationMembershipContext {
  readonly tenant?: never;
  readonly tenantId?: never;
  readonly organization?: never;
  readonly organizationId?: never;
  readonly actor?: never;
  readonly actorId?: never;
  readonly actorContext?: never;
  readonly actorRole?: never;
  readonly actorRoles?: never;
  readonly actorUserId?: never;
  readonly currentActor?: never;
  readonly currentActorId?: never;
  readonly currentUser?: never;
  readonly currentUserId?: never;
  readonly user?: never;
  readonly userId?: never;
  readonly principal?: never;
  readonly principalId?: never;
  readonly subject?: never;
  readonly subjectId?: never;
  readonly authenticatedUser?: never;
  readonly authenticatedUserId?: never;
  readonly identity?: never;
  readonly session?: never;
  readonly sessionId?: never;
  readonly auth?: never;
  readonly authorization?: never;
  readonly role?: never;
  readonly roles?: never;
  readonly capability?: never;
  readonly capabilities?: never;
  readonly permission?: never;
  readonly permissions?: never;
  readonly visibility?: never;
  readonly visibilityAuthorization?: never;
  readonly entity?: never;
  readonly entityId?: never;
  readonly entityType?: never;
  readonly hostEntity?: never;
  readonly hostEntityId?: never;
  readonly hostEntityType?: never;
  readonly hostEntityAuthorization?: never;
}

export type ConversationMembershipMutationIntent =
  | "join"
  | "leave"
  | "add_member"
  | "remove_member"
  | "change_member_role";

interface ConversationMembershipMutationInputBase<
  Intent extends ConversationMembershipMutationIntent,
> extends NoTrustedConversationMembershipContext {
  readonly operation: "mutate_conversation_membership";
  readonly intent: Intent;
  readonly conversationId: ConversationId;
  /** Optimistic-concurrency revision for the complete membership list. */
  readonly expectedMemberListRevision: number;
  readonly idempotencyKey: string;
}

/** Explicit self-service request; the trusted actor is resolved server-side. */
export interface JoinConversationInput
  extends ConversationMembershipMutationInputBase<"join"> {
  readonly targetUserId?: never;
  readonly requestedRole?: never;
}

/** Explicit self-service request; the trusted actor is resolved server-side. */
export interface LeaveConversationInput
  extends ConversationMembershipMutationInputBase<"leave"> {
  readonly targetUserId?: never;
  readonly requestedRole?: never;
}

/** Adds one host-directory user with an explicitly requested chat role. */
export interface AddConversationMemberInput
  extends ConversationMembershipMutationInputBase<"add_member"> {
  readonly targetUserId: UserId;
  readonly requestedRole: ConversationMemberRole;
}

/** Removes one host-directory user without accepting a role or toggle state. */
export interface RemoveConversationMemberInput
  extends ConversationMembershipMutationInputBase<"remove_member"> {
  readonly targetUserId: UserId;
  readonly requestedRole?: never;
}

/** Replaces one active member's chat role with an explicit requested role. */
export interface ChangeConversationMemberRoleInput
  extends ConversationMembershipMutationInputBase<"change_member_role"> {
  readonly targetUserId: UserId;
  readonly requestedRole: ConversationMemberRole;
}

export type ConversationMembershipMutationInput =
  | JoinConversationInput
  | LeaveConversationInput
  | AddConversationMemberInput
  | RemoveConversationMemberInput
  | ChangeConversationMemberRoleInput;

/** Tenant and conversation are inherited from the enclosing authoritative result. */
export interface CanonicalConversationMemberState {
  readonly userId: UserId;
  readonly role: ConversationMemberRole;
  readonly state: ConversationMemberState;
  readonly joinedAt: IsoTimestamp;
  readonly updatedAt: IsoTimestamp;
}

export type ConversationMembershipSafetyError =
  | {
      readonly code: "last_owner";
      readonly message: string;
    }
  | {
      readonly code: "last_active_member";
      readonly message: string;
    };

export type ConversationMembershipReconciliationStatus =
  | "applied"
  | "replayed"
  | "already_requested_state"
  | "member_list_conflict"
  | "safety_rejected";

interface ConversationMembershipResultBase<
  Intent extends ConversationMembershipMutationIntent,
> {
  readonly operation: "mutate_conversation_membership";
  readonly intent: Intent;
  readonly conversationId: ConversationId;
  /** Exact echo of the request's optimistic-concurrency revision. */
  readonly expectedMemberListRevision: number;
  /** Authoritative revision of the complete canonical member list below. */
  readonly memberListRevision: number;
  /** Affected host-directory user; self intents derive this from the session. */
  readonly memberUserId: UserId;
  /** Complete list in ascending userId order, with no duplicate identities. */
  readonly members: readonly CanonicalConversationMemberState[];
}

type ConversationMembershipResultIntentFields<
  Intent extends ConversationMembershipMutationIntent,
> = Intent extends "add_member" | "change_member_role"
  ? {
      readonly targetUserId: UserId;
      readonly requestedRole: ConversationMemberRole;
    }
  : Intent extends "remove_member"
    ? {
        readonly targetUserId: UserId;
        readonly requestedRole?: never;
      }
    : {
        readonly targetUserId?: never;
        readonly requestedRole?: never;
      };

type SettledConversationMembershipResult = {
  readonly reconciliationStatus:
    | "applied"
    | "replayed"
    | "already_requested_state";
  readonly safetyError?: never;
};

type ConflictingConversationMembershipResult = {
  readonly reconciliationStatus: "member_list_conflict";
  readonly safetyError?: never;
};

type SafetyErrorForIntent<Intent extends ConversationMembershipMutationIntent> =
  Intent extends "leave" | "remove_member"
    ? ConversationMembershipSafetyError
    : Intent extends "change_member_role"
      ? Extract<ConversationMembershipSafetyError, { readonly code: "last_owner" }>
      : never;

type SafetyRejectedConversationMembershipResult<
  Intent extends ConversationMembershipMutationIntent,
> = SafetyErrorForIntent<Intent> extends never
  ? never
  : {
      readonly reconciliationStatus: "safety_rejected";
      readonly safetyError: SafetyErrorForIntent<Intent>;
    };

type ConversationMembershipMutationResultForIntent<
  Intent extends ConversationMembershipMutationIntent,
> = ConversationMembershipResultBase<Intent> &
  ConversationMembershipResultIntentFields<Intent> &
  (
    | SettledConversationMembershipResult
    | ConflictingConversationMembershipResult
    | SafetyRejectedConversationMembershipResult<Intent>
  );

export type JoinConversationResult =
  ConversationMembershipMutationResultForIntent<"join">;
export type LeaveConversationResult =
  ConversationMembershipMutationResultForIntent<"leave">;
export type AddConversationMemberResult =
  ConversationMembershipMutationResultForIntent<"add_member">;
export type RemoveConversationMemberResult =
  ConversationMembershipMutationResultForIntent<"remove_member">;
export type ChangeConversationMemberRoleResult =
  ConversationMembershipMutationResultForIntent<"change_member_role">;

export type ConversationMembershipMutationResult =
  | JoinConversationResult
  | LeaveConversationResult
  | AddConversationMemberResult
  | RemoveConversationMemberResult
  | ChangeConversationMemberRoleResult;

export type ConversationMembershipParseErrorCode =
  | "malformed_input"
  | "server_derived_field"
  | "malformed_identifier"
  | "malformed_revision"
  | "malformed_result"
  | "duplicate_member"
  | "noncanonical_member_order"
  | "incoherent_result";

export class ConversationMembershipParseError extends Error {
  readonly code: ConversationMembershipParseErrorCode;

  constructor(code: ConversationMembershipParseErrorCode, message: string) {
    super(message);
    this.name = "ConversationMembershipParseError";
    this.code = code;
  }
}

const BASE_INPUT_KEYS = [
  "operation",
  "intent",
  "conversationId",
  "expectedMemberListRevision",
  "idempotencyKey",
] as const;
const TARGET_INPUT_KEYS = [...BASE_INPUT_KEYS, "targetUserId"] as const;
const TARGET_ROLE_INPUT_KEYS = [...TARGET_INPUT_KEYS, "requestedRole"] as const;

const BASE_RESULT_KEYS = [
  "operation",
  "intent",
  "reconciliationStatus",
  "conversationId",
  "expectedMemberListRevision",
  "memberListRevision",
  "memberUserId",
  "members",
] as const;

export function parseJoinConversationInput(value: unknown): JoinConversationInput {
  return parseInput(value, "join") as JoinConversationInput;
}

export function parseLeaveConversationInput(value: unknown): LeaveConversationInput {
  return parseInput(value, "leave") as LeaveConversationInput;
}

export function parseAddConversationMemberInput(
  value: unknown,
): AddConversationMemberInput {
  return parseInput(value, "add_member") as AddConversationMemberInput;
}

export function parseRemoveConversationMemberInput(
  value: unknown,
): RemoveConversationMemberInput {
  return parseInput(value, "remove_member") as RemoveConversationMemberInput;
}

export function parseChangeConversationMemberRoleInput(
  value: unknown,
): ChangeConversationMemberRoleInput {
  return parseInput(value, "change_member_role") as ChangeConversationMemberRoleInput;
}

export function parseConversationMembershipMutationInput(
  value: unknown,
): ConversationMembershipMutationInput {
  rejectServerDerivedFields(value);
  const input = requireRecord(value, "input", "malformed_input");
  return parseInputRecord(input, readIntent(input.intent, "malformed_input"));
}

/** Parses an authoritative result and reconciles it with the exact request. */
export function parseConversationMembershipMutationResult(
  value: unknown,
  expectedInput: ConversationMembershipMutationInput,
): ConversationMembershipMutationResult {
  const request = parseConversationMembershipMutationInput(expectedInput);
  const result = requireRecord(value, "result", "malformed_result");
  const intent = readIntent(result.intent, "malformed_result");
  const status = readReconciliationStatus(result.reconciliationStatus);
  const targeted = isTargetedIntent(intent);
  const roleBearing = isRoleBearingIntent(intent);
  const expectedKeys = [
    ...BASE_RESULT_KEYS,
    ...(targeted ? ["targetUserId"] : []),
    ...(roleBearing ? ["requestedRole"] : []),
    ...(status === "safety_rejected" ? ["safetyError"] : []),
  ];
  assertExactKeys(result, expectedKeys, "result", "malformed_result");

  if (result.operation !== "mutate_conversation_membership") {
    throw membershipError(
      "malformed_result",
      "result.operation must be mutate_conversation_membership",
    );
  }

  const conversationId = readIdentifier(
    result.conversationId,
    "result.conversationId",
    "malformed_result",
  ) as ConversationId;
  const expectedMemberListRevision = readRevision(
    result.expectedMemberListRevision,
    "result.expectedMemberListRevision",
    "malformed_result",
  );
  const memberListRevision = readRevision(
    result.memberListRevision,
    "result.memberListRevision",
    "malformed_result",
  );
  const memberUserId = readIdentifier(
    result.memberUserId,
    "result.memberUserId",
    "malformed_result",
  ) as UserId;
  const members = parseCanonicalMembers(result.members);

  if (
    intent !== request.intent ||
    conversationId !== request.conversationId ||
    expectedMemberListRevision !== request.expectedMemberListRevision
  ) {
    throw membershipError(
      "incoherent_result",
      "result intent, conversationId, and expectedMemberListRevision must match the request",
    );
  }

  const targetUserId = targeted
    ? (readIdentifier(
        result.targetUserId,
        "result.targetUserId",
        "malformed_result",
      ) as UserId)
    : undefined;
  const requestedRole = roleBearing
    ? readRole(result.requestedRole, "result.requestedRole", "malformed_result")
    : undefined;

  if (targeted) {
    const requestTarget = request.targetUserId;
    if (targetUserId !== requestTarget || memberUserId !== requestTarget) {
      throw membershipError(
        "incoherent_result",
        "targeted results must echo the request target as targetUserId and memberUserId",
      );
    }
  }
  const requestRole =
    "requestedRole" in request ? request.requestedRole : undefined;
  if (roleBearing && requestedRole !== requestRole) {
    throw membershipError(
      "incoherent_result",
      "result.requestedRole must match the request",
    );
  }

  validateRevisionOutcome(status, expectedMemberListRevision, memberListRevision);
  const affectedMember = members.find((member) => member.userId === memberUserId);
  const safetyError =
    status === "safety_rejected"
      ? parseSafetyError(result.safetyError, intent, members, affectedMember)
      : undefined;
  if (
    status === "safety_rejected" &&
    intent === "change_member_role" &&
    requestedRole === "owner"
  ) {
    throw membershipError(
      "incoherent_result",
      "requesting the existing owner role cannot produce last-owner protection",
    );
  }

  if (status !== "member_list_conflict" && affectedMember === undefined) {
    throw membershipError(
      "incoherent_result",
      "settled and safety results must include the affected member",
    );
  }
  if (
    status === "applied" ||
    status === "replayed" ||
    status === "already_requested_state"
  ) {
    validateSettledMember(intent, affectedMember!, requestedRole);
  }

  return {
    operation: "mutate_conversation_membership",
    intent,
    reconciliationStatus: status,
    conversationId,
    expectedMemberListRevision,
    memberListRevision,
    memberUserId,
    members,
    ...(targeted ? { targetUserId } : {}),
    ...(roleBearing ? { requestedRole } : {}),
    ...(status === "safety_rejected" ? { safetyError } : {}),
  } as ConversationMembershipMutationResult;
}

function parseInput<Intent extends ConversationMembershipMutationIntent>(
  value: unknown,
  expectedIntent: Intent,
): ConversationMembershipMutationInput {
  rejectServerDerivedFields(value);
  const input = requireRecord(value, "input", "malformed_input");
  if (input.intent !== expectedIntent) {
    throw membershipError(
      "malformed_input",
      `input.intent must be ${expectedIntent}`,
    );
  }
  return parseInputRecord(input, expectedIntent);
}

function parseInputRecord(
  input: Record<string, unknown>,
  intent: ConversationMembershipMutationIntent,
): ConversationMembershipMutationInput {
  const expectedKeys = isRoleBearingIntent(intent)
    ? TARGET_ROLE_INPUT_KEYS
    : isTargetedIntent(intent)
      ? TARGET_INPUT_KEYS
      : BASE_INPUT_KEYS;
  assertExactKeys(input, expectedKeys, "input", "malformed_input");

  if (input.operation !== "mutate_conversation_membership") {
    throw membershipError(
      "malformed_input",
      "input.operation must be mutate_conversation_membership",
    );
  }

  const common = {
    operation: "mutate_conversation_membership" as const,
    intent,
    conversationId: readIdentifier(
      input.conversationId,
      "input.conversationId",
      "malformed_input",
    ) as ConversationId,
    expectedMemberListRevision: readRevision(
      input.expectedMemberListRevision,
      "input.expectedMemberListRevision",
      "malformed_input",
    ),
    idempotencyKey: readIdempotencyKey(input.idempotencyKey),
  };

  if (intent === "join") return { ...common, intent: "join" };
  if (intent === "leave") return { ...common, intent: "leave" };

  const targetUserId = readIdentifier(
    input.targetUserId,
    "input.targetUserId",
    "malformed_input",
  ) as UserId;
  if (intent === "remove_member") {
    return { ...common, intent: "remove_member", targetUserId };
  }

  return {
    ...common,
    targetUserId,
    requestedRole: readRole(
      input.requestedRole,
      "input.requestedRole",
      "malformed_input",
    ),
  } as AddConversationMemberInput | ChangeConversationMemberRoleInput;
}

function parseCanonicalMembers(
  value: unknown,
): readonly CanonicalConversationMemberState[] {
  if (!Array.isArray(value)) {
    throw membershipError("malformed_result", "result.members must be an array");
  }
  if (value.length === 0) {
    throw membershipError(
      "malformed_result",
      "result.members must contain the authoritative membership list",
    );
  }

  const members: CanonicalConversationMemberState[] = [];
  const seen = new Set<string>();
  let previousUserId: string | undefined;
  for (let index = 0; index < value.length; index += 1) {
    const path = `result.members[${index}]`;
    const member = requireRecord(value[index], path, "malformed_result");
    assertExactKeys(
      member,
      ["userId", "role", "state", "joinedAt", "updatedAt"],
      path,
      "malformed_result",
    );
    const userId = readIdentifier(
      member.userId,
      `${path}.userId`,
      "malformed_result",
    ) as UserId;
    if (seen.has(userId)) {
      throw membershipError(
        "duplicate_member",
        `result.members cannot contain duplicate userId ${JSON.stringify(userId)}`,
      );
    }
    if (previousUserId !== undefined && previousUserId >= userId) {
      throw membershipError(
        "noncanonical_member_order",
        "result.members must be ordered by ascending userId",
      );
    }
    seen.add(userId);
    previousUserId = userId;
    members.push({
      userId,
      role: readRole(member.role, `${path}.role`, "malformed_result"),
      state: readMemberState(member.state, `${path}.state`),
      joinedAt: readIsoTimestamp(member.joinedAt, `${path}.joinedAt`),
      updatedAt: readIsoTimestamp(member.updatedAt, `${path}.updatedAt`),
    });
  }
  return members;
}

function validateRevisionOutcome(
  status: ConversationMembershipReconciliationStatus,
  expected: number,
  authoritative: number,
): void {
  if (status === "applied" || status === "replayed") {
    if (authoritative !== expected + 1) {
      throw membershipError(
        "incoherent_result",
        `${status} results must advance expectedMemberListRevision by one`,
      );
    }
    return;
  }
  if (status === "member_list_conflict") {
    if (authoritative === expected) {
      throw membershipError(
        "incoherent_result",
        "a member-list conflict must carry a different authoritative revision",
      );
    }
    return;
  }
  if (authoritative !== expected) {
    throw membershipError(
      "incoherent_result",
      `${status} results must preserve the expected member-list revision`,
    );
  }
}

function validateSettledMember(
  intent: ConversationMembershipMutationIntent,
  member: CanonicalConversationMemberState,
  requestedRole: ConversationMemberRole | undefined,
): void {
  const expectedState =
    intent === "leave"
      ? "left"
      : intent === "remove_member"
        ? "removed"
        : "active";
  if (member.state !== expectedState) {
    throw membershipError(
      "incoherent_result",
      `a settled ${intent} result must report the affected member as ${expectedState}`,
    );
  }
  if (requestedRole !== undefined && member.role !== requestedRole) {
    throw membershipError(
      "incoherent_result",
      `a settled ${intent} result must report the requested role`,
    );
  }
}

function parseSafetyError(
  value: unknown,
  intent: ConversationMembershipMutationIntent,
  members: readonly CanonicalConversationMemberState[],
  affectedMember: CanonicalConversationMemberState | undefined,
): ConversationMembershipSafetyError {
  if (intent === "join" || intent === "add_member") {
    throw membershipError(
      "incoherent_result",
      `${intent} cannot produce an owner or last-member safety rejection`,
    );
  }
  const safety = requireRecord(
    value,
    "result.safetyError",
    "malformed_result",
  );
  assertExactKeys(
    safety,
    ["code", "message"],
    "result.safetyError",
    "malformed_result",
  );
  const message = readNonBlankString(
    safety.message,
    "result.safetyError.message",
    "malformed_result",
  );
  if (affectedMember === undefined || affectedMember.state !== "active") {
    throw membershipError(
      "incoherent_result",
      "a safety rejection requires the affected member to remain active",
    );
  }

  if (safety.code === "last_owner") {
    if (affectedMember.role !== "owner") {
      throw membershipError(
        "incoherent_result",
        "last_owner requires the affected member to be an owner",
      );
    }
    const activeOwners = members.filter(
      (member) => member.state === "active" && member.role === "owner",
    );
    if (activeOwners.length !== 1 || activeOwners[0]?.userId !== affectedMember.userId) {
      throw membershipError(
        "incoherent_result",
        "last_owner requires exactly one active owner matching the affected member",
      );
    }
    return { code: "last_owner", message };
  }

  if (safety.code === "last_active_member") {
    if (intent === "change_member_role") {
      throw membershipError(
        "incoherent_result",
        "change_member_role cannot produce last_active_member",
      );
    }
    const activeMembers = members.filter((member) => member.state === "active");
    if (
      activeMembers.length !== 1 ||
      activeMembers[0]?.userId !== affectedMember.userId
    ) {
      throw membershipError(
        "incoherent_result",
        "last_active_member requires exactly one active member matching the affected member",
      );
    }
    return { code: "last_active_member", message };
  }

  throw membershipError(
    "malformed_result",
    "result.safetyError.code must be last_owner or last_active_member",
  );
}

function isTargetedIntent(
  intent: ConversationMembershipMutationIntent,
): intent is "add_member" | "remove_member" | "change_member_role" {
  return (
    intent === "add_member" ||
    intent === "remove_member" ||
    intent === "change_member_role"
  );
}

function isRoleBearingIntent(
  intent: ConversationMembershipMutationIntent,
): intent is "add_member" | "change_member_role" {
  return intent === "add_member" || intent === "change_member_role";
}

function readIntent(
  value: unknown,
  code: "malformed_input" | "malformed_result",
): ConversationMembershipMutationIntent {
  if (
    value !== "join" &&
    value !== "leave" &&
    value !== "add_member" &&
    value !== "remove_member" &&
    value !== "change_member_role"
  ) {
    throw membershipError(
      code,
      "intent must be join, leave, add_member, remove_member, or change_member_role",
    );
  }
  return value;
}

function readReconciliationStatus(
  value: unknown,
): ConversationMembershipReconciliationStatus {
  if (
    value !== "applied" &&
    value !== "replayed" &&
    value !== "already_requested_state" &&
    value !== "member_list_conflict" &&
    value !== "safety_rejected"
  ) {
    throw membershipError(
      "malformed_result",
      "result.reconciliationStatus is unsupported",
    );
  }
  return value;
}

function readRole(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): ConversationMemberRole {
  if (value !== "owner" && value !== "moderator" && value !== "member") {
    throw membershipError(code, `${path} must be owner, moderator, or member`);
  }
  return value;
}

function readMemberState(
  value: unknown,
  path: string,
): ConversationMemberState {
  if (value !== "active" && value !== "left" && value !== "removed") {
    throw membershipError(
      "malformed_result",
      `${path} must be active, left, or removed`,
    );
  }
  return value;
}

function rejectServerDerivedFields(value: unknown, path = "input"): void {
  if (Array.isArray(value)) {
    value.forEach((entry, index) =>
      rejectServerDerivedFields(entry, `${path}[${index}]`),
    );
    return;
  }
  if (!isRecord(value)) return;

  for (const [key, nested] of Object.entries(value)) {
    const normalizedKey = key.replaceAll(/[^a-zA-Z0-9]/g, "").toLowerCase();
    if (SERVER_DERIVED_FIELDS.has(normalizedKey)) {
      throw membershipError(
        "server_derived_field",
        `${path}.${key} is server-derived and cannot be supplied by a client`,
      );
    }
    rejectServerDerivedFields(nested, `${path}.${key}`);
  }
}

function assertExactKeys(
  value: Record<string, unknown>,
  expected: readonly string[],
  path: string,
  code: "malformed_input" | "malformed_result",
): void {
  const expectedSet = new Set(expected);
  for (const key of Object.keys(value)) {
    if (!expectedSet.has(key)) {
      throw membershipError(code, `${path}.${key} is not supported`);
    }
  }
  for (const key of expected) {
    if (!Object.hasOwn(value, key)) {
      throw membershipError(code, `${path}.${key} is required`);
    }
  }
}

function requireRecord(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): Record<string, unknown> {
  if (!isRecord(value)) {
    throw membershipError(code, `${path} must be an object`);
  }
  return value;
}

function readIdentifier(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): string {
  if (
    typeof value !== "string" ||
    value.length === 0 ||
    value.trim() !== value
  ) {
    throw membershipError("malformed_identifier", `${path} must be a nonblank identifier without surrounding whitespace`);
  }
  return value;
}

function readRevision(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): number {
  if (!Number.isSafeInteger(value) || (value as number) < 1) {
    throw membershipError("malformed_revision", `${path} must be a positive safe integer`);
  }
  return value as number;
}

function readIdempotencyKey(value: unknown): string {
  const key = readNonBlankString(
    value,
    "input.idempotencyKey",
    "malformed_input",
  );
  if (
    new TextEncoder().encode(key).byteLength >
    MAX_CONVERSATION_MEMBERSHIP_IDEMPOTENCY_KEY_UTF8_BYTES
  ) {
    throw membershipError(
      "malformed_input",
      `input.idempotencyKey cannot exceed ${MAX_CONVERSATION_MEMBERSHIP_IDEMPOTENCY_KEY_UTF8_BYTES} UTF-8 bytes`,
    );
  }
  return key;
}

function readNonBlankString(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw membershipError(code, `${path} must be a nonblank string`);
  }
  return value;
}

function readIsoTimestamp(value: unknown, path: string): IsoTimestamp {
  if (
    typeof value !== "string" ||
    !ISO_TIMESTAMP_PATTERN.test(value) ||
    !Number.isFinite(Date.parse(value))
  ) {
    throw membershipError(
      "malformed_result",
      `${path} must be an ISO-8601 timestamp`,
    );
  }
  return value;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function membershipError(
  code: ConversationMembershipParseErrorCode,
  message: string,
): ConversationMembershipParseError {
  return new ConversationMembershipParseError(code, message);
}
