// Generated by scripts/generate-conversation-preference.mjs from contracts/http/conversation-preference.json.
// Do not edit this file directly.

import type { ConversationId, IsoTimestamp } from "./identifiers.js";
import type {
  ConversationMuteState,
  ConversationNotificationPreference,
} from "./member-read-state.js";

export const MAX_CONVERSATION_PREFERENCE_IDENTIFIER_UTF8_BYTES = 255;
export const MAX_CONVERSATION_PREFERENCE_IDEMPOTENCY_KEY_UTF8_BYTES = 255;
const MAX_SAFE_INTEGER = 9007199254740991;
const ISO_TIMESTAMP_PATTERN =
  /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;
const SERVER_DERIVED_FIELDS = new Set([
  "tenant",
  "tenantid",
  "organization",
  "organizationid",
  "actor",
  "actorid",
  "actorcontext",
  "actoruserid",
  "currentactor",
  "currentactorid",
  "currentuser",
  "currentuserid",
  "user",
  "userid",
  "principal",
  "principalid",
  "subject",
  "subjectid",
  "authenticateduser",
  "authenticateduserid",
  "identity",
  "session",
  "sessionid",
  "auth",
  "authentication",
  "authorization",
  "role",
  "roles",
  "capability",
  "capabilities",
  "permission",
  "permissions",
]);

/** Compile-time guard for identity and authorization resolved by the server. */
export interface NoTrustedConversationPreferenceMutationContext {
  readonly tenant?: never;
  readonly tenantId?: never;
  readonly organization?: never;
  readonly organizationId?: never;
  readonly actor?: never;
  readonly actorId?: never;
  readonly actorContext?: never;
  readonly actorUserId?: never;
  readonly currentActor?: never;
  readonly currentActorId?: never;
  readonly currentUser?: never;
  readonly currentUserId?: never;
  readonly user?: never;
  readonly userId?: never;
  readonly principal?: never;
  readonly principalId?: never;
  readonly subject?: never;
  readonly subjectId?: never;
  readonly authenticatedUser?: never;
  readonly authenticatedUserId?: never;
  readonly identity?: never;
  readonly session?: never;
  readonly sessionId?: never;
  readonly auth?: never;
  readonly authentication?: never;
  readonly authorization?: never;
  readonly role?: never;
  readonly roles?: never;
  readonly capability?: never;
  readonly capabilities?: never;
  readonly permission?: never;
  readonly permissions?: never;
}

/** Explicit desired values; boolean toggle semantics are deliberately absent. */
export interface ConversationPreferenceDesiredState {
  readonly notificationPreference: ConversationNotificationPreference;
  readonly isStarred: boolean;
  readonly mute: ConversationMuteState;
}

/** Retry-safe update for the trusted current user's private preference state. */
export interface UpdateConversationPreferenceInput
  extends NoTrustedConversationPreferenceMutationContext,
    ConversationPreferenceDesiredState {
  readonly operation: "update_conversation_preference";
  readonly conversationId: ConversationId;
  /** Zero means the caller has not observed a persisted preference yet. */
  readonly expectedPreferenceRevision: number;
  readonly idempotencyKey: string;
}

/** Canonical private state for the affected user; identity comes from delivery context. */
export interface CanonicalConversationPreferenceState
  extends ConversationPreferenceDesiredState {
  readonly updatedAt: IsoTimestamp;
}

export type ConversationPreferenceMutationReconciliationStatus =
  | "applied"
  | "replayed"
  | "already_requested_state"
  | "preference_revision_conflict";;

interface ConversationPreferenceMutationResultBase<
  Status extends ConversationPreferenceMutationReconciliationStatus,
> {
  readonly operation: "update_conversation_preference";
  readonly reconciliationStatus: Status;
  readonly conversationId: ConversationId;
  readonly expectedPreferenceRevision: number;
  readonly idempotencyKey: string;
  readonly requestedPreference: ConversationPreferenceDesiredState;
  readonly preferenceRevision: number;
  readonly preference: CanonicalConversationPreferenceState;
}

export type SettledConversationPreferenceMutationResult =
  ConversationPreferenceMutationResultBase<
    "applied" | "replayed" | "already_requested_state"
  >;
export type ConflictingConversationPreferenceMutationResult =
  ConversationPreferenceMutationResultBase<"preference_revision_conflict">;
export type UpdateConversationPreferenceResult =
  | SettledConversationPreferenceMutationResult
  | ConflictingConversationPreferenceMutationResult;

export type ConversationPreferenceMutationParseErrorCode =
  | "malformed_input"
  | "trusted_identity_field"
  | "malformed_identifier"
  | "malformed_revision"
  | "malformed_preference"
  | "malformed_timestamp"
  | "malformed_result"
  | "incoherent_result";

export class ConversationPreferenceMutationParseError extends Error {
  readonly code: ConversationPreferenceMutationParseErrorCode;
  constructor(code: ConversationPreferenceMutationParseErrorCode, message: string) {
    super(message);
    this.name = "ConversationPreferenceMutationParseError";
    this.code = code;
  }
}

const INPUT_KEYS = ["operation", "conversationId", "expectedPreferenceRevision", "idempotencyKey", "notificationPreference", "isStarred", "mute"] as const;
const RESULT_KEYS = ["operation", "reconciliationStatus", "conversationId", "expectedPreferenceRevision", "idempotencyKey", "requestedPreference", "preferenceRevision", "preference"] as const;

export function parseUpdateConversationPreferenceInput(
  value: unknown,
): UpdateConversationPreferenceInput {
  rejectServerDerivedFields(value);
  const input = record(value, "input", "malformed_input");
  exactKeys(input, INPUT_KEYS, "input", "malformed_input");
  if (input.operation !== "update_conversation_preference") {
    throw error("malformed_input", "input.operation must be update_conversation_preference; toggle semantics are not supported");
  }
  return {
    operation: "update_conversation_preference",
    conversationId: identifier(input.conversationId, "input.conversationId") as ConversationId,
    expectedPreferenceRevision: expectedRevision(input.expectedPreferenceRevision, "input.expectedPreferenceRevision"),
    idempotencyKey: idempotency(input.idempotencyKey, "input.idempotencyKey", "malformed_input"),
    ...desired(input, "input", "malformed_preference"),
  };
}

export function parseUpdateConversationPreferenceResult(
  value: unknown,
  expectedInput: UpdateConversationPreferenceInput,
): UpdateConversationPreferenceResult {
  const request = parseUpdateConversationPreferenceInput(expectedInput);
  const result = record(value, "result", "malformed_result");
  exactKeys(result, RESULT_KEYS, "result", "malformed_result");
  if (result.operation !== "update_conversation_preference") {
    throw error("malformed_result", "result.operation must be update_conversation_preference");
  }
  const reconciliationStatus = status(result.reconciliationStatus);
  const conversationId = identifier(result.conversationId, "result.conversationId") as ConversationId;
  const expectedPreferenceRevision = expectedRevision(result.expectedPreferenceRevision, "result.expectedPreferenceRevision");
  const idempotencyKey = idempotency(result.idempotencyKey, "result.idempotencyKey", "malformed_result");
  const requestedPreference = desired(result.requestedPreference, "result.requestedPreference", "malformed_result");
  const preferenceRevision = canonicalRevision(result.preferenceRevision);
  const preference = canonical(result.preference);
  if (
    conversationId !== request.conversationId ||
    expectedPreferenceRevision !== request.expectedPreferenceRevision ||
    idempotencyKey !== request.idempotencyKey ||
    !samePreference(request, requestedPreference)
  ) {
    throw error("incoherent_result", "result request echoes must exactly match conversationId, expectedPreferenceRevision, idempotencyKey, and requested preference");
  }
  const canonicalMatches = samePreference(request, preference);
  if (reconciliationStatus === "applied" || reconciliationStatus === "replayed") {
    if (preferenceRevision !== expectedPreferenceRevision + 1 || !canonicalMatches) {
      throw error("incoherent_result", `${reconciliationStatus} results must advance by one and carry the requested preference`);
    }
  } else if (reconciliationStatus === "already_requested_state") {
    if (preferenceRevision !== expectedPreferenceRevision || !canonicalMatches) {
      throw error("incoherent_result", "already-requested-state results must preserve the revision and requested preference");
    }
  } else if (preferenceRevision === expectedPreferenceRevision) {
    throw error("incoherent_result", "a preference revision conflict must carry a different authoritative revision");
  }
  return {
    operation: "update_conversation_preference",
    reconciliationStatus,
    conversationId,
    expectedPreferenceRevision,
    idempotencyKey,
    requestedPreference,
    preferenceRevision,
    preference,
  };
}

function desired(
  value: unknown,
  path: string,
  code: "malformed_preference" | "malformed_result",
): ConversationPreferenceDesiredState {
  const object = record(value, path, code);
  if (path !== "input") exactKeys(object, ["notificationPreference", "isStarred", "mute"], path, code);
  return {
    notificationPreference: notification(object.notificationPreference, `${path}.notificationPreference`, code),
    isStarred: starred(object.isStarred, `${path}.isStarred`, code),
    mute: mute(object.mute, `${path}.mute`, code),
  };
}

function canonical(value: unknown): CanonicalConversationPreferenceState {
  const object = record(value, "result.preference", "malformed_result");
  exactKeys(object, ["notificationPreference", "isStarred", "mute", "updatedAt"], "result.preference", "malformed_result");
  return {
    ...desired({ notificationPreference: object.notificationPreference, isStarred: object.isStarred, mute: object.mute }, "result.preference", "malformed_result"),
    updatedAt: timestamp(object.updatedAt, "result.preference.updatedAt", "malformed_result"),
  };
}

function starred(
  value: unknown,
  path: string,
  code: "malformed_preference" | "malformed_result",
): boolean {
  if (typeof value !== "boolean") throw error(code, `${path} must be boolean`);
  return value;
}

function mute(
  value: unknown,
  path: string,
  code: "malformed_preference" | "malformed_result",
): ConversationMuteState {
  const object = record(value, path, code);
  if (object.muted === false) {
    exactKeys(object, ["muted"], path, code);
    return { muted: false };
  }
  if (object.muted === true) {
    if (object.mutedUntil === undefined) {
      exactKeys(object, ["muted"], path, code);
      return { muted: true };
    }
    exactKeys(object, ["muted", "mutedUntil"], path, code);
    return { muted: true, mutedUntil: timestamp(object.mutedUntil, `${path}.mutedUntil`, code) };
  }
  throw error(code, `${path}.muted must be boolean`);
}

function notification(
  value: unknown,
  path: string,
  code: "malformed_preference" | "malformed_result",
): ConversationNotificationPreference {
  if (value !== "all" && value !== "mentions" && value !== "none") {
    throw error(code, `${path} must be all, mentions, or none`);
  }
  return value;
}

function status(value: unknown): ConversationPreferenceMutationReconciliationStatus {
  if (value !== "applied" && value !== "replayed" && value !== "already_requested_state" && value !== "preference_revision_conflict") {
    throw error("malformed_result", "result.reconciliationStatus is not supported");
  }
  return value;
}

function expectedRevision(value: unknown, path: string): number {
  if (!Number.isSafeInteger(value) || (value as number) < 0 || (value as number) >= MAX_SAFE_INTEGER) {
    throw error("malformed_revision", `${path} must be a nonnegative safe integer that can advance by one`);
  }
  return value as number;
}

function canonicalRevision(value: unknown): number {
  if (!Number.isSafeInteger(value) || (value as number) < 0) {
    throw error("malformed_revision", "result.preferenceRevision must be a nonnegative safe integer");
  }
  return value as number;
}

function identifier(value: unknown, path: string): string {
  if (typeof value !== "string" || value.length === 0 || value.trim() !== value || value !== value.normalize("NFC") || unsafe(value) || utf8(value) > MAX_CONVERSATION_PREFERENCE_IDENTIFIER_UTF8_BYTES) {
    throw error("malformed_identifier", `${path} must be a safe, NFC-normalized identifier of at most ${MAX_CONVERSATION_PREFERENCE_IDENTIFIER_UTF8_BYTES} UTF-8 bytes`);
  }
  return value;
}

function idempotency(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): string {
  if (typeof value !== "string" || value.trim().length === 0 || value.trim() !== value || value !== value.normalize("NFC") || unsafe(value) || utf8(value) > MAX_CONVERSATION_PREFERENCE_IDEMPOTENCY_KEY_UTF8_BYTES) {
    throw error(code, `${path} must be a safe, NFC-normalized nonblank string of at most ${MAX_CONVERSATION_PREFERENCE_IDEMPOTENCY_KEY_UTF8_BYTES} UTF-8 bytes`);
  }
  return value;
}

function timestamp(
  value: unknown,
  path: string,
  code: "malformed_preference" | "malformed_result",
): IsoTimestamp {
  if (typeof value !== "string" || !finiteTimestamp(value)) {
    throw error(code === "malformed_preference" ? "malformed_timestamp" : code, `${path} must be a finite ISO-8601 timestamp`);
  }
  return value;
}

function finiteTimestamp(value: string): boolean {
  const match = ISO_TIMESTAMP_PATTERN.exec(value);
  if (match === null || !Number.isFinite(Date.parse(value))) return false;
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const leap = year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);
  const days = [31, leap ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
  return month >= 1 && month <= 12 && day >= 1 && day <= (days[month - 1] ?? 0) && Number(match[4]) <= 23 && Number(match[5]) <= 59 && Number(match[6]) <= 59;
}

function samePreference(left: ConversationPreferenceDesiredState, right: ConversationPreferenceDesiredState): boolean {
  return left.notificationPreference === right.notificationPreference &&
    left.isStarred === right.isStarred &&
    left.mute.muted === right.mute.muted &&
    (left.mute.muted === false || (right.mute.muted === true && left.mute.mutedUntil === right.mute.mutedUntil));
}

function rejectServerDerivedFields(value: unknown, path = "input"): void {
  if (Array.isArray(value)) {
    value.forEach((entry, index) => rejectServerDerivedFields(entry, `${path}[${index}]`));
    return;
  }
  if (!isRecord(value)) return;
  for (const [key, nested] of Object.entries(value)) {
    const normalized = key.replaceAll(/[^a-zA-Z0-9]/g, "").toLowerCase();
    if (SERVER_DERIVED_FIELDS.has(normalized)) {
      throw error("trusted_identity_field", `${path}.${key} is server-derived and cannot be supplied by a client`);
    }
    rejectServerDerivedFields(nested, `${path}.${key}`);
  }
}

function exactKeys(
  value: Record<string, unknown>,
  expected: readonly string[],
  path: string,
  code: "malformed_input" | "malformed_preference" | "malformed_result",
): void {
  const actual = Object.keys(value).sort();
  const keys = expected.slice().sort();
  if (actual.length !== keys.length || actual.some((key, index) => key !== keys[index])) {
    throw error(code, `${path} must contain exactly: ${keys.join(", ")}`);
  }
}

function record(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_preference" | "malformed_result",
): Record<string, unknown> {
  if (!isRecord(value)) throw error(code, `${path} must be an object`);
  return value;
}
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function unsafe(value: string): boolean {
  return /[\u0000-\u001F\u007F-\u009F\uD800-\uDFFF]/u.test(value);
}
function utf8(value: string): number {
  return new TextEncoder().encode(value).byteLength;
}
function error(code: ConversationPreferenceMutationParseErrorCode, message: string): ConversationPreferenceMutationParseError {
  return new ConversationPreferenceMutationParseError(code, message);
}
