// Generated by scripts/generate-conversations.mjs from contracts/models/conversation.json.
// Do not edit this file directly.

import type {
  ConversationId,
  IsoTimestamp,
  MessageId,
  TenantId,
  UserId,
} from "./identifiers.js";

export type ConversationType =
  | "channel"
  | "direct"
  | "group_direct"
  | "thread";

export type ConversationVisibility = "public" | "private";

/** An opaque reference to an entity owned and authorized by the host application. */
export interface HostEntityReference {
  readonly type: string;
  readonly id: string;
}

interface ConversationBase {
  readonly id: ConversationId;
  readonly tenantId: TenantId;
  readonly createdAt: IsoTimestamp;
  readonly updatedAt: IsoTimestamp;
}

type ConversationArchiveState =
  | {
      readonly archivedAt?: never;
      readonly archivedByUserId?: never;
    }
  | {
      readonly archivedAt: IsoTimestamp;
      readonly archivedByUserId: UserId;
    };

/** Shared thread close/lock metadata. Absence means legacy open/unlocked and never clears administrative archive. Unlocking leaves the closure pair intact. Hiding is computed discovery policy, not stored state. */
export type ThreadLifecycle = { readonly revision: number } & (
  | {
      readonly locked: false;
      readonly closedAt?: never;
      readonly closedByUserId?: never;
    }
  | {
      readonly locked: boolean;
      readonly closedAt: IsoTimestamp;
      readonly closedByUserId: UserId;
    }
);

/** Validate supplied lifecycle metadata. Absence is handled at conversation level. */
export function validateThreadLifecycle(value: unknown): ThreadLifecycle {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new TypeError("ThreadLifecycle must be a JSON object.");
  }
  const object = value as Record<string, unknown>;
  const allowed = new Set(["revision", "locked", "closedAt", "closedByUserId"]);
  if (Object.keys(object).some((key) => !allowed.has(key))) {
    throw new TypeError("ThreadLifecycle contains an unknown field.");
  }
  const has = (key: string) => Object.prototype.hasOwnProperty.call(object, key);
  const revision = object.revision;
  if (!has("revision") || typeof revision !== "number" ||
      !Number.isSafeInteger(revision) || revision < 1 || revision > 9007199254740991) {
    throw new TypeError("ThreadLifecycle.revision must be a positive safe integer.");
  }
  if (!has("locked") || typeof object.locked !== "boolean") {
    throw new TypeError("ThreadLifecycle.locked must be a boolean.");
  }
  const hasClosedAt = has("closedAt");
  if (hasClosedAt !== has("closedByUserId")) {
    throw new TypeError("ThreadLifecycle.closedAt and closedByUserId must be provided together.");
  }
  if (!hasClosedAt) {
    if (object.locked) throw new TypeError("A locked thread must be closed.");
    return { revision, locked: false };
  }
  // Match the canonical identifier/timestamp wire convention: string values.
  if (typeof object.closedAt !== "string" || typeof object.closedByUserId !== "string") {
    throw new TypeError("ThreadLifecycle closure fields must be strings.");
  }
  return {
    revision,
    locked: object.locked,
    closedAt: object.closedAt as IsoTimestamp,
    closedByUserId: object.closedByUserId as UserId,
  };
}

/** Validate only the conversation's lifecycle field; does not parse a snapshot.
 * Preserve absence instead of materializing an open state or changing archive.
 */
export function validateConversationThreadLifecycle(conversation: {
  readonly type: ConversationType;
  readonly threadLifecycle?: unknown;
}): ThreadLifecycle | undefined {
  if (!Object.prototype.hasOwnProperty.call(conversation, "threadLifecycle")) return undefined;
  if (conversation.type !== "thread") {
    throw new TypeError("threadLifecycle is only allowed on thread conversations.");
  }
  return validateThreadLifecycle(conversation.threadLifecycle);
}


/** A named public or private channel, optionally attached to a host entity. */
export type ChannelConversation = ConversationBase &
  ConversationArchiveState & {
    readonly type: "channel";
    readonly threadLifecycle?: never;
    readonly name: string;
    readonly visibility: ConversationVisibility;
    readonly entity?: HostEntityReference;
    readonly parentConversationId?: never;
    readonly rootMessageId?: never;
  };

/** A private one-to-one conversation. Membership is modeled separately. */
export type DirectConversation = ConversationBase &
  ConversationArchiveState & {
    readonly type: "direct";
    readonly threadLifecycle?: never;
    readonly visibility: "private";
    readonly name?: never;
    readonly entity?: never;
    readonly parentConversationId?: never;
    readonly rootMessageId?: never;
  };

/** A private multi-person direct conversation. Membership is modeled separately. */
export type GroupDirectConversation = ConversationBase &
  ConversationArchiveState & {
    readonly type: "group_direct";
    readonly threadLifecycle?: never;
    readonly visibility: "private";
    readonly name?: never;
    readonly entity?: never;
    readonly parentConversationId?: never;
    readonly rootMessageId?: never;
  };

/** A standalone reply stream rooted in a message from its parent conversation. */
export type ThreadConversation = ConversationBase &
  ConversationArchiveState & {
    readonly type: "thread";
    readonly threadLifecycle?: ThreadLifecycle;
    readonly visibility: ConversationVisibility;
    readonly parentConversationId: ConversationId;
    readonly rootMessageId: MessageId;
    readonly name?: string;
    readonly entity?: never;
  };

export type Conversation =
  | ChannelConversation
  | DirectConversation
  | GroupDirectConversation
  | ThreadConversation;

/**
 * Validate a supplied canonical thread name; absence is handled by the caller.
 * Reject untrimmed input; never normalize it. Count Unicode scalar values,
 * not UTF-16 units or grapheme clusters; reject unpaired surrogates.
 * Whitespace is Unicode White_Space plus U+FEFF, frozen in the descriptor.
 */
export function validateThreadConversationName(value: unknown): string {
  if (typeof value !== "string") {
    throw new TypeError("ThreadConversation.name must be a string.");
  }
  const characters = Array.from(value);
  const whitespace = new Set<number>([9,10,11,12,13,32,133,160,5760,8192,8193,8194,8195,8196,8197,8198,8199,8200,8201,8202,8232,8233,8239,8287,12288,65279]);
  if (
    characters.length < 1 || characters.length > 100 ||
    characters.some((character) => {
      const point = character.codePointAt(0)!;
      return point >= 0xd800 && point <= 0xdfff;
    }) ||
    whitespace.has(characters[0]!.codePointAt(0)!) ||
    whitespace.has(characters[characters.length - 1]!.codePointAt(0)!)
  ) {
    throw new TypeError("ThreadConversation.name must be trimmed and contain 1–100 Unicode scalar values.");
  }
  return value;
}
