// Generated by scripts/generate-conversation-archive.mjs from contracts/http/conversation-archive.json.
// Do not edit this file directly.

import type {
  ConversationId,
  IsoTimestamp,
  UserId,
} from "./identifiers.js";

const ISO_TIMESTAMP_PATTERN =
  /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/;

const SERVER_DERIVED_FIELDS = new Set([
  "tenant",
  "tenantid",
  "organization",
  "organizationid",
  "actor",
  "actorid",
  "actorcontext",
  "actoruserid",
  "currentactor",
  "currentactorid",
  "currentuser",
  "currentuserid",
  "user",
  "userid",
  "principal",
  "principalid",
  "subject",
  "subjectid",
  "authenticateduser",
  "authenticateduserid",
  "identity",
  "session",
  "sessionid",
  "auth",
  "authorization",
  "role",
  "roles",
  "capability",
  "capabilities",
  "permission",
  "permissions",
  "entity",
  "entityid",
  "entitytype",
  "hostentity",
  "hostentityid",
  "hostentitytype",
  "hostentityauthorization",
]);

/** Compile-time guard for identity and authorization resolved by the server. */
export interface NoTrustedConversationArchiveContext {
  readonly tenant?: never;
  readonly tenantId?: never;
  readonly organization?: never;
  readonly organizationId?: never;
  readonly actor?: never;
  readonly actorId?: never;
  readonly actorContext?: never;
  readonly actorUserId?: never;
  readonly currentActor?: never;
  readonly currentActorId?: never;
  readonly currentUser?: never;
  readonly currentUserId?: never;
  readonly user?: never;
  readonly userId?: never;
  readonly principal?: never;
  readonly principalId?: never;
  readonly subject?: never;
  readonly subjectId?: never;
  readonly authenticatedUser?: never;
  readonly authenticatedUserId?: never;
  readonly identity?: never;
  readonly session?: never;
  readonly sessionId?: never;
  readonly auth?: never;
  readonly authorization?: never;
  readonly role?: never;
  readonly roles?: never;
  readonly capability?: never;
  readonly capabilities?: never;
  readonly permission?: never;
  readonly permissions?: never;
  readonly entity?: never;
  readonly entityId?: never;
  readonly entityType?: never;
  readonly hostEntity?: never;
  readonly hostEntityId?: never;
  readonly hostEntityType?: never;
  readonly hostEntityAuthorization?: never;
}

export type ConversationArchiveIntent = "archive" | "restore";

interface ConversationArchiveInputBase<
  Intent extends ConversationArchiveIntent,
> extends NoTrustedConversationArchiveContext {
  readonly operation: "set_conversation_archive";
  readonly intent: Intent;
  readonly conversationId: ConversationId;
  readonly expectedLifecycleRevision: number;
  readonly idempotencyKey: string;
}

/** Explicitly requests that an active conversation become archived. */
export type ArchiveConversationInput = ConversationArchiveInputBase<"archive">;

/** Explicitly requests that an archived conversation become active. */
export type RestoreConversationInput = ConversationArchiveInputBase<"restore">;

export type ConversationArchiveInput =
  | ArchiveConversationInput
  | RestoreConversationInput;

export interface ActiveConversationArchiveState {
  readonly status: "active";
  readonly archivedAt?: never;
  readonly archivedByUserId?: never;
}

export interface ArchivedConversationArchiveState {
  readonly status: "archived";
  readonly archivedAt: IsoTimestamp;
  /** Always derived from the trusted server actor, never from caller input. */
  readonly archivedByUserId: UserId;
}

export type ConversationArchiveState =
  | ActiveConversationArchiveState
  | ArchivedConversationArchiveState;

export type ConversationArchiveReconciliationStatus =
  | "applied"
  | "replayed"
  | "already_requested_state"
  | "lifecycle_conflict";

type RequestedArchiveState<Intent extends ConversationArchiveIntent> =
  Intent extends "archive"
    ? ArchivedConversationArchiveState
    : ActiveConversationArchiveState;

type ConflictingArchiveState<Intent extends ConversationArchiveIntent> =
  Intent extends "archive"
    ? ActiveConversationArchiveState
    : ArchivedConversationArchiveState;

interface ConversationArchiveResultBase<
  Intent extends ConversationArchiveIntent,
  Status extends ConversationArchiveReconciliationStatus,
  State extends ConversationArchiveState,
> {
  readonly operation: "set_conversation_archive";
  readonly intent: Intent;
  readonly reconciliationStatus: Status;
  readonly conversationId: ConversationId;
  /** Exact echo of the caller's optimistic-concurrency revision. */
  readonly expectedLifecycleRevision: number;
  /** Current authoritative lifecycle revision for deterministic reconciliation. */
  readonly lifecycleRevision: number;
  readonly archiveState: State;
}

type ConversationArchiveSettledResult<
  Intent extends ConversationArchiveIntent,
> = ConversationArchiveResultBase<
  Intent,
  "applied" | "replayed" | "already_requested_state",
  RequestedArchiveState<Intent>
>;

type ConversationArchiveConflictResult<
  Intent extends ConversationArchiveIntent,
> = ConversationArchiveResultBase<
  Intent,
  "lifecycle_conflict",
  ConflictingArchiveState<Intent>
>;

export type ArchiveConversationResult =
  | ConversationArchiveSettledResult<"archive">
  | ConversationArchiveConflictResult<"archive">;

export type RestoreConversationResult =
  | ConversationArchiveSettledResult<"restore">
  | ConversationArchiveConflictResult<"restore">;

export type ConversationArchiveResult =
  | ArchiveConversationResult
  | RestoreConversationResult;

export type ConversationArchiveParseErrorCode =
  | "malformed_input"
  | "trusted_identity_field"
  | "malformed_result"
  | "incoherent_result";

export class ConversationArchiveParseError extends Error {
  readonly code: ConversationArchiveParseErrorCode;

  constructor(code: ConversationArchiveParseErrorCode, message: string) {
    super(message);
    this.name = "ConversationArchiveParseError";
    this.code = code;
  }
}

const INPUT_KEYS = [
  "operation",
  "intent",
  "conversationId",
  "expectedLifecycleRevision",
  "idempotencyKey",
] as const;

const RESULT_KEYS = [
  "operation",
  "intent",
  "reconciliationStatus",
  "conversationId",
  "expectedLifecycleRevision",
  "lifecycleRevision",
  "archiveState",
] as const;

export function parseConversationArchiveInput(
  value: unknown,
): ConversationArchiveInput {
  rejectServerDerivedFields(value);
  const input = requireRecord(value, "input", "malformed_input");
  assertExactKeys(input, INPUT_KEYS, "input", "malformed_input");

  if (input.operation !== "set_conversation_archive") {
    throw archiveError(
      "malformed_input",
      "input.operation must be set_conversation_archive",
    );
  }

  return {
    operation: "set_conversation_archive",
    intent: readIntent(input.intent, "malformed_input"),
    conversationId: readNonBlankString(
      input.conversationId,
      "input.conversationId",
      "malformed_input",
    ) as ConversationId,
    expectedLifecycleRevision: readPositiveSafeInteger(
      input.expectedLifecycleRevision,
      "input.expectedLifecycleRevision",
      "malformed_input",
    ),
    idempotencyKey: readNonBlankString(
      input.idempotencyKey,
      "input.idempotencyKey",
      "malformed_input",
    ),
  };
}

/** Parses an authoritative result and reconciles it with its exact request. */
export function parseConversationArchiveResult(
  value: unknown,
  expectedInput: ConversationArchiveInput,
): ConversationArchiveResult {
  const request = parseConversationArchiveInput(expectedInput);
  const result = requireRecord(value, "result", "malformed_result");
  assertExactKeys(result, RESULT_KEYS, "result", "malformed_result");

  if (result.operation !== "set_conversation_archive") {
    throw archiveError(
      "malformed_result",
      "result.operation must be set_conversation_archive",
    );
  }

  const intent = readIntent(result.intent, "malformed_result");
  const reconciliationStatus = readReconciliationStatus(
    result.reconciliationStatus,
  );
  const conversationId = readNonBlankString(
    result.conversationId,
    "result.conversationId",
    "malformed_result",
  ) as ConversationId;
  const expectedLifecycleRevision = readPositiveSafeInteger(
    result.expectedLifecycleRevision,
    "result.expectedLifecycleRevision",
    "malformed_result",
  );
  const lifecycleRevision = readPositiveSafeInteger(
    result.lifecycleRevision,
    "result.lifecycleRevision",
    "malformed_result",
  );
  const archiveState = parseArchiveState(result.archiveState);

  if (
    intent !== request.intent ||
    conversationId !== request.conversationId ||
    expectedLifecycleRevision !== request.expectedLifecycleRevision
  ) {
    throw archiveError(
      "incoherent_result",
      "result intent, conversationId, and expectedLifecycleRevision must match the request",
    );
  }

  validateResultCoherence(
    intent,
    reconciliationStatus,
    expectedLifecycleRevision,
    lifecycleRevision,
    archiveState,
  );

  return {
    operation: "set_conversation_archive",
    intent,
    reconciliationStatus,
    conversationId,
    expectedLifecycleRevision,
    lifecycleRevision,
    archiveState,
  } as ConversationArchiveResult;
}

function validateResultCoherence(
  intent: ConversationArchiveIntent,
  reconciliationStatus: ConversationArchiveReconciliationStatus,
  expectedLifecycleRevision: number,
  lifecycleRevision: number,
  archiveState: ConversationArchiveState,
): void {
  const requestedStatus = intent === "archive" ? "archived" : "active";
  const stateMatchesIntent = archiveState.status === requestedStatus;

  if (reconciliationStatus === "lifecycle_conflict") {
    if (stateMatchesIntent) {
      throw archiveError(
        "incoherent_result",
        "a lifecycle conflict must carry authoritative state that differs from the requested intent",
      );
    }
    if (lifecycleRevision === expectedLifecycleRevision) {
      throw archiveError(
        "incoherent_result",
        "a lifecycle conflict must carry a lifecycle revision different from the expected revision",
      );
    }
    return;
  }

  if (!stateMatchesIntent) {
    throw archiveError(
      "incoherent_result",
      "a settled result must carry authoritative state matching the requested intent",
    );
  }
  if (
    reconciliationStatus === "applied" &&
    lifecycleRevision !== expectedLifecycleRevision + 1
  ) {
    throw archiveError(
      "incoherent_result",
      "an applied result must advance expectedLifecycleRevision by one",
    );
  }
}

function parseArchiveState(value: unknown): ConversationArchiveState {
  const state = requireRecord(
    value,
    "result.archiveState",
    "malformed_result",
  );

  if (state.status === "active") {
    assertExactKeys(
      state,
      ["status"],
      "result.archiveState",
      "malformed_result",
    );
    return { status: "active" };
  }
  if (state.status === "archived") {
    assertExactKeys(
      state,
      ["status", "archivedAt", "archivedByUserId"],
      "result.archiveState",
      "malformed_result",
    );
    return {
      status: "archived",
      archivedAt: readIsoTimestamp(
        state.archivedAt,
        "result.archiveState.archivedAt",
      ),
      archivedByUserId: readNonBlankString(
        state.archivedByUserId,
        "result.archiveState.archivedByUserId",
        "malformed_result",
      ) as UserId,
    };
  }

  throw archiveError(
    "malformed_result",
    "result.archiveState.status must be active or archived",
  );
}

function readIntent(
  value: unknown,
  code: "malformed_input" | "malformed_result",
): ConversationArchiveIntent {
  if (value !== "archive" && value !== "restore") {
    throw archiveError(code, "intent must be archive or restore");
  }
  return value;
}

function readReconciliationStatus(
  value: unknown,
): ConversationArchiveReconciliationStatus {
  if (
    value !== "applied" &&
    value !== "replayed" &&
    value !== "already_requested_state" &&
    value !== "lifecycle_conflict"
  ) {
    throw archiveError(
      "malformed_result",
      "result.reconciliationStatus must be applied, replayed, already_requested_state, or lifecycle_conflict",
    );
  }
  return value;
}

function rejectServerDerivedFields(value: unknown, path = "input"): void {
  if (Array.isArray(value)) {
    value.forEach((entry, index) =>
      rejectServerDerivedFields(entry, path + "[" + index + "]"),
    );
    return;
  }
  if (!isRecord(value)) return;

  for (const [key, nested] of Object.entries(value)) {
    const normalizedKey = key.replaceAll(/[^a-zA-Z0-9]/g, "").toLowerCase();
    if (SERVER_DERIVED_FIELDS.has(normalizedKey)) {
      throw archiveError(
        "trusted_identity_field",
        path + "." + key + " is server-derived and cannot be supplied by a client",
      );
    }
    rejectServerDerivedFields(nested, path + "." + key);
  }
}

function assertExactKeys(
  value: Record<string, unknown>,
  expected: readonly string[],
  path: string,
  code: "malformed_input" | "malformed_result",
): void {
  const expectedSet = new Set(expected);
  for (const key of Object.keys(value)) {
    if (!expectedSet.has(key)) {
      throw archiveError(code, path + "." + key + " is not supported");
    }
  }
  for (const key of expected) {
    if (!Object.hasOwn(value, key)) {
      throw archiveError(code, path + "." + key + " is required");
    }
  }
}

function requireRecord(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): Record<string, unknown> {
  if (!isRecord(value)) {
    throw archiveError(code, path + " must be an object");
  }
  return value;
}

function readNonBlankString(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw archiveError(code, path + " must be a nonblank string");
  }
  return value;
}

function readPositiveSafeInteger(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): number {
  if (!Number.isSafeInteger(value) || (value as number) < 1) {
    throw archiveError(code, path + " must be a positive safe integer");
  }
  return value as number;
}

function readIsoTimestamp(value: unknown, path: string): IsoTimestamp {
  if (
    typeof value !== "string" ||
    !ISO_TIMESTAMP_PATTERN.test(value) ||
    !Number.isFinite(Date.parse(value))
  ) {
    throw archiveError(
      "malformed_result",
      path + " must be an ISO-8601 timestamp",
    );
  }
  return value;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function archiveError(
  code: ConversationArchiveParseErrorCode,
  message: string,
): ConversationArchiveParseError {
  return new ConversationArchiveParseError(code, message);
}
