// Generated by scripts/generate-device-push-token.mjs from contracts/http/device-push-token.json.
// Do not edit this file directly.

import type { DeviceId, IsoTimestamp } from "./identifiers.js";

export const DEVICE_PUSH_TOKEN_METHOD = "PUT" as const;
export const DEVICE_PUSH_TOKEN_PATH = "/devices/:deviceId/push-token" as const;
export const MAX_DEVICE_PUSH_TOKEN_UTF8_BYTES = 4_096;
export const MIN_DEVICE_PUSH_TOKEN_REVISION = 1;
export const MAX_DEVICE_PUSH_TOKEN_REVISION = 2_147_483_647;
export const MAX_DEVICE_PUSH_TOKEN_IDEMPOTENCY_KEY_UTF8_BYTES = 255;
export const DEVICE_PUSH_TOKEN_REDACTION = "[REDACTED]" as const;

export type DevicePushTokenOperation = "register" | "refresh" | "unregister";
export type DevicePushProvider = "apns" | "fcm";
export type DevicePlatform = "ios" | "android";
export type DevicePushProviderEnvironment = "sandbox" | "production";
export type DevicePushTokenStatus = "active" | "unregistered";
export type DevicePushTokenReconciliationStatus = "applied" | "replayed";

declare const opaquePushTokenBrand: unique symbol;
/** An opaque provider credential. Inspect it only through the redaction helpers. */
export type OpaquePushToken = string & { readonly [opaquePushTokenBrand]: true };

export interface NoTrustedDevicePushTokenIdentity {
  readonly tenant?: never;
  readonly tenantId?: never;
  readonly organization?: never;
  readonly organizationId?: never;
  readonly org?: never;
  readonly orgId?: never;
  readonly actor?: never;
  readonly actorId?: never;
  readonly actorContext?: never;
  readonly actorUserId?: never;
  readonly currentActor?: never;
  readonly currentActorId?: never;
  readonly currentUser?: never;
  readonly currentUserId?: never;
  readonly user?: never;
  readonly userId?: never;
  readonly member?: never;
  readonly memberId?: never;
  readonly principal?: never;
  readonly principalId?: never;
  readonly subject?: never;
  readonly subjectId?: never;
  readonly authenticatedUser?: never;
  readonly authenticatedUserId?: never;
  readonly identity?: never;
  readonly session?: never;
  readonly sessionId?: never;
  readonly auth?: never;
  readonly authentication?: never;
  readonly authorization?: never;
  readonly role?: never;
  readonly roles?: never;
  readonly permission?: never;
  readonly permissions?: never;
  readonly capability?: never;
  readonly capabilities?: never;
}

interface TokenBearingInput extends NoTrustedDevicePushTokenIdentity {
  readonly deviceId: DeviceId;
  readonly platform: DevicePlatform;
  readonly provider: DevicePushProvider;
  readonly environment: DevicePushProviderEnvironment;
  readonly token: OpaquePushToken;
  readonly tokenRevision: number;
  readonly idempotencyKey: string;
}

export interface RegisterDevicePushTokenInput extends TokenBearingInput {
  readonly operation: "register";
}

export interface RefreshDevicePushTokenInput extends TokenBearingInput {
  readonly operation: "refresh";
}

export interface UnregisterDevicePushTokenInput extends NoTrustedDevicePushTokenIdentity {
  readonly operation: "unregister";
  readonly intent: "unregister";
  readonly deviceId: DeviceId;
  readonly tokenRevision: number;
  readonly idempotencyKey: string;
}

export type DevicePushTokenInput =
  | RegisterDevicePushTokenInput
  | RefreshDevicePushTokenInput
  | UnregisterDevicePushTokenInput;

/** Canonical token state authored by the server. It deliberately excludes the opaque token. */
export interface CanonicalDevicePushTokenState {
  readonly deviceId: DeviceId;
  readonly status: DevicePushTokenStatus;
  readonly platform: DevicePlatform;
  readonly provider: DevicePushProvider;
  readonly environment: DevicePushProviderEnvironment;
  readonly tokenRevision: number;
  readonly updatedAt: IsoTimestamp;
}

export interface DevicePushTokenResult {
  readonly operation: DevicePushTokenOperation;
  readonly reconciliationStatus: DevicePushTokenReconciliationStatus;
  readonly idempotencyKey: string;
  readonly devicePushToken: CanonicalDevicePushTokenState;
}

export interface DevicePushTokenParseOptions {
  /** When supplied, the incoming revision must be strictly greater. */
  readonly currentTokenRevision?: number;
}

export type DevicePushTokenParseErrorCode =
  | "malformed_input"
  | "malformed_result"
  | "trusted_identity_field"
  | "invalid_provider_target"
  | "invalid_token"
  | "invalid_revision"
  | "revision_not_monotonic"
  | "invalid_idempotency_key"
  | "result_mismatch";

export class DevicePushTokenContractError extends Error {
  readonly code: DevicePushTokenParseErrorCode;

  constructor(
    code: DevicePushTokenParseErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "DevicePushTokenContractError";
    this.code = code;
  }
}

const TRUSTED_IDENTITY_FIELDS = new Set([
  "tenant",
  "tenantid",
  "organization",
  "organizationid",
  "org",
  "orgid",
  "actor",
  "actorid",
  "actorcontext",
  "actoruserid",
  "currentactor",
  "currentactorid",
  "currentuser",
  "currentuserid",
  "user",
  "userid",
  "member",
  "memberid",
  "principal",
  "principalid",
  "subject",
  "subjectid",
  "authenticateduser",
  "authenticateduserid",
  "identity",
  "session",
  "sessionid",
  "auth",
  "authentication",
  "authorization",
  "role",
  "roles",
  "permission",
  "permissions",
  "capability",
  "capabilities",
]);

const TOKEN_FIELDS = new Set([
  "token",
  "pushtoken",
  "devicetoken",
  "registrationtoken",
  "opaquetoken",
]);

export function parseDevicePushTokenInput(
  value: unknown,
  options: DevicePushTokenParseOptions = {},
): DevicePushTokenInput {
  rejectTrustedIdentityFields(value);
  const input = record(value, "input", "malformed_input");
  const operation = readOperation(input.operation, "malformed_input");
  const deviceId = nonBlank(input.deviceId, "input.deviceId", "malformed_input") as DeviceId;
  const tokenRevision = revision(input.tokenRevision, "input.tokenRevision", "malformed_input");
  assertMonotonicRevision(tokenRevision, options.currentTokenRevision);
  const idempotencyKey = boundedNonBlank(
    input.idempotencyKey,
    "input.idempotencyKey",
    MAX_DEVICE_PUSH_TOKEN_IDEMPOTENCY_KEY_UTF8_BYTES,
    "invalid_idempotency_key",
  );

  if (operation === "unregister") {
    exact(input, ["operation", "intent", "deviceId", "tokenRevision", "idempotencyKey"], "input", "malformed_input");
    if (input.intent !== "unregister") fail("malformed_input", "input.intent must be unregister");
    return { operation, intent: "unregister", deviceId, tokenRevision, idempotencyKey };
  }

  exact(input, ["operation", "deviceId", "platform", "provider", "environment", "token", "tokenRevision", "idempotencyKey"], "input", "malformed_input");
  const platform = readPlatform(input.platform, "malformed_input");
  const provider = readProvider(input.provider, "malformed_input");
  const environment = readEnvironment(input.environment, "malformed_input");
  assertProviderTarget(platform, provider, environment);
  const token = boundedNonBlank(
    input.token,
    "input.token",
    MAX_DEVICE_PUSH_TOKEN_UTF8_BYTES,
    "invalid_token",
  ) as OpaquePushToken;
  return { operation, deviceId, platform, provider, environment, token, tokenRevision, idempotencyKey };
}

export function parseDevicePushTokenResult(
  value: unknown,
  expectedInput?: DevicePushTokenInput,
): DevicePushTokenResult {
  const result = record(value, "result", "malformed_result");
  exact(result, ["operation", "reconciliationStatus", "idempotencyKey", "devicePushToken"], "result", "malformed_result");
  const operation = readOperation(result.operation, "malformed_result");
  const reconciliationStatus = readReconciliationStatus(result.reconciliationStatus);
  const idempotencyKey = boundedNonBlank(
    result.idempotencyKey,
    "result.idempotencyKey",
    MAX_DEVICE_PUSH_TOKEN_IDEMPOTENCY_KEY_UTF8_BYTES,
    "malformed_result",
  );
  const devicePushToken = parseCanonicalState(result.devicePushToken);
  const expectedStatus = operation === "unregister" ? "unregistered" : "active";
  if (devicePushToken.status !== expectedStatus) fail("result_mismatch", `result status must be ${expectedStatus} for ${operation}`);
  if (expectedInput) assertResultMatchesInput(operation, idempotencyKey, devicePushToken, expectedInput);
  return { operation, reconciliationStatus, idempotencyKey, devicePushToken };
}

export function parseCanonicalDevicePushTokenState(value: unknown): CanonicalDevicePushTokenState {
  return parseCanonicalState(value);
}

/** Returns a recursively copied value with token-named fields structurally redacted. */
export function redactDevicePushTokenDiagnostics(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(redactDevicePushTokenDiagnostics);
  if (!value || typeof value !== "object") return value;
  const output: Record<string, unknown> = {};
  for (const [key, nested] of Object.entries(value)) {
    output[key] = TOKEN_FIELDS.has(normalize(key))
      ? DEVICE_PUSH_TOKEN_REDACTION
      : redactDevicePushTokenDiagnostics(nested);
  }
  return output;
}

/** A diagnostic-only string; use the parsed input itself for wire serialization. */
export function formatDevicePushTokenDiagnostic(value: unknown): string {
  return JSON.stringify(redactDevicePushTokenDiagnostics(value));
}

function parseCanonicalState(value: unknown): CanonicalDevicePushTokenState {
  const state = record(value, "result.devicePushToken", "malformed_result");
  exact(state, ["deviceId", "status", "platform", "provider", "environment", "tokenRevision", "updatedAt"], "result.devicePushToken", "malformed_result");
  const deviceId = nonBlank(state.deviceId, "result.devicePushToken.deviceId", "malformed_result") as DeviceId;
  const status = state.status === "active" || state.status === "unregistered" ? state.status : fail("malformed_result", "devicePushToken.status must be active or unregistered");
  const platform = readPlatform(state.platform, "malformed_result");
  const provider = readProvider(state.provider, "malformed_result");
  const environment = readEnvironment(state.environment, "malformed_result");
  assertProviderTarget(platform, provider, environment);
  const tokenRevision = revision(state.tokenRevision, "result.devicePushToken.tokenRevision", "malformed_result");
  const updatedAt = timestamp(state.updatedAt, "result.devicePushToken.updatedAt") as IsoTimestamp;
  return { deviceId, status, platform, provider, environment, tokenRevision, updatedAt };
}

function assertResultMatchesInput(
  operation: DevicePushTokenOperation,
  idempotencyKey: string,
  state: CanonicalDevicePushTokenState,
  input: DevicePushTokenInput,
): void {
  if (operation !== input.operation || idempotencyKey !== input.idempotencyKey || state.deviceId !== input.deviceId || state.tokenRevision !== input.tokenRevision) {
    fail("result_mismatch", "result must match operation, idempotency key, device, and revision from input");
  }
  if (input.operation !== "unregister" && (state.platform !== input.platform || state.provider !== input.provider || state.environment !== input.environment)) {
    fail("result_mismatch", "active canonical provider target must match input");
  }
}

function assertMonotonicRevision(value: number, current: number | undefined): void {
  if (current === undefined) return;
  if (!Number.isInteger(current) || current < 0 || current > MAX_DEVICE_PUSH_TOKEN_REVISION) fail("invalid_revision", "currentTokenRevision is outside the supported range");
  if (value <= current) fail("revision_not_monotonic", "tokenRevision must be strictly greater than currentTokenRevision");
}

function assertProviderTarget(platform: DevicePlatform, provider: DevicePushProvider, environment: DevicePushProviderEnvironment): void {
  if (platform === "ios" && provider === "apns") return;
  if (platform === "android" && provider === "fcm" && environment === "production") return;
  fail("invalid_provider_target", "provider, platform, and environment are not coherent");
}

function rejectTrustedIdentityFields(value: unknown, seen = new Set<object>()): void {
  if (!value || typeof value !== "object" || seen.has(value)) return;
  seen.add(value);
  if (Array.isArray(value)) {
    for (const nested of value) rejectTrustedIdentityFields(nested, seen);
    return;
  }
  for (const [key, nested] of Object.entries(value)) {
    if (TRUSTED_IDENTITY_FIELDS.has(normalize(key))) fail("trusted_identity_field", `caller input must not contain trusted identity field ${key}`);
    rejectTrustedIdentityFields(nested, seen);
  }
}

function readOperation(value: unknown, code: DevicePushTokenParseErrorCode): DevicePushTokenOperation {
  if (value === "register" || value === "refresh" || value === "unregister") return value;
  return fail(code, "operation must be register, refresh, or unregister");
}
function readPlatform(value: unknown, code: DevicePushTokenParseErrorCode): DevicePlatform {
  if (value === "ios" || value === "android") return value;
  return fail(code, "platform must be ios or android");
}
function readProvider(value: unknown, code: DevicePushTokenParseErrorCode): DevicePushProvider {
  if (value === "apns" || value === "fcm") return value;
  return fail(code, "provider must be apns or fcm");
}
function readEnvironment(value: unknown, code: DevicePushTokenParseErrorCode): DevicePushProviderEnvironment {
  if (value === "sandbox" || value === "production") return value;
  return fail(code, "environment must be sandbox or production");
}
function readReconciliationStatus(value: unknown): DevicePushTokenReconciliationStatus {
  if (value === "applied" || value === "replayed") return value;
  return fail("malformed_result", "reconciliationStatus must be applied or replayed");
}
function revision(value: unknown, path: string, code: DevicePushTokenParseErrorCode): number {
  if (!Number.isInteger(value) || (value as number) < MIN_DEVICE_PUSH_TOKEN_REVISION || (value as number) > MAX_DEVICE_PUSH_TOKEN_REVISION) fail(code === "malformed_result" ? code : "invalid_revision", `${path} is outside the supported integer range`);
  return value as number;
}
function timestamp(value: unknown, path: string): string {
  if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value) || Number.isNaN(Date.parse(value))) fail("malformed_result", `${path} must be a canonical UTC timestamp`);
  return value;
}
function boundedNonBlank(value: unknown, path: string, maximum: number, code: DevicePushTokenParseErrorCode): string {
  const result = nonBlank(value, path, code);
  if (new TextEncoder().encode(result).byteLength > maximum) fail(code, `${path} exceeds ${maximum} UTF-8 bytes`);
  return result;
}
function nonBlank(value: unknown, path: string, code: DevicePushTokenParseErrorCode): string {
  if (typeof value !== "string" || value.trim().length === 0) return fail(code, `${path} must be a nonblank string`);
  return value;
}
function record(value: unknown, path: string, code: DevicePushTokenParseErrorCode): Record<string, unknown> {
  if (!value || typeof value !== "object" || Array.isArray(value)) return fail(code, `${path} must be an object`);
  return value as Record<string, unknown>;
}
function exact(value: Record<string, unknown>, expected: readonly string[], path: string, code: DevicePushTokenParseErrorCode): void {
  const actual = Object.keys(value).sort();
  const wanted = [...expected].sort();
  if (actual.length !== wanted.length || actual.some((key, index) => key !== wanted[index])) fail(code, `${path} must contain exactly: ${expected.join(", ")}`);
}
function normalize(value: string): string { return value.replaceAll(/[^a-zA-Z0-9]/g, "").toLowerCase(); }
function fail(code: DevicePushTokenParseErrorCode, message: string): never { throw new DevicePushTokenContractError(code, message); }
