// Generated by scripts/generate-identifiers.mjs from contracts/models/identifiers.json.
// Do not edit this file directly.

declare const identifierBrand: unique symbol;

/** A nominal identifier whose value is scoped to one Handrail Chat tenant. */
export type TenantScopedId<Kind extends string> = string & {
  readonly [identifierBrand]: `tenant:${Kind}`;
};

/** An opaque host-application tenant identifier. */
export type TenantId = string & {
  readonly [identifierBrand]: "tenant";
};

/** A tenant-scoped conversation identifier. */
export type ConversationId = TenantScopedId<"conversation">;

/** A tenant-scoped message identifier. */
export type MessageId = TenantScopedId<"message">;

/** A tenant-scoped user identifier. */
export type UserId = TenantScopedId<"user">;

/** A tenant-scoped attachment identifier. */
export type AttachmentId = TenantScopedId<"attachment">;

/** A tenant-scoped device identifier. */
export type DeviceId = TenantScopedId<"device">;

/** A tenant-scoped session identifier. */
export type SessionId = TenantScopedId<"session">;

/** An ISO-8601 timestamp supplied by the server. */
export type IsoTimestamp = string;

/** A conversation-local, monotonically increasing message position. */
export type MessageSequence = number;
