// Generated by scripts/generate-message-context.mjs from contracts/http/message-context.json.
// Do not edit this file directly.

import type { ConversationId, MessageId, MessageSequence } from "./identifiers.js";
import type { Message, MessageBlock } from "./message.js";
import { parseCanonicalMessage } from "./generated/send-message.js";

export const MESSAGE_CONTEXT_PATH = "/conversations/:conversationId/messages/:messageId/context" as const;
/** Identifiers select a target; only the server's trusted session can authorize it. */
export interface MessageContextRequest {
  readonly conversationId: ConversationId;
  readonly messageId: MessageId;
}
export type MessageContextResult<Block extends MessageBlock = MessageBlock> = MessageContextRequest & (
  | { readonly status: "available"; readonly sequence: MessageSequence;
      readonly message: Extract<Message<Block>, { readonly deletedAt?: never }> }
  | { readonly status: "deleted"; readonly sequence: MessageSequence;
      readonly message: Extract<Message<Block>, { readonly deletedAt: string }> & { readonly content: null } }
  | { readonly status: "unavailable"; readonly sequence?: never; readonly message?: never }
);
export type MessageContextParseErrorCode = "malformed_request" | "malformed_result" | "identity_mismatch" | "invalid_sequence" | "invalid_message";
export class MessageContextParseError extends Error {
  constructor(readonly code: MessageContextParseErrorCode, message: string) {
    super(message);
    this.name = "MessageContextParseError";
  }
}
export function parseMessageContextRequest(value: unknown): MessageContextRequest {
  const object = record(value, "malformed_request");
  exact(object, ["conversationId", "messageId"], "malformed_request");
  return identity(object, "malformed_request");
}
/** Parse only a successful HTTP result body. Transport errors stay errors; never map a failed read to unavailable. */
export function parseMessageContextResult<Block extends MessageBlock = MessageBlock>(
  value: unknown, expectedRequest: MessageContextRequest,
): MessageContextResult<Block> {
  const request = parseMessageContextRequest(expectedRequest);
  const object = record(value, "malformed_result");
  const status = object.status;
  if (status !== "available" && status !== "deleted" && status !== "unavailable") fail("malformed_result", "Unsupported context status");
  exact(object, status === "unavailable" ? ["status", "conversationId", "messageId"] : ["status", "conversationId", "messageId", "sequence", "message"], "malformed_result");
  const target = identity(object, "malformed_result");
  if (target.conversationId !== request.conversationId || target.messageId !== request.messageId) fail("identity_mismatch", "Result must echo requested conversation and message");
  if (status === "unavailable") return { ...target, status };
  const sequence = parseSequence(object.sequence);
  let message: Message<Block>;
  try { message = parseCanonicalMessage<Block>(object.message); }
  catch { fail("invalid_message", "Context requires a canonical message"); }
  if (message.conversationId !== target.conversationId || message.id !== target.messageId) fail("identity_mismatch", "Message must belong to the requested target");
  if (parseSequence(message.sequence) !== sequence) fail("invalid_sequence", "Sequence must equal message.sequence");
  if (status === "deleted") {
    if (message.deletedAt === undefined || message.content !== null) fail("invalid_message", "Deleted context requires a redacted canonical deletion shell");
    return { ...target, status, sequence, message: { ...message, content: null } };
  }
  if (message.deletedAt !== undefined || message.content === null) fail("invalid_message", "Available context requires an active canonical message");
  return { ...target, status, sequence, message };
}
function identity(object: Record<string, unknown>, code: MessageContextParseErrorCode): MessageContextRequest {
  return { conversationId: identifier(object.conversationId, code) as ConversationId,
    messageId: identifier(object.messageId, code) as MessageId };
}
function identifier(value: unknown, code: MessageContextParseErrorCode): string {
  if (typeof value !== "string" || value.length === 0 || value.trim() !== value ||
      /[\x00-\x1f\x7f-\x9f\u2028\u2029]/u.test(value) || new TextEncoder().encode(value).length > 255) fail(code, "Invalid bounded identifier");
  return value;
}
function parseSequence(value: unknown): MessageSequence {
  if (typeof value !== "number" || !Number.isSafeInteger(value) || value < 1 || value > 9007199254740991) fail("invalid_sequence", "Sequence must be a positive safe integer");
  return value;
}
function record(value: unknown, code: MessageContextParseErrorCode): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) fail(code, "Expected an object");
  return value as Record<string, unknown>;
}
function exact(value: Record<string, unknown>, keys: readonly string[], code: MessageContextParseErrorCode): void {
  if (Object.keys(value).length !== keys.length || !keys.every(key => Object.hasOwn(value, key))) fail(code, "Unsupported or missing fields");
}
function fail(code: MessageContextParseErrorCode, message: string): never {
  throw new MessageContextParseError(code, message);
}
