// Generated by scripts/generate-messages.mjs from contracts/models/message.json.
// Do not edit this file directly.

import type {
  AttachmentId,
  ConversationId,
  IsoTimestamp,
  MessageId,
  MessageSequence,
  TenantId,
  UserId,
} from "./identifiers.js";
import type { HostEntityReference } from "./conversation.js";

export interface UserMention {
  readonly type: "user";
  readonly userId: UserId;
}

export interface ConversationMention {
  readonly type: "conversation";
  readonly conversationId: ConversationId;
}

export interface EntityMention {
  readonly type: "entity";
  readonly entity: HostEntityReference;
}

export type MessageMention =
  | UserMention
  | ConversationMention
  | EntityMention;

/** A reference to attachment metadata managed outside the message body. */
export interface MessageAttachmentReference {
  readonly attachmentId: AttachmentId;
}

/** A host-defined, renderer-dispatched structured block. */
export interface MessageBlock<Type extends string = string, Data = unknown> {
  readonly type: Type;
  readonly data: Data;
}

/** Non-secret original-author display attribution frozen when the forward is created. */
export interface ForwardedMessageAuthorAttribution {
  readonly userId: UserId;
  readonly displayName: string;
}

/** Renderer-safe source attribution attached to an immutable copy of the source display content; it is never resolved as a live rendering reference. */
export interface ForwardedMessageSnapshot {
  readonly sourceMessageId: MessageId;
  readonly originalAuthor: ForwardedMessageAuthorAttribution;
  readonly originalCreatedAt: IsoTimestamp;
}

/** Immutable same-conversation source reference; source display and actor attribution are resolved by the server. */
export interface MessageReplyReference {
  readonly messageId: MessageId;
  readonly notifyAuthor: boolean;
  readonly tenantId?: never;
  readonly actor?: never;
  readonly actorId?: never;
  readonly userId?: never;
  readonly author?: never;
  readonly authorId?: never;
  readonly sourceMessageId?: never;
  readonly originalAuthor?: never;
  readonly originalCreatedAt?: never;
  readonly displayName?: never;
  readonly sourceDisplay?: never;
  readonly source?: never;
  readonly content?: never;
}

interface MessageContentBase<Block extends MessageBlock> {
  readonly text: string;
  readonly mentions?: readonly MessageMention[];
  readonly attachments?: readonly MessageAttachmentReference[];
  readonly blocks?: readonly Block[];
  readonly forwarded?: ForwardedMessageSnapshot;
}

export type MessageContent<Block extends MessageBlock = MessageBlock> =
  | (MessageContentBase<Block> & { readonly format: "plain" })
  | (MessageContentBase<Block> & { readonly format: "markdown" });

export interface MessageAuthorIdentity {
  readonly type: "user";
  readonly userId: UserId;
}

export interface MessageRevisionMetadata {
  /** Starts at one and increases whenever the message is edited. */
  readonly revision: number;
  readonly editedAt?: IsoTimestamp;
  readonly editedByUserId?: UserId;
}

export interface ThreadSummaryFacts {
  readonly threadId: ConversationId;
  readonly replyCount: number;
  readonly participantIds: readonly UserId[];
  readonly lastReplyAt?: IsoTimestamp;
}

export interface ThreadSummary extends ThreadSummaryFacts {
  readonly unreadCount: number;
}

export interface NormalizedThreadSummary extends ThreadSummaryFacts {
  /** Null means unknown or invalidated; the key is always required. */
  readonly unreadCount: number | null;
}

interface MessageBase<Block extends MessageBlock> {
  readonly id: MessageId;
  readonly tenantId: TenantId;
  readonly conversationId: ConversationId;
  readonly author: MessageAuthorIdentity;
  /**
   * The immutable position allocated when the message is created. Editing only
   * changes content/revision metadata and does not allocate a new sequence, so
   * an already-read message does not become unread again merely because of an edit.
   */
  readonly sequence: MessageSequence;
  readonly createdAt: IsoTimestamp;
  readonly updatedAt: IsoTimestamp;
  readonly revision: MessageRevisionMetadata;
  readonly replyTo?: MessageReplyReference;
  /** Present only when this message is the root of a thread. */
  readonly threadSummary?: ThreadSummary;
}

export type Message<Block extends MessageBlock = MessageBlock> =
  | (MessageBase<Block> & {
      readonly content: MessageContent<Block>;
      readonly deletedAt?: never;
      readonly deletedByUserId?: never;
    })
  | (MessageBase<Block> & {
      /** Servers may redact content while retaining the soft-deleted message shell. */
      readonly content: MessageContent<Block> | null;
      readonly deletedAt: IsoTimestamp;
      readonly deletedByUserId: UserId;
    });

interface ServerOwnedActorFields {
  readonly tenantId?: never;
  readonly actor?: never;
  readonly actorId?: never;
  readonly userId?: never;
  readonly author?: never;
  readonly authorId?: never;
}

/**
 * Caller-authored message data. Tenant and actor identity are deliberately
 * impossible here; the server adds them from trusted host authentication.
 */
export type MessageComposition<Block extends MessageBlock = MessageBlock> =
  ServerOwnedActorFields & {
    readonly content: MessageContent<Block>;
    readonly replyTo?: MessageReplyReference;
  };
