// Generated by scripts/generate-message-search.mjs from contracts/http/message-search.json.
// Do not edit this file directly.

import type {
  ConversationId,
  IsoTimestamp,
  MessageId,
  UserId,
} from "./identifiers.js";

export const MESSAGE_SEARCH_MIN_PAGE_SIZE = 1;
export const MESSAGE_SEARCH_MAX_PAGE_SIZE = 100;
export const MESSAGE_SEARCH_MAX_CURSOR_LENGTH = 2048;
export const MESSAGE_SEARCH_MAX_IDENTIFIER_LENGTH = 255;

const MAX_TITLE_LENGTH = 512;
const MAX_SNIPPET_LENGTH = 4096;
const MAX_AUTHOR_DISPLAY_NAME_LENGTH = 256;
const TRUSTED_IDENTITY_FIELDS = new Set([
  "tenant",
  "tenantid",
  "organization",
  "organizationid",
  "actor",
  "actorid",
  "actorcontext",
  "actoruserid",
  "currentactor",
  "currentactorid",
  "currentuser",
  "currentuserid",
  "user",
  "userid",
  "principal",
  "principalid",
  "subject",
  "subjectid",
  "authenticateduser",
  "authenticateduserid",
  "identity",
  "session",
  "sessionid",
  "auth",
  "authorization",
  "role",
  "roles",
  "capability",
  "capabilities",
  "permission",
  "permissions",
]);

/** Compile-time guard for identity and authorization derived from trusted context. */
export interface NoTrustedMessageSearchIdentity {
  readonly tenant?: never;
  readonly tenantId?: never;
  readonly organization?: never;
  readonly organizationId?: never;
  readonly actor?: never;
  readonly actorId?: never;
  readonly actorContext?: never;
  readonly actorUserId?: never;
  readonly currentActor?: never;
  readonly currentActorId?: never;
  readonly currentUser?: never;
  readonly currentUserId?: never;
  readonly user?: never;
  readonly userId?: never;
  readonly principal?: never;
  readonly principalId?: never;
  readonly subject?: never;
  readonly subjectId?: never;
  readonly authenticatedUser?: never;
  readonly authenticatedUserId?: never;
  readonly identity?: never;
  readonly session?: never;
  readonly sessionId?: never;
  readonly auth?: never;
  readonly authorization?: never;
  readonly role?: never;
  readonly roles?: never;
  readonly capability?: never;
  readonly capabilities?: never;
  readonly permission?: never;
  readonly permissions?: never;
}

export interface MessageSearchFilters extends NoTrustedMessageSearchIdentity {
  readonly conversationIds?: readonly ConversationId[];
  readonly authorUserIds?: readonly UserId[];
  readonly sentAfter?: IsoTimestamp;
  readonly sentBefore?: IsoTimestamp;
}

declare const messageSearchCursorBrand: unique symbol;

/** Opaque pagination state. Consumers must return it without interpreting it. */
export type MessageSearchCursor = string & {
  readonly [messageSearchCursorBrand]: "message-search-cursor";
};

export interface MessageSearchRequest extends NoTrustedMessageSearchIdentity {
  /** NFC-normalized, trimmed, and whitespace-collapsed by the parser. */
  readonly query: string;
  readonly filters?: MessageSearchFilters;
  readonly pageSize: number;
  readonly cursor?: MessageSearchCursor;
}

interface MessageSearchHitBase {
  readonly conversationId: ConversationId;
  readonly title?: string;
  /** Plain text only; consumers must not interpret this field as markup. */
  readonly snippet: string;
}

export interface ConversationMessageSearchHit extends MessageSearchHitBase {
  readonly type: "conversation";
  readonly messageId?: never;
  readonly authorUserId?: never;
  readonly authorDisplayName?: never;
  readonly sentAt?: never;
}

export interface MessageMessageSearchHit extends MessageSearchHitBase {
  readonly type: "message";
  readonly messageId: MessageId;
  readonly authorUserId?: UserId;
  readonly authorDisplayName?: string;
  readonly sentAt?: IsoTimestamp;
}

export type MessageSearchHit =
  | ConversationMessageSearchHit
  | MessageMessageSearchHit;

export interface MessageSearchResponse {
  /** Server relevance order; the parser preserves this order exactly. */
  readonly hits: readonly MessageSearchHit[];
  readonly nextCursor?: MessageSearchCursor;
}

export type MessageSearchParseErrorCode =
  | "malformed_request"
  | "trusted_identity_field"
  | "malformed_filters"
  | "invalid_identifier"
  | "duplicate_identifier"
  | "invalid_timestamp"
  | "invalid_time_range"
  | "invalid_page_size"
  | "malformed_cursor"
  | "malformed_response"
  | "malformed_hit"
  | "duplicate_hit_identity";

export class MessageSearchParseError extends Error {
  readonly code: MessageSearchParseErrorCode;

  constructor(code: MessageSearchParseErrorCode, message: string) {
    super(message);
    this.name = "MessageSearchParseError";
    this.code = code;
  }
}

export function normalizeMessageSearchQuery(value: string): string {
  return value.normalize("NFC").trim().replaceAll(/\s+/gu, " ");
}

export function parseMessageSearchCursor(value: unknown, path = "cursor"): MessageSearchCursor {
  if (
    typeof value !== "string" ||
    value.trim().length === 0 ||
    value.length > MESSAGE_SEARCH_MAX_CURSOR_LENGTH
  ) {
    throw searchError(
      "malformed_cursor",
      `${path} must be a nonblank opaque string of at most ${MESSAGE_SEARCH_MAX_CURSOR_LENGTH} characters`,
    );
  }
  return value as MessageSearchCursor;
}

export function parseMessageSearchRequest(value: unknown): MessageSearchRequest {
  rejectTrustedIdentityFields(value);
  const request = requireRecord(value, "request", "malformed_request");
  assertAllowedKeys(request, ["query", "filters", "pageSize", "cursor"], "request", "malformed_request");
  if (typeof request.query !== "string") {
    throw searchError("malformed_request", "request.query must be a string");
  }
  const query = normalizeMessageSearchQuery(request.query);
  if (query.length === 0) {
    throw searchError("malformed_request", "request.query must not be empty after normalization");
  }
  const pageSize = readPageSize(request.pageSize);
  const output: {
    query: string;
    pageSize: number;
    filters?: MessageSearchFilters;
    cursor?: MessageSearchCursor;
  } = { query, pageSize };
  if (request.filters !== undefined) output.filters = parseMessageSearchFilters(request.filters);
  if (request.cursor !== undefined) output.cursor = parseMessageSearchCursor(request.cursor, "request.cursor");
  return output;
}

export function parseMessageSearchFilters(value: unknown): MessageSearchFilters {
  const filters = requireRecord(value, "request.filters", "malformed_filters");
  assertAllowedKeys(
    filters,
    ["conversationIds", "authorUserIds", "sentAfter", "sentBefore"],
    "request.filters",
    "malformed_filters",
  );
  const output: {
    conversationIds?: ConversationId[];
    authorUserIds?: UserId[];
    sentAfter?: IsoTimestamp;
    sentBefore?: IsoTimestamp;
  } = {};
  if (filters.conversationIds !== undefined) {
    output.conversationIds = readUniqueIds(filters.conversationIds, "request.filters.conversationIds") as ConversationId[];
  }
  if (filters.authorUserIds !== undefined) {
    output.authorUserIds = readUniqueIds(filters.authorUserIds, "request.filters.authorUserIds") as UserId[];
  }
  if (filters.sentAfter !== undefined) {
    output.sentAfter = readIsoTimestamp(filters.sentAfter, "request.filters.sentAfter", "invalid_timestamp");
  }
  if (filters.sentBefore !== undefined) {
    output.sentBefore = readIsoTimestamp(filters.sentBefore, "request.filters.sentBefore", "invalid_timestamp");
  }
  if (
    output.sentAfter !== undefined &&
    output.sentBefore !== undefined &&
    Date.parse(output.sentAfter) >= Date.parse(output.sentBefore)
  ) {
    throw searchError("invalid_time_range", "request.filters.sentAfter must be before sentBefore");
  }
  return output;
}

export function parseMessageSearchResponse(value: unknown): MessageSearchResponse {
  const response = requireRecord(value, "response", "malformed_response");
  assertAllowedKeys(response, ["hits", "nextCursor"], "response", "malformed_response");
  if (!Array.isArray(response.hits)) {
    throw searchError("malformed_response", "response.hits must be an array");
  }
  const hits: MessageSearchHit[] = [];
  const identities = new Set<string>();
  for (let index = 0; index < response.hits.length; index += 1) {
    const hit = parseMessageSearchHit(response.hits[index], `response.hits[${index}]`);
    const identity = hit.type === "conversation"
      ? `conversation:${hit.conversationId}`
      : `message:${hit.messageId}`;
    if (identities.has(identity)) {
      throw searchError("duplicate_hit_identity", `response.hits contains duplicate identity ${JSON.stringify(identity)}`);
    }
    identities.add(identity);
    hits.push(hit);
  }
  const output: { hits: MessageSearchHit[]; nextCursor?: MessageSearchCursor } = { hits };
  if (response.nextCursor !== undefined) {
    output.nextCursor = parseMessageSearchCursor(response.nextCursor, "response.nextCursor");
  }
  return output;
}

export function parseMessageSearchHit(value: unknown, path = "hit"): MessageSearchHit {
  const hit = requireRecord(value, path, "malformed_hit");
  if (hit.type === "conversation") return parseConversationHit(hit, path);
  if (hit.type === "message") return parseMessageHit(hit, path);
  throw searchError("malformed_hit", `${path}.type must be conversation or message`);
}

function parseConversationHit(hit: Record<string, unknown>, path: string): ConversationMessageSearchHit {
  assertAllowedKeys(hit, ["type", "conversationId", "title", "snippet"], path, "malformed_hit");
  const output: { type: "conversation"; conversationId: ConversationId; snippet: string; title?: string } = {
    type: "conversation",
    conversationId: readIdentifier(hit.conversationId, `${path}.conversationId`) as ConversationId,
    snippet: readBoundedNonBlankString(hit.snippet, `${path}.snippet`, MAX_SNIPPET_LENGTH),
  };
  if (hit.title !== undefined) output.title = readBoundedNonBlankString(hit.title, `${path}.title`, MAX_TITLE_LENGTH);
  return output;
}

function parseMessageHit(hit: Record<string, unknown>, path: string): MessageMessageSearchHit {
  assertAllowedKeys(
    hit,
    ["type", "conversationId", "messageId", "title", "snippet", "authorUserId", "authorDisplayName", "sentAt"],
    path,
    "malformed_hit",
  );
  const output: {
    type: "message";
    conversationId: ConversationId;
    messageId: MessageId;
    snippet: string;
    title?: string;
    authorUserId?: UserId;
    authorDisplayName?: string;
    sentAt?: IsoTimestamp;
  } = {
    type: "message",
    conversationId: readIdentifier(hit.conversationId, `${path}.conversationId`) as ConversationId,
    messageId: readIdentifier(hit.messageId, `${path}.messageId`) as MessageId,
    snippet: readBoundedNonBlankString(hit.snippet, `${path}.snippet`, MAX_SNIPPET_LENGTH),
  };
  if (hit.title !== undefined) output.title = readBoundedNonBlankString(hit.title, `${path}.title`, MAX_TITLE_LENGTH);
  if (hit.authorUserId !== undefined) output.authorUserId = readIdentifier(hit.authorUserId, `${path}.authorUserId`) as UserId;
  if (hit.authorDisplayName !== undefined) {
    output.authorDisplayName = readBoundedNonBlankString(hit.authorDisplayName, `${path}.authorDisplayName`, MAX_AUTHOR_DISPLAY_NAME_LENGTH);
  }
  if (hit.sentAt !== undefined) output.sentAt = readIsoTimestamp(hit.sentAt, `${path}.sentAt`, "malformed_hit");
  return output;
}

function readPageSize(value: unknown): number {
  if (
    typeof value !== "number" ||
    !Number.isInteger(value) ||
    value < MESSAGE_SEARCH_MIN_PAGE_SIZE ||
    value > MESSAGE_SEARCH_MAX_PAGE_SIZE
  ) {
    throw searchError(
      "invalid_page_size",
      `request.pageSize must be an integer from ${MESSAGE_SEARCH_MIN_PAGE_SIZE} through ${MESSAGE_SEARCH_MAX_PAGE_SIZE}`,
    );
  }
  return value;
}

function readUniqueIds(value: unknown, path: string): string[] {
  if (!Array.isArray(value)) throw searchError("malformed_filters", `${path} must be an array`);
  const output: string[] = [];
  const seen = new Set<string>();
  for (let index = 0; index < value.length; index += 1) {
    const id = readIdentifier(value[index], `${path}[${index}]`);
    if (seen.has(id)) throw searchError("duplicate_identifier", `${path} cannot contain duplicate identifiers`);
    seen.add(id);
    output.push(id);
  }
  return output;
}

function readIdentifier(value: unknown, path: string): string {
  if (
    typeof value !== "string" ||
    value.length === 0 ||
    value.length > MESSAGE_SEARCH_MAX_IDENTIFIER_LENGTH ||
    value !== value.trim() ||
    /[\u0000-\u001f\u007f]/u.test(value)
  ) {
    throw searchError("invalid_identifier", `${path} must be a valid nonblank transport identifier`);
  }
  return value;
}

function readBoundedNonBlankString(value: unknown, path: string, maximumLength: number): string {
  if (typeof value !== "string" || value.trim().length === 0 || value.length > maximumLength || value.includes("\u0000")) {
    throw searchError("malformed_hit", `${path} must be nonblank plain text of at most ${maximumLength} characters`);
  }
  return value;
}

function readIsoTimestamp(
  value: unknown,
  path: string,
  code: "invalid_timestamp" | "malformed_hit",
): IsoTimestamp {
  if (typeof value !== "string") throw searchError(code, `${path} must be an ISO-8601 timestamp`);
  const match = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d{1,9})?(Z|[+-]\d{2}:\d{2})$/u.exec(value);
  if (match === null) throw searchError(code, `${path} must be an ISO-8601 timestamp with a timezone`);
  const [, yearText, monthText, dayText, hourText, minuteText, secondText] = match;
  const zone = match[7]!;
  const year = Number(yearText);
  const month = Number(monthText);
  const day = Number(dayText);
  const hour = Number(hourText);
  const minute = Number(minuteText);
  const second = Number(secondText);
  const date = new Date(Date.UTC(year, month - 1, day));
  const zoneHour = zone === "Z" ? 0 : Number(zone.slice(1, 3));
  const zoneMinute = zone === "Z" ? 0 : Number(zone.slice(4, 6));
  if (
    date.getUTCFullYear() !== year ||
    date.getUTCMonth() !== month - 1 ||
    date.getUTCDate() !== day ||
    hour > 23 || minute > 59 || second > 59 || zoneHour > 23 || zoneMinute > 59 ||
    !Number.isFinite(Date.parse(value))
  ) {
    throw searchError(code, `${path} must be a valid ISO-8601 timestamp`);
  }
  return value as IsoTimestamp;
}

function rejectTrustedIdentityFields(value: unknown, path = "request"): void {
  if (Array.isArray(value)) {
    value.forEach((entry, index) => rejectTrustedIdentityFields(entry, `${path}[${index}]`));
    return;
  }
  if (!isRecord(value)) return;
  for (const [key, nested] of Object.entries(value)) {
    const normalized = key.replaceAll(/[^a-zA-Z0-9]/g, "").toLowerCase();
    if (TRUSTED_IDENTITY_FIELDS.has(normalized)) {
      throw searchError("trusted_identity_field", `${path}.${key} is server-derived and cannot be supplied by a client`);
    }
    rejectTrustedIdentityFields(nested, `${path}.${key}`);
  }
}

function assertAllowedKeys(
  value: Record<string, unknown>,
  allowed: readonly string[],
  path: string,
  code: "malformed_request" | "malformed_filters" | "malformed_response" | "malformed_hit",
): void {
  const allowedSet = new Set(allowed);
  for (const key of Object.keys(value)) {
    if (!allowedSet.has(key)) throw searchError(code, `${path}.${key} is not supported`);
  }
}

function requireRecord(
  value: unknown,
  path: string,
  code: "malformed_request" | "malformed_filters" | "malformed_response" | "malformed_hit",
): Record<string, unknown> {
  if (!isRecord(value)) throw searchError(code, `${path} must be an object`);
  return value;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function searchError(code: MessageSearchParseErrorCode, message: string): MessageSearchParseError {
  return new MessageSearchParseError(code, message);
}
