// Generated by scripts/generate-read-cursor.mjs from contracts/http/read-cursor.json.
// Do not edit the generated output directly.

/** Descriptor-owned wire metadata for PATCH read-cursor mutations. */
export const READ_CURSOR_MUTATION_METHOD = "PATCH" as const;
export const READ_CURSOR_MUTATION_PATH = "/conversations/:conversationId/read-cursor" as const;
export const READ_CURSOR_MUTATION_OPERATIONS = ["mark_read", "mark_unread"] as const;
export const READ_CURSOR_MUTATION_RECONCILIATION_STATUSES = ["applied", "replayed"] as const;
export const READ_CURSOR_UPDATED_EVENT_TYPE = "conversation.read_cursor_updated" as const;
export const READ_CURSOR_UPDATED_PAYLOAD_KIND = "conversation_read_cursor" as const;

import type { UntrustedChatMutationInput } from "../server/contracts.js";
import type {
  ConversationId,
  IsoTimestamp,
  MessageSequence,
  TenantId,
  UserId,
} from "./identifiers.js";
import {
  deriveUnreadCount,
  markRead,
  markUnread,
  type ConversationReadState,
} from "./member-read-state.js";
import { parseChatEvent, type ChatEvent } from "./realtime.js";

/** Matches the persisted `chat_idempotency_keys.client_key` UTF-8 bound. */
export const MAX_READ_CURSOR_IDEMPOTENCY_KEY_UTF8_BYTES =
  255;

const TRUSTED_IDENTITY_FIELDS = new Set([
  "tenant",
  "tenantid",
  "organization",
  "organizationid",
  "actor",
  "actorid",
  "actorcontext",
  "actoruserid",
  "currentactor",
  "currentactorid",
  "currentuserid",
  "user",
  "userid",
  "principal",
  "principalid",
  "subject",
  "subjectid",
  "authenticateduser",
  "authenticateduserid",
  "identity",
  "session",
  "sessionid",
  "auth",
  "authorization",
  "roles",
]);

/** Compile-time guard for identity that must come from the trusted session. */
export interface NoTrustedReadCursorMutationIdentity {
  readonly tenant?: never;
  readonly tenantId?: never;
  readonly organization?: never;
  readonly organizationId?: never;
  readonly actor?: never;
  readonly actorId?: never;
  readonly actorContext?: never;
  readonly actorUserId?: never;
  readonly currentActor?: never;
  readonly currentActorId?: never;
  readonly currentUserId?: never;
  readonly user?: never;
  readonly userId?: never;
  readonly principal?: never;
  readonly principalId?: never;
  readonly subject?: never;
  readonly subjectId?: never;
  readonly authenticatedUser?: never;
  readonly authenticatedUserId?: never;
  readonly identity?: never;
  readonly session?: never;
  readonly sessionId?: never;
  readonly auth?: never;
  readonly authorization?: never;
  readonly roles?: never;
}

type ReadCursorMutationInputBase<
  Operation extends string,
  SequenceField extends object,
> = UntrustedChatMutationInput<
  NoTrustedReadCursorMutationIdentity &
    SequenceField & {
      readonly operation: Operation;
      readonly conversationId: ConversationId;
      readonly idempotencyKey: string;
    }
>;

/** Monotonic intent to read through a conversation-local message sequence. */
export type MarkReadInput = ReadCursorMutationInputBase<
  "mark_read",
  { readonly throughSequence: MessageSequence }
>;

/** Explicit intent to make an existing, already-read sequence unread. */
export type MarkUnreadInput = ReadCursorMutationInputBase<
  "mark_unread",
  { readonly fromSequence: MessageSequence }
>;

export type ReadCursorMutationInput = MarkReadInput | MarkUnreadInput;
export type ReadCursorMutationOperation = ReadCursorMutationInput["operation"];

interface ReadCursorMutationResultBase<Operation extends string> {
  readonly operation: Operation;
  readonly conversationId: ConversationId;
  readonly readState: ConversationReadState;
  /** Sequence used to derive `unreadCount`, included for deterministic clients. */
  readonly latestSequence: MessageSequence;
  readonly unreadCount: number;
}

export type MarkReadResult = ReadCursorMutationResultBase<"mark_read">;
export type MarkUnreadResult = ReadCursorMutationResultBase<"mark_unread">;
export type ReadCursorMutationResult = MarkReadResult | MarkUnreadResult;

export type ReadCursorMutationReconciliationStatus = "applied" | "replayed";

interface ReadCursorMutationOutcomeBase<
  Result extends ReadCursorMutationResult,
  Status extends ReadCursorMutationReconciliationStatus,
> extends ReadCursorMutationResultBase<Result["operation"]> {
  readonly reconciliationStatus: Status;
  /** Exact request key used to deterministically correlate retries. */
  readonly idempotencyKey: string;
}

export type AppliedReadCursorMutationResult =
  | ReadCursorMutationOutcomeBase<MarkReadResult, "applied">
  | ReadCursorMutationOutcomeBase<MarkUnreadResult, "applied">;

export type ReplayedReadCursorMutationResult =
  | ReadCursorMutationOutcomeBase<MarkReadResult, "replayed">
  | ReadCursorMutationOutcomeBase<MarkUnreadResult, "replayed">;

/** Explicit HTTP reconciliation result. Durable events carry canonical state only. */
export type ReadCursorMutationOutcome =
  | AppliedReadCursorMutationResult
  | ReplayedReadCursorMutationResult;

/** Server-trusted state required to resolve a caller-authored cursor intent. */
export interface TrustedReadCursorMutationContext {
  readonly currentReadState: ConversationReadState;
  readonly latestSequence: MessageSequence;
  readonly updatedAt: IsoTimestamp;
}

/** Durable payload delivered to every private session for the affected user. */
export interface ReadCursorUpdatedPayload
  extends ReadCursorMutationResultBase<ReadCursorMutationOperation> {
  readonly kind: "conversation_read_cursor";
  /** Trusted actor whose own conversation read state was updated. */
  readonly actorUserId: UserId;
}

export type ReadCursorUserStreamId = `user:${string}`;

/** Distinct durable envelope; it cannot be interpreted as a message edit. */
export interface ReadCursorUpdatedEvent extends ChatEvent<ReadCursorUpdatedPayload> {
  readonly type: "conversation.read_cursor_updated";
  readonly streamId: ReadCursorUserStreamId;
}

export interface ReadCursorUpdatedEventInput {
  readonly eventId: string;
  readonly protocolVersion: number;
  readonly tenantId: TenantId;
  readonly occurredAt: IsoTimestamp;
  readonly result: ReadCursorMutationResult;
}

export type ReadCursorMutationErrorCode =
  | "malformed_input"
  | "trusted_identity_field"
  | "invalid_sequence"
  | "cursor_regression"
  | "sequence_out_of_range"
  | "read_state_mismatch"
  | "invalid_read_state"
  | "malformed_result"
  | "malformed_event";

export class ReadCursorMutationError extends Error {
  readonly code: ReadCursorMutationErrorCode;

  constructor(code: ReadCursorMutationErrorCode, message: string) {
    super(message);
    this.name = "ReadCursorMutationError";
    this.code = code;
  }
}

export function parseMarkReadInput(value: unknown): MarkReadInput {
  return parseInput(value, "mark_read");
}

export function parseMarkUnreadInput(value: unknown): MarkUnreadInput {
  return parseInput(value, "mark_unread");
}

export function parseReadCursorMutationInput(
  value: unknown,
): ReadCursorMutationInput {
  const input = requireRecord(value, "input", "malformed_input");
  rejectTrustedIdentityFields(input);

  if (input.operation === "mark_read") {
    return parseInputRecord(input, "mark_read");
  }
  if (input.operation === "mark_unread") {
    return parseInputRecord(input, "mark_unread");
  }
  throw contractError(
    "malformed_input",
    "operation must be mark_read or mark_unread",
  );
}

/**
 * Applies validated caller intent to trusted state using the established read
 * helpers. Reapplying an already-realized intent preserves `updatedAt`, so a
 * retry does not pretend that another read-state transition occurred.
 */
export function applyReadCursorMutation(
  value: unknown,
  context: TrustedReadCursorMutationContext,
): ReadCursorMutationResult {
  const input = parseReadCursorMutationInput(value);
  const latestSequence = readSequence(
    context.latestSequence,
    "latestSequence",
    false,
    "invalid_sequence",
  );
  const current = validateReadState(
    context.currentReadState,
    latestSequence,
    "invalid_read_state",
  );
  readIsoTimestamp(context.updatedAt, "updatedAt", "invalid_read_state");

  if (input.conversationId !== current.conversationId) {
    throw contractError(
      "read_state_mismatch",
      "input.conversationId must match the trusted current read state",
    );
  }

  if (input.operation === "mark_read") {
    if (input.throughSequence < current.lastReadSequence) {
      throw contractError(
        "cursor_regression",
        "mark-read cursor cannot move backward",
      );
    }
    if (input.throughSequence > latestSequence) {
      throw contractError(
        "sequence_out_of_range",
        "throughSequence cannot exceed latestSequence",
      );
    }

    const alreadyRealized =
      input.throughSequence === current.lastReadSequence &&
      current.manualUnreadFromSequence === undefined;
    const readState = alreadyRealized
      ? current
      : markRead(current, input.throughSequence, context.updatedAt);

    return {
      operation: "mark_read",
      conversationId: input.conversationId,
      readState,
      latestSequence,
      unreadCount: deriveUnreadCount(latestSequence, readState),
    };
  }

  const maximumUnreadSequence = Math.min(
    current.lastReadSequence,
    latestSequence,
  );
  if (
    input.fromSequence < 1 ||
    input.fromSequence > maximumUnreadSequence
  ) {
    throw contractError(
      "sequence_out_of_range",
      "fromSequence must identify an existing sequence in the already-read range",
    );
  }

  const alreadyRealized =
    current.manualUnreadFromSequence === input.fromSequence;
  const readState = alreadyRealized
    ? current
    : markUnread(current, input.fromSequence, context.updatedAt);

  return {
    operation: "mark_unread",
    conversationId: input.conversationId,
    readState,
    latestSequence,
    unreadCount: deriveUnreadCount(latestSequence, readState),
  };
}

export function parseReadCursorMutationResult(
  value: unknown,
): ReadCursorMutationResult {
  const result = requireRecord(value, "result", "malformed_result");
  assertExactKeys(
    result,
    [
      "operation",
      "conversationId",
      "readState",
      "latestSequence",
      "unreadCount",
    ],
    "result",
    "malformed_result",
  );
  const operation = readOperation(result.operation, "malformed_result");
  const conversationId = readNonBlankString(
    result.conversationId,
    "result.conversationId",
    "malformed_result",
  ) as ConversationId;
  const latestSequence = readSequence(
    result.latestSequence,
    "result.latestSequence",
    false,
    "malformed_result",
  );
  const readState = validateReadState(
    result.readState,
    latestSequence,
    "malformed_result",
  );
  const unreadCount = readSequence(
    result.unreadCount,
    "result.unreadCount",
    false,
    "malformed_result",
  );

  if (conversationId !== readState.conversationId) {
    throw contractError(
      "malformed_result",
      "result conversationId must match readState.conversationId",
    );
  }
  if (unreadCount !== deriveUnreadCount(latestSequence, readState)) {
    throw contractError(
      "malformed_result",
      "result.unreadCount must be derived from latestSequence and readState",
    );
  }
  if (
    operation === "mark_read" &&
    readState.manualUnreadFromSequence !== undefined
  ) {
    throw contractError(
      "malformed_result",
      "a mark_read result must clear manualUnreadFromSequence",
    );
  }
  if (
    operation === "mark_read" &&
    readState.lastReadSequence > latestSequence
  ) {
    throw contractError(
      "malformed_result",
      "a mark_read result cannot advance beyond latestSequence",
    );
  }
  if (
    operation === "mark_unread" &&
    readState.manualUnreadFromSequence === undefined
  ) {
    throw contractError(
      "malformed_result",
      "a mark_unread result must include manualUnreadFromSequence",
    );
  }

  return {
    operation,
    conversationId,
    readState,
    latestSequence,
    unreadCount,
  } as ReadCursorMutationResult;
}

/**
 * Parses an applied/replayed HTTP outcome against the exact request. This is
 * intentionally additive to the canonical result API used by the existing
 * runtime and durable event constructors.
 */
export function parseReadCursorMutationOutcome(
  value: unknown,
  expectedInput: ReadCursorMutationInput,
): ReadCursorMutationOutcome {
  const input = parseReadCursorMutationInput(expectedInput);
  const outcome = requireRecord(value, "result", "malformed_result");
  assertExactKeys(
    outcome,
    [
      "operation",
      "reconciliationStatus",
      "idempotencyKey",
      "conversationId",
      "readState",
      "latestSequence",
      "unreadCount",
    ],
    "result",
    "malformed_result",
  );
  const reconciliationStatus = readReconciliationStatus(
    outcome.reconciliationStatus,
  );
  const idempotencyKey = parseBoundedIdempotencyKey(
    outcome.idempotencyKey,
    "result.idempotencyKey",
    "malformed_result",
  );
  const result = parseReadCursorMutationResult({
    operation: outcome.operation,
    conversationId: outcome.conversationId,
    readState: outcome.readState,
    latestSequence: outcome.latestSequence,
    unreadCount: outcome.unreadCount,
  });

  if (
    result.operation !== input.operation ||
    result.conversationId !== input.conversationId ||
    idempotencyKey !== input.idempotencyKey
  ) {
    throw contractError(
      "malformed_result",
      "result operation, conversationId, and idempotencyKey must match the request",
    );
  }
  if (
    input.operation === "mark_read" &&
    result.readState.lastReadSequence !== input.throughSequence
  ) {
    throw contractError(
      "malformed_result",
      "mark_read result must carry the requested throughSequence",
    );
  }
  if (
    input.operation === "mark_unread" &&
    result.readState.manualUnreadFromSequence !== input.fromSequence
  ) {
    throw contractError(
      "malformed_result",
      "mark_unread result must carry the requested fromSequence",
    );
  }

  return {
    ...result,
    reconciliationStatus,
    idempotencyKey,
  } as ReadCursorMutationOutcome;
}

/** Adds the explicit status/key envelope to a canonical committed result. */
export function createReadCursorMutationOutcome(
  result: ReadCursorMutationResult,
  input: ReadCursorMutationInput,
  reconciliationStatus: "applied",
): AppliedReadCursorMutationResult;
export function createReadCursorMutationOutcome(
  result: ReadCursorMutationResult,
  input: ReadCursorMutationInput,
  reconciliationStatus: "replayed",
): ReplayedReadCursorMutationResult;
export function createReadCursorMutationOutcome(
  result: ReadCursorMutationResult,
  input: ReadCursorMutationInput,
  reconciliationStatus: ReadCursorMutationReconciliationStatus,
): ReadCursorMutationOutcome {
  return parseReadCursorMutationOutcome(
    { ...result, reconciliationStatus, idempotencyKey: input.idempotencyKey },
    input,
  );
}

/** Creates the server-authored user-private event for a committed mutation. */
export function createReadCursorUpdatedEvent(
  input: ReadCursorUpdatedEventInput,
): ReadCursorUpdatedEvent {
  const eventId = readNonBlankString(
    input.eventId,
    "eventId",
    "malformed_event",
  );
  const protocolVersion = readSequence(
    input.protocolVersion,
    "protocolVersion",
    true,
    "malformed_event",
  );
  const tenantId = readNonBlankString(
    input.tenantId,
    "tenantId",
    "malformed_event",
  ) as TenantId;
  const occurredAt = readIsoTimestamp(
    input.occurredAt,
    "occurredAt",
    "malformed_event",
  );
  const result = parseReadCursorMutationResult(input.result);
  const actorUserId = result.readState.userId;

  return {
    eventId,
    protocolVersion,
    tenantId,
    streamId: `user:${actorUserId}`,
    type: "conversation.read_cursor_updated",
    occurredAt,
    payload: {
      kind: "conversation_read_cursor",
      actorUserId,
      ...result,
    },
  };
}

/** Parses a cross-device event against the tenant from the trusted session. */
export function parseReadCursorUpdatedEvent(
  value: unknown,
  expectedTenantId: TenantId,
): ReadCursorUpdatedEvent {
  const record = requireRecord(value, "event", "malformed_event");
  assertExactKeys(
    record,
    [
      "eventId",
      "protocolVersion",
      "tenantId",
      "streamId",
      "type",
      "occurredAt",
      "payload",
    ],
    "event",
    "malformed_event",
  );

  let event: ChatEvent<ReadCursorUpdatedPayload>;
  try {
    event = parseChatEvent(record, expectedTenantId, parseUpdatedPayload);
  } catch (error) {
    if (error instanceof ReadCursorMutationError) {
      throw error;
    }
    throw contractError(
      "malformed_event",
      error instanceof Error ? error.message : "event is malformed",
    );
  }

  if (event.type !== "conversation.read_cursor_updated") {
    throw contractError(
      "malformed_event",
      "event.type must be conversation.read_cursor_updated",
    );
  }
  const expectedStreamId = `user:${event.payload.actorUserId}`;
  if (event.streamId !== expectedStreamId) {
    throw contractError(
      "malformed_event",
      "event.streamId must identify the affected user's private stream",
    );
  }

  return {
    ...event,
    type: "conversation.read_cursor_updated",
    streamId: event.streamId as ReadCursorUserStreamId,
  };
}

function parseInput<Operation extends ReadCursorMutationOperation>(
  value: unknown,
  operation: Operation,
): Operation extends "mark_read" ? MarkReadInput : MarkUnreadInput {
  const input = requireRecord(value, "input", "malformed_input");
  rejectTrustedIdentityFields(input);
  return parseInputRecord(input, operation);
}

function parseInputRecord<Operation extends ReadCursorMutationOperation>(
  input: Record<string, unknown>,
  operation: Operation,
): Operation extends "mark_read" ? MarkReadInput : MarkUnreadInput {
  const sequenceKey = operation === "mark_read" ? "throughSequence" : "fromSequence";
  assertExactKeys(
    input,
    ["operation", "conversationId", sequenceKey, "idempotencyKey"],
    "input",
    "malformed_input",
  );
  if (input.operation !== operation) {
    throw contractError("malformed_input", `operation must be ${operation}`);
  }

  const base = {
    operation,
    conversationId: readNonBlankString(
      input.conversationId,
      "input.conversationId",
      "malformed_input",
    ) as ConversationId,
    idempotencyKey: parseIdempotencyKey(input.idempotencyKey),
  };

  return (operation === "mark_read"
    ? {
        ...base,
        operation: "mark_read",
        throughSequence: readSequence(
          input.throughSequence,
          "input.throughSequence",
          false,
          "invalid_sequence",
        ),
      }
    : {
        ...base,
        operation: "mark_unread",
        fromSequence: readSequence(
          input.fromSequence,
          "input.fromSequence",
          true,
          "invalid_sequence",
        ),
      }) as Operation extends "mark_read" ? MarkReadInput : MarkUnreadInput;
}

function parseUpdatedPayload(value: unknown): ReadCursorUpdatedPayload {
  const payload = requireRecord(value, "event.payload", "malformed_event");
  assertExactKeys(
    payload,
    [
      "kind",
      "actorUserId",
      "operation",
      "conversationId",
      "readState",
      "latestSequence",
      "unreadCount",
    ],
    "event.payload",
    "malformed_event",
  );
  if (payload.kind !== "conversation_read_cursor") {
    throw contractError(
      "malformed_event",
      "event.payload.kind must be conversation_read_cursor",
    );
  }
  const actorUserId = readNonBlankString(
    payload.actorUserId,
    "event.payload.actorUserId",
    "malformed_event",
  ) as UserId;
  const result = parseReadCursorMutationResult({
    operation: payload.operation,
    conversationId: payload.conversationId,
    readState: payload.readState,
    latestSequence: payload.latestSequence,
    unreadCount: payload.unreadCount,
  });
  if (actorUserId !== result.readState.userId) {
    throw contractError(
      "malformed_event",
      "actorUserId must match readState.userId",
    );
  }

  return {
    kind: "conversation_read_cursor",
    actorUserId,
    ...result,
  };
}

function validateReadState(
  value: unknown,
  latestSequence: number,
  code: "invalid_read_state" | "malformed_result",
): ConversationReadState {
  const readState = requireRecord(value, "readState", code);
  const allowedKeys = [
    "conversationId",
    "userId",
    "lastReadSequence",
    "manualUnreadFromSequence",
    "updatedAt",
  ];
  assertAllowedKeys(readState, allowedKeys, "readState", code);
  for (const required of [
    "conversationId",
    "userId",
    "lastReadSequence",
    "updatedAt",
  ]) {
    if (!Object.hasOwn(readState, required)) {
      throw contractError(code, `readState.${required} is required`);
    }
  }

  const conversationId = readNonBlankString(
    readState.conversationId,
    "readState.conversationId",
    code,
  ) as ConversationId;
  const userId = readNonBlankString(
    readState.userId,
    "readState.userId",
    code,
  ) as UserId;
  const lastReadSequence = readSequence(
    readState.lastReadSequence,
    "readState.lastReadSequence",
    false,
    code,
  );
  const updatedAt = readIsoTimestamp(readState.updatedAt, "readState.updatedAt", code);
  const markerValue = readState.manualUnreadFromSequence;

  if (markerValue === undefined) {
    return { conversationId, userId, lastReadSequence, updatedAt };
  }

  const manualUnreadFromSequence = readSequence(
    markerValue,
    "readState.manualUnreadFromSequence",
    true,
    code,
  );
  if (manualUnreadFromSequence > Math.min(lastReadSequence, latestSequence)) {
    throw contractError(
      code,
      "readState.manualUnreadFromSequence must be in the existing already-read range",
    );
  }
  return {
    conversationId,
    userId,
    lastReadSequence,
    manualUnreadFromSequence,
    updatedAt,
  };
}

function parseIdempotencyKey(value: unknown): string {
  return parseBoundedIdempotencyKey(
    value,
    "input.idempotencyKey",
    "malformed_input",
  );
}

function parseBoundedIdempotencyKey(
  value: unknown,
  path: string,
  code: "malformed_input" | "malformed_result",
): string {
  const key = readNonBlankString(value, path, code);
  if (
    new TextEncoder().encode(key).byteLength >
    MAX_READ_CURSOR_IDEMPOTENCY_KEY_UTF8_BYTES
  ) {
    throw contractError(
      code,
      `${path} cannot exceed ${MAX_READ_CURSOR_IDEMPOTENCY_KEY_UTF8_BYTES} UTF-8 bytes`,
    );
  }
  return key;
}

function readReconciliationStatus(
  value: unknown,
): ReadCursorMutationReconciliationStatus {
  if (value !== "applied" && value !== "replayed") {
    throw contractError(
      "malformed_result",
      "result.reconciliationStatus must be applied or replayed",
    );
  }
  return value;
}

function rejectTrustedIdentityFields(input: Record<string, unknown>): void {
  for (const key of Object.keys(input)) {
    const normalizedKey = key.replaceAll(/[^a-zA-Z0-9]/g, "").toLowerCase();
    if (TRUSTED_IDENTITY_FIELDS.has(normalizedKey)) {
      throw contractError(
        "trusted_identity_field",
        `input.${key} is server-derived and cannot be supplied by a client`,
      );
    }
  }
}

function readOperation(
  value: unknown,
  code: ReadCursorMutationErrorCode,
): ReadCursorMutationOperation {
  if (value !== "mark_read" && value !== "mark_unread") {
    throw contractError(code, "operation must be mark_read or mark_unread");
  }
  return value;
}

function readSequence(
  value: unknown,
  path: string,
  positive: boolean,
  code: ReadCursorMutationErrorCode,
): number {
  if (
    !Number.isSafeInteger(value) ||
    (value as number) < (positive ? 1 : 0)
  ) {
    throw contractError(
      code,
      `${path} must be a ${positive ? "positive" : "non-negative"} safe integer`,
    );
  }
  return value as number;
}

function readNonBlankString(
  value: unknown,
  path: string,
  code: ReadCursorMutationErrorCode,
): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw contractError(code, `${path} must be a nonblank string`);
  }
  return value;
}

function readIsoTimestamp(
  value: unknown,
  path: string,
  code: ReadCursorMutationErrorCode,
): IsoTimestamp {
  if (
    typeof value !== "string" ||
    !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(
      value,
    ) ||
    !Number.isFinite(Date.parse(value))
  ) {
    throw contractError(code, `${path} must be an ISO-8601 timestamp`);
  }
  return value;
}

function requireRecord(
  value: unknown,
  path: string,
  code: ReadCursorMutationErrorCode,
): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    throw contractError(code, `${path} must be an object`);
  }
  return value as Record<string, unknown>;
}

function assertExactKeys(
  value: Record<string, unknown>,
  expected: readonly string[],
  path: string,
  code: ReadCursorMutationErrorCode,
): void {
  assertAllowedKeys(value, expected, path, code);
  for (const key of expected) {
    if (!Object.hasOwn(value, key)) {
      throw contractError(code, `${path}.${key} is required`);
    }
  }
}

function assertAllowedKeys(
  value: Record<string, unknown>,
  allowed: readonly string[],
  path: string,
  code: ReadCursorMutationErrorCode,
): void {
  const allowedKeys = new Set(allowed);
  for (const key of Object.keys(value)) {
    if (!allowedKeys.has(key)) {
      throw contractError(code, `${path}.${key} is not allowed`);
    }
  }
}

function contractError(
  code: ReadCursorMutationErrorCode,
  message: string,
): ReadCursorMutationError {
  return new ReadCursorMutationError(code, message);
}
