// Generated by scripts/generate-reply-style-preference.mjs from contracts/http/reply-style-preference.json.
// Do not edit this file directly.

export const REPLY_STYLE_PREFERENCE_FEATURE = "reply_style_preference_v1" as const;
export const MAX_REPLY_STYLE_PREFERENCE_IDEMPOTENCY_KEY_UTF8_BYTES = 255;
const MAX_SAFE_REVISION = 9007199254740991;
export type ReplyStyle = "current" | "discord";

/** Identity and authorization come exclusively from the trusted session. */
export interface NoTrustedReplyStylePreferenceContext {
  readonly tenant?: never;
  readonly tenantId?: never;
  readonly organization?: never;
  readonly organizationId?: never;
  readonly actor?: never;
  readonly actorId?: never;
  readonly actorContext?: never;
  readonly actorRole?: never;
  readonly actorRoles?: never;
  readonly actorUserId?: never;
  readonly currentActor?: never;
  readonly currentActorId?: never;
  readonly currentUser?: never;
  readonly currentUserId?: never;
  readonly user?: never;
  readonly userId?: never;
  readonly otherUser?: never;
  readonly otherUserId?: never;
  readonly arbitraryUser?: never;
  readonly arbitraryUserId?: never;
  readonly targetUser?: never;
  readonly targetUserId?: never;
  readonly principal?: never;
  readonly principalId?: never;
  readonly subject?: never;
  readonly subjectId?: never;
  readonly authenticatedUser?: never;
  readonly authenticatedUserId?: never;
  readonly identity?: never;
  readonly session?: never;
  readonly sessionId?: never;
  readonly auth?: never;
  readonly authentication?: never;
  readonly authorization?: never;
  readonly role?: never;
  readonly roles?: never;
  readonly capability?: never;
  readonly capabilities?: never;
  readonly permission?: never;
  readonly permissions?: never;
}
export type GetReplyStylePreferenceInput = NoTrustedReplyStylePreferenceContext;
export type ReplyStylePreferenceState =
  | { readonly state: "absent"; readonly revision: 0; readonly style?: never }
  | { readonly state: "saved"; readonly revision: number; readonly style: string };
export interface UpdateReplyStylePreferenceInput extends NoTrustedReplyStylePreferenceContext {
  readonly operation: "update_reply_style_preference";
  readonly style: ReplyStyle;
  readonly baseRevision: number;
  readonly idempotencyKey: string;
}
export type ReplyStylePreferenceReconciliationStatus =
  | "applied" | "replayed" | "already_requested_state" | "preference_revision_conflict";
interface ReplyStylePreferenceResultBase {
  readonly operation: "update_reply_style_preference";
  readonly baseRevision: number;
  readonly idempotencyKey: string;
  readonly requestedStyle: ReplyStyle;
}
export type UpdateReplyStylePreferenceResult = ReplyStylePreferenceResultBase & (
  | { readonly reconciliationStatus: "applied" | "replayed" | "already_requested_state";
      readonly preference: { readonly state: "saved"; readonly revision: number; readonly style: ReplyStyle } }
  | { readonly reconciliationStatus: "preference_revision_conflict"; readonly preference: ReplyStylePreferenceState }
);
export type ReplyStylePreferenceParseErrorCode =
  | "malformed_input" | "trusted_identity_field" | "malformed_style"
  | "malformed_revision" | "malformed_result" | "incoherent_result";
export class ReplyStylePreferenceParseError extends Error {
  constructor(readonly code: ReplyStylePreferenceParseErrorCode, message: string) {
    super(message);
    this.name = "ReplyStylePreferenceParseError";
  }
}

/** A missing feature is unsupported. This does not advertise server support. */
export function supportsReplyStylePreference(features?: Readonly<Record<string, boolean>>): boolean {
  return features?.[REPLY_STYLE_PREFERENCE_FEATURE] === true;
}
export function isReplyStyle(value: unknown): value is ReplyStyle {
  return value === "current" || value === "discord";
}
/** Value fallback only. Callers must distinguish absent from saved before host precedence. */
export function resolveReplyStylePreference(preference: ReplyStylePreferenceState): ReplyStyle {
  return preference.state === "saved" && isReplyStyle(preference.style) ? preference.style : "current";
}
export function parseGetReplyStylePreferenceInput(value: unknown): GetReplyStylePreferenceInput {
  rejectTrusted(value);
  exact(record(value, "malformed_input"), [], "malformed_input");
  return {};
}
export function parseReplyStylePreferenceState(value: unknown): ReplyStylePreferenceState {
  rejectTrusted(value);
  const object = record(value, "malformed_result");
  const revision = parseRevision(object.revision, false);
  if (object.state === "absent") {
    exact(object, ["state", "revision"], "malformed_result");
    if (revision !== 0) fail("incoherent_result", "Absent preference must have revision zero");
    return { state: "absent", revision: 0 };
  }
  exact(object, ["state", "revision", "style"], "malformed_result");
  if (object.state !== "saved" || typeof object.style !== "string") fail("malformed_result", "Saved preference requires a raw style string");
  if (revision === 0) fail("incoherent_result", "Saved preference requires a positive revision");
  return { state: "saved", revision, style: object.style };
}
export function parseUpdateReplyStylePreferenceInput(value: unknown): UpdateReplyStylePreferenceInput {
  rejectTrusted(value);
  const object = record(value, "malformed_input");
  exact(object, ["operation", "style", "baseRevision", "idempotencyKey"], "malformed_input");
  if (object.operation !== "update_reply_style_preference") fail("malformed_input", "Unsupported operation");
  return { operation: "update_reply_style_preference", style: style(object.style),
    baseRevision: parseRevision(object.baseRevision, true), idempotencyKey: key(object.idempotencyKey) };
}
export function parseUpdateReplyStylePreferenceResult(value: unknown, expectedInput: UpdateReplyStylePreferenceInput): UpdateReplyStylePreferenceResult {
  const request = parseUpdateReplyStylePreferenceInput(expectedInput);
  rejectTrusted(value);
  const object = record(value, "malformed_result");
  exact(object, ["operation", "reconciliationStatus", "baseRevision", "idempotencyKey", "requestedStyle", "preference"], "malformed_result");
  const status = object.reconciliationStatus;
  if (object.operation !== "update_reply_style_preference" ||
      (status !== "applied" && status !== "replayed" && status !== "already_requested_state" && status !== "preference_revision_conflict")) {
    fail("malformed_result", "Unsupported operation or reconciliation status");
  }
  const baseRevision = parseRevision(object.baseRevision, true);
  const idempotencyKey = key(object.idempotencyKey);
  const requestedStyle = style(object.requestedStyle);
  const preference = parseReplyStylePreferenceState(object.preference);
  if (baseRevision !== request.baseRevision || idempotencyKey !== request.idempotencyKey || requestedStyle !== request.style) {
    fail("incoherent_result", "Result must echo the exact request");
  }
  const base = { operation: "update_reply_style_preference" as const, baseRevision, idempotencyKey, requestedStyle };
  if (status === "preference_revision_conflict") {
    if (preference.revision === baseRevision) fail("incoherent_result", "Conflict requires a different canonical revision");
    return { ...base, reconciliationStatus: status, preference };
  }
  const expectedRevision = status === "already_requested_state" ? baseRevision : baseRevision + 1;
  if (preference.revision !== expectedRevision || preference.state !== "saved" || preference.style !== requestedStyle) {
    fail("incoherent_result", "Settled result must carry the requested saved style and status-specific revision");
  }
  return { ...base, reconciliationStatus: status, preference: { state: "saved", revision: preference.revision, style: requestedStyle } };
}
const trustedFields = new Set([
  "tenant",
  "tenantid",
  "organization",
  "organizationid",
  "actor",
  "actorid",
  "actorcontext",
  "actorrole",
  "actorroles",
  "actoruserid",
  "currentactor",
  "currentactorid",
  "currentuser",
  "currentuserid",
  "user",
  "userid",
  "otheruser",
  "otheruserid",
  "arbitraryuser",
  "arbitraryuserid",
  "targetuser",
  "targetuserid",
  "principal",
  "principalid",
  "subject",
  "subjectid",
  "authenticateduser",
  "authenticateduserid",
  "identity",
  "session",
  "sessionid",
  "auth",
  "authentication",
  "authorization",
  "role",
  "roles",
  "capability",
  "capabilities",
  "permission",
  "permissions",
]);
function rejectTrusted(value: unknown, seen = new Set<object>()): void {
  if (typeof value !== "object" || value === null) return;
  if (seen.has(value)) fail("malformed_input", "Cyclic values are not JSON");
  seen.add(value);
  for (const [name, nested] of Object.entries(value)) {
    if (trustedFields.has(name.replaceAll(/[^a-zA-Z0-9]/g, "").toLowerCase())) fail("trusted_identity_field", `${name} is server-derived`);
    rejectTrusted(nested, seen);
  }
  seen.delete(value);
}
function record(value: unknown, code: ReplyStylePreferenceParseErrorCode): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) fail(code, "Expected an object");
  return value as Record<string, unknown>;
}
function exact(value: Record<string, unknown>, keys: readonly string[], code: ReplyStylePreferenceParseErrorCode): void {
  if (Object.keys(value).length !== keys.length || !keys.every(k => Object.hasOwn(value, k))) fail(code, "Unsupported or missing fields");
}
function style(value: unknown): ReplyStyle {
  if (!isReplyStyle(value)) fail("malformed_style", "Style must be current or discord");
  return value;
}
function parseRevision(value: unknown, advanceable: boolean): number {
  if (typeof value !== "number" || !Number.isSafeInteger(value) || value < 0 || value > MAX_SAFE_REVISION - (advanceable ? 1 : 0)) {
    fail("malformed_revision", "Revision must be a nonnegative safe integer (writes must be advanceable)");
  }
  return value;
}
function key(value: unknown): string {
  if (typeof value !== "string" || value.trim().length === 0 || value.trim() !== value || value.normalize("NFC") !== value ||
      /[\u0000-\u001F\u007F-\u009F\uD800-\uDFFF]/u.test(value) || new TextEncoder().encode(value).length > MAX_REPLY_STYLE_PREFERENCE_IDEMPOTENCY_KEY_UTF8_BYTES) {
    fail("malformed_input", "Invalid bounded NFC idempotency key");
  }
  return value;
}
function fail(code: ReplyStylePreferenceParseErrorCode, message: string): never {
  throw new ReplyStylePreferenceParseError(code, message);
}
