// Generated by scripts/generate-thread-list.mjs from contracts/http/thread-list.json.
// Do not edit directly. Contract SHA-256: ffedf79a5d4cc3d0f7e6f515de529c829c4d5dac60c0552d8f388c487bbee38c
import type { ConversationId, IsoTimestamp } from "./identifiers.js";
import { parseConversationSnapshotSummary, type ThreadConversationSnapshotSummary, type ConversationDetailSnapshotConversation } from "./conversation-snapshot-runtime.js";
import { parseCanonicalThreadFollowState } from "./thread-follow-mutation.js";

export const THREAD_LIST_PATH = "/conversations/:parentConversationId/threads" as const;
export type ThreadListView = "active" | "all";
/** Structurally matches the server's resolved ChatThreadInactivityPolicy. */
export type ThreadListInactivityPolicy = false | Readonly<{ hideAfterMs: number }>;
export interface ThreadListRequest {
  readonly parentConversationId: ConversationId;
  readonly view?: ThreadListView;
  readonly limit?: number;
  readonly cursor?: string;
}
export interface ResolvedThreadListRequest extends ThreadListRequest {
  readonly view: ThreadListView;
  readonly limit: number;
}
export interface ThreadListCursorPosition {
  readonly parentConversationId: ConversationId;
  readonly view: ThreadListView;
  readonly createdAt: IsoTimestamp;
  readonly threadId: ConversationId;
}
export interface ThreadListItem {
  readonly thread: ThreadConversationSnapshotSummary;
  readonly currentThreadFollow: NonNullable<ConversationDetailSnapshotConversation["currentThreadFollow"]>;
  readonly lastActivityAt: IsoTimestamp;
  /** Unix milliseconds, including fractional milliseconds; null means disabled. */
  readonly hideAt: number | null;
}
export interface ThreadListResult {
  readonly parentConversationId: ConversationId;
  readonly view: ThreadListView;
  readonly evaluatedAt: IsoTimestamp;
  readonly lifecycleSupported: boolean;
  readonly inactivityPolicy?: ThreadListInactivityPolicy;
  readonly items: readonly ThreadListItem[];
  readonly nextCursor?: string;
}
export class ThreadListParseError extends Error {
  constructor(message: string) { super(message); this.name = "ThreadListParseError"; }
}
export function parseThreadListRequest(value: unknown): ResolvedThreadListRequest {
  const o = object(value);
  keys(o, ["parentConversationId"], ["view", "limit", "cursor"]);
  const parentConversationId = identifier(o.parentConversationId) as ConversationId;
  const view = selection(Object.hasOwn(o, "view") ? o.view : "active");
  const limit = Object.hasOwn(o, "limit") ? o.limit : 50;
  if (typeof limit !== "number" || !Number.isInteger(limit) || limit < 1 || limit > 100) fail("Invalid page limit");
  const request = { parentConversationId, view, limit };
  if (Object.hasOwn(o, "cursor")) {
    if (typeof o.cursor !== "string") fail("Invalid cursor");
    decodeThreadListCursor(o.cursor, request);
    return { ...request, cursor: o.cursor };
  }
  return request;
}
/** Adapter for decoded HTTP query values. Unknown query keys and repeated values fail. */
export function parseThreadListHttpRequest(parentConversationId: unknown, query: unknown): ResolvedThreadListRequest {
  const q = object(query);
  keys(q, [], ["view", "limit", "cursor"]);
  const o: Record<string, unknown> = { ...q, parentConversationId };
  if (Object.hasOwn(q, "limit")) {
    if (typeof q.limit !== "string" || !/^[1-9][0-9]*$/.test(q.limit)) fail("Invalid HTTP limit");
    o.limit = Number(q.limit);
  }
  return parseThreadListRequest(o);
}
export function serializeThreadListQuery(input: ThreadListRequest): Record<string, string> {
  const r = parseThreadListRequest(input);
  return { view: r.view, limit: String(r.limit), ...(r.cursor === undefined ? {} : { cursor: r.cursor }) };
}
export function encodeThreadListCursor(value: ThreadListCursorPosition): string {
  const p = position(value);
  const bytes = new TextEncoder().encode(JSON.stringify(p));
  return "handrail-threads.v1." + btoa(String.fromCharCode(...bytes)).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "");
}
export function decodeThreadListCursor(value: unknown, scope: Pick<ResolvedThreadListRequest, "parentConversationId" | "view">): ThreadListCursorPosition {
  identifier(scope.parentConversationId); selection(scope.view);
  if (typeof value !== "string" || value.length > 4096 || !value.startsWith("handrail-threads.v1.")) fail("Invalid cursor envelope");
  let p: ThreadListCursorPosition;
  try {
    const token = value.slice("handrail-threads.v1.".length);
    if (!/^[A-Za-z0-9_-]+$/.test(token)) fail("Invalid cursor encoding");
    const binary = atob(token.replaceAll("-", "+").replaceAll("_", "/"));
    p = position(JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(Uint8Array.from(binary, c => c.charCodeAt(0)))));
  } catch { fail("Malformed cursor"); }
  if (encodeThreadListCursor(p) !== value || p.parentConversationId !== scope.parentConversationId || p.view !== scope.view) fail("Noncanonical or incompatible cursor");
  return p;
}
/** Negative means a sorts before b. Use the same UTF-8/C collation in SQL. */
export function compareThreadListPositions(a: Pick<ThreadListCursorPosition, "createdAt" | "threadId">, b: Pick<ThreadListCursorPosition, "createdAt" | "threadId">): number {
  const time = timestamp(b.createdAt) - timestamp(a.createdAt);
  if (time !== 0) return time;
  const left = new TextEncoder().encode(identifier(a.threadId));
  const right = new TextEncoder().encode(identifier(b.threadId));
  for (let i = 0; i < Math.min(left.length, right.length); i++) {
    if (left[i] !== right[i]) return left[i]! - right[i]!;
  }
  return left.length - right.length;
}
export function parseThreadListResult(value: unknown, expectedRequest: ThreadListRequest): ThreadListResult {
  const r = parseThreadListRequest(expectedRequest);
  const o = object(value);
  keys(o, ["parentConversationId", "view", "evaluatedAt", "lifecycleSupported", "items"], ["inactivityPolicy", "nextCursor"]);
  if (identifier(o.parentConversationId) !== r.parentConversationId || selection(o.view) !== r.view) fail("Response scope mismatch");
  const evaluatedAt = timestamp(o.evaluatedAt);
  if (typeof o.lifecycleSupported !== "boolean") fail("Invalid lifecycle capability");
  const policy = Object.hasOwn(o, "inactivityPolicy") ? parsePolicy(o.inactivityPolicy) : false;
  if (!Array.isArray(o.items) || o.items.length > r.limit) fail("Invalid items");
  let previous = r.cursor === undefined ? undefined : decodeThreadListCursor(r.cursor, r);
  const ids = new Set<string>();
  const items = o.items.map(raw => {
    const item = object(raw);
    keys(item, ["thread", "currentThreadFollow", "lastActivityAt", "hideAt"]);
    let thread: ThreadConversationSnapshotSummary;
    try {
      keys(object(item.thread), [], ["type", "id", "tenantId", "createdAt", "updatedAt", "archivedAt", "archivedByUserId", "threadLifecycle", "visibility", "parentConversationId", "rootMessageId", "name", "latestSequence", "activityAt", "unreadMentionCount", "currentMember", "currentReadState", "activeMemberUserIds", "currentPreference"]);
      const summary = parseConversationSnapshotSummary(item.thread);
      if (summary.type !== "thread") fail("Expected thread summary");
      thread = summary;
    } catch { fail("Invalid canonical thread summary"); }
    identifier(thread.id); identifier(thread.rootMessageId);
    if (identifier(thread.parentConversationId) !== r.parentConversationId || thread.id === r.parentConversationId) fail("Thread parent mismatch");
    if (thread.archivedAt !== undefined) fail("Archived thread is not discoverable");
    if (!o.lifecycleSupported && thread.threadLifecycle !== undefined) fail("Lifecycle metadata requires capability");
    const current = { parentConversationId: r.parentConversationId, view: r.view, createdAt: thread.createdAt, threadId: thread.id };
    timestamp(current.createdAt);
    if (ids.has(thread.id) || (previous !== undefined && compareThreadListPositions(previous, current) >= 0)) fail("Duplicate, unsorted or non-advancing page");
    ids.add(thread.id); previous = current;
    const activity = timestamp(item.lastActivityAt);
    if (activity < timestamp(thread.createdAt) || activity > evaluatedAt || thread.activityAt !== item.lastActivityAt) fail("Invalid message activity");
    if (thread.latestSequence === 0 && activity !== timestamp(thread.createdAt)) fail("Empty thread activity must equal creation");
    const hideAt = policy === false ? null : activity + policy.hideAfterMs;
    if (item.hideAt !== hideAt || (hideAt !== null && !Number.isFinite(hideAt))) fail("Invalid expiry metadata");
    if (r.view === "active" && (thread.threadLifecycle?.closedAt !== undefined || (policy !== false && evaluatedAt - activity >= policy.hideAfterMs))) fail("Inactive thread in active view");
    const authority = object(item.currentThreadFollow);
    keys(authority, ["followRevision", "follow"]);
    const revision = authority.followRevision;
    if (typeof revision !== "number" || !Number.isSafeInteger(revision) || revision < 0) fail("Invalid follow revision");
    let follow;
    try { follow = authority.follow === null ? null : parseCanonicalThreadFollowState(authority.follow); }
    catch { fail("Invalid canonical follow"); }
    if (follow === null ? revision !== 0 : revision === 0 || follow.target.id !== thread.id) fail("Follow authority mismatch");
    return { thread, currentThreadFollow: { followRevision: revision, follow }, lastActivityAt: item.lastActivityAt as IsoTimestamp, hideAt };
  });
  if (Object.hasOwn(o, "nextCursor")) {
    const next = decodeThreadListCursor(o.nextCursor, r);
    if (items.length !== r.limit || previous === undefined || compareThreadListPositions(previous, next) !== 0) fail("Cursor must describe last item of a full page");
  }
  return { parentConversationId: r.parentConversationId, view: r.view, evaluatedAt: o.evaluatedAt as IsoTimestamp,
    lifecycleSupported: o.lifecycleSupported, items,
    ...(Object.hasOwn(o, "inactivityPolicy") ? { inactivityPolicy: policy } : {}),
    ...(Object.hasOwn(o, "nextCursor") ? { nextCursor: o.nextCursor as string } : {}) };
}
export function serializeThreadListResult(value: ThreadListResult, request: ThreadListRequest): ThreadListResult {
  return parseThreadListResult(value, request);
}
function position(value: unknown): ThreadListCursorPosition {
  const o = object(value); keys(o, ["parentConversationId", "view", "createdAt", "threadId"]); timestamp(o.createdAt);
  return { parentConversationId: identifier(o.parentConversationId) as ConversationId, view: selection(o.view), createdAt: o.createdAt as IsoTimestamp, threadId: identifier(o.threadId) as ConversationId };
}
function parsePolicy(value: unknown): ThreadListInactivityPolicy {
  if (value === false) return false;
  const o = object(value); keys(o, ["hideAfterMs"]);
  if (typeof o.hideAfterMs !== "number" || !Number.isFinite(o.hideAfterMs) || o.hideAfterMs <= 0) fail("Invalid resolved policy");
  return { hideAfterMs: o.hideAfterMs };
}
function timestamp(value: unknown): number {
  if (typeof value !== "string" || !/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(value)) fail("Invalid canonical timestamp");
  const ms = Date.parse(value);
  if (!Number.isFinite(ms) || new Date(ms).toISOString() !== value) fail("Invalid timestamp");
  return ms;
}
function selection(value: unknown): ThreadListView {
  if (value !== "active" && value !== "all") fail("Invalid view");
  return value;
}
function identifier(value: unknown): string {
  if (typeof value !== "string" || !value || value.trim() !== value || /[\x00-\x1f\x7f-\x9f\u2028\u2029]/u.test(value) || new TextEncoder().encode(value).length > 255 || new TextDecoder().decode(new TextEncoder().encode(value)) !== value) fail("Invalid identifier");
  return value;
}
function object(value: unknown): Record<string, unknown> {
  if (typeof value !== "object" || value === null || Array.isArray(value)) fail("Expected object");
  return value as Record<string, unknown>;
}
function keys(o: Record<string, unknown>, required: readonly string[], optional: readonly string[] = []): void {
  if (!required.every(k => Object.hasOwn(o, k)) || Object.keys(o).some(k => !required.includes(k) && !optional.includes(k))) fail("Unknown or missing fields");
}
function fail(message: string): never { throw new ThreadListParseError(message); }
