import { readFileSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const templateRoot = resolve(repositoryRoot, "scripts/templates");
const descriptorPath = "contracts/http/huddles.json";
const outputPaths = {
  typescript: "src/contracts/huddle-session.ts",
  dart: "contracts/generated/dart/huddle_session.dart",
};

const expectedStates = ["inactive", "starting", "active", "ended"];
const expectedParticipantStatuses = ["joined", "left"];
const expectedOperations = [
  "start_huddle",
  "join_huddle",
  "leave_huddle",
  "set_huddle_screen_share",
  "end_huddle",
];
const expectedTransitions = [
  ["inactive", "inactive"], ["inactive", "starting"],
  ["starting", "starting"], ["starting", "active"], ["starting", "ended"],
  ["active", "active"], ["active", "ended"], ["ended", "ended"],
];

export async function readHuddlesDescriptor(root = repositoryRoot) {
  const descriptor = JSON.parse(await readFile(resolve(root, descriptorPath), "utf8"));
  validateDescriptor(descriptor);
  return descriptor;
}

export function generateTypeScript(descriptor) {
  validateDescriptor(descriptor);
  let output = readFileSync(resolve(templateRoot, "huddle-session.ts.tpl"), "utf8");
  output = output.replace(
    /export const MAX_HUDDLE_IDEMPOTENCY_KEY_UTF8_BYTES = [^;]+;/,
    `export const MAX_HUDDLE_IDEMPOTENCY_KEY_UTF8_BYTES = ${numberLiteral(descriptor.bounds.idempotencyKeyMaxUtf8Bytes)};`,
  );
  output = output.replace(
    /export const MAX_HUDDLE_MEDIA_JOIN_DESCRIPTOR_UTF8_BYTES = [^;]+;/,
    `export const MAX_HUDDLE_MEDIA_JOIN_DESCRIPTOR_UTF8_BYTES = ${numberLiteral(descriptor.mediaJoinDescriptor.maxUtf8Bytes)};`,
  );
  output = output.replace(
    /export const MAX_HUDDLE_MEDIA_JOIN_DESCRIPTOR_TTL_MS = [^;]+;/,
    `export const MAX_HUDDLE_MEDIA_JOIN_DESCRIPTOR_TTL_MS = ${numberLiteral(descriptor.mediaJoinDescriptor.maxTtlMs)};`,
  );
  output = replaceSet(output, "TRUSTED_CONTEXT_FIELDS", descriptor.forbiddenPublicFields.trustedIdentity);
  output = replaceSet(output, "PROVIDER_FIELDS", [
    ...descriptor.forbiddenPublicFields.providerInternals,
    ...descriptor.forbiddenPublicFields.credentials,
  ]);
  return `// Generated by scripts/generate-huddles.mjs from contracts/http/huddles.json.\n// Do not edit this file directly.\n\n${output}`;
}

export function generateDart(descriptor) {
  validateDescriptor(descriptor);
  return render("huddle_session.dart.tpl", {
    IDENTIFIER_MAX: String(descriptor.bounds.identifierMaxUtf8Bytes),
    IDEMPOTENCY_MAX: String(descriptor.bounds.idempotencyKeyMaxUtf8Bytes),
    DESCRIPTOR_MAX: String(descriptor.mediaJoinDescriptor.maxUtf8Bytes),
    DESCRIPTOR_TTL_MAX: String(descriptor.mediaJoinDescriptor.maxTtlMs),
    TRUSTED_FIELDS: dartSetValues(descriptor.forbiddenPublicFields.trustedIdentity),
    PROVIDER_FIELDS: dartSetValues([
      ...descriptor.forbiddenPublicFields.providerInternals,
      ...descriptor.forbiddenPublicFields.credentials,
    ]),
  });
}

export async function generateHuddles({ check = false, root = repositoryRoot } = {}) {
  const descriptor = await readHuddlesDescriptor(root);
  const outputs = {
    [outputPaths.typescript]: generateTypeScript(descriptor),
    [outputPaths.dart]: generateDart(descriptor),
  };
  const drifted = [];
  for (const [path, generated] of Object.entries(outputs)) {
    const absolute = resolve(root, path);
    if (check) {
      let existing;
      try { existing = await readFile(absolute, "utf8"); }
      catch (error) { if (error?.code !== "ENOENT") throw error; }
      if (existing !== generated) drifted.push(path);
    } else {
      await mkdir(dirname(absolute), { recursive: true });
      await writeFile(absolute, generated, "utf8");
    }
  }
  return drifted;
}

function validateDescriptor(descriptor) {
  if (descriptor?.schemaVersion !== 1) throw new Error("huddles.json must use schemaVersion 1");
  equal(descriptor.states, expectedStates, "states");
  equal(descriptor.participantStatuses, expectedParticipantStatuses, "participant statuses");
  equal(descriptor.screenShareIntents, ["set", "clear"], "screen-share intents");
  equal(descriptor.reconciliationStatuses, ["applied", "replayed"], "reconciliation statuses");
  equal(Object.keys(descriptor.operations ?? {}), expectedOperations, "operations");
  equal(descriptor.allowedTransitions, expectedTransitions, "allowed transitions");
  const expectedOperationPolicy = {
    start_huddle: ["conversation", "starting", true, true],
    join_huddle: ["session", "active", true, true],
    leave_huddle: ["session", "active", false, false],
    set_huddle_screen_share: ["session", "active", false, false],
    end_huddle: ["session", "ended", false, false],
  };
  for (const [operation, policy] of Object.entries(descriptor.operations ?? {})) {
    equal([policy.inputTarget, policy.successState, policy.mediaJoin, policy.featureDisabled], expectedOperationPolicy[operation], `${operation} policy`);
  }
  for (const [name, value] of Object.entries({
    ...descriptor.bounds,
    maxUtf8Bytes: descriptor.mediaJoinDescriptor?.maxUtf8Bytes,
    maxTtlMs: descriptor.mediaJoinDescriptor?.maxTtlMs,
  })) {
    if (!Number.isSafeInteger(value) || value <= 0) throw new Error(`huddles.json bound ${name} must be a positive safe integer`);
  }
  if (descriptor.mediaJoinDescriptor?.kind !== "opaque_media_join" || descriptor.mediaJoinDescriptor?.opaque !== true || descriptor.mediaJoinDescriptor?.providerNeutral !== true) {
    throw new Error("huddles.json media join descriptor must be opaque and provider-neutral");
  }
  equal(descriptor.featureDisabled, { feature: "huddles", reason: "media_unavailable", statePreserving: true }, "feature-disabled policy");
  if (Object.keys(descriptor.coherenceRules ?? {}).length !== 6 || Object.values(descriptor.coherenceRules).some((value) => value !== true)) {
    throw new Error("huddles.json coherence rules are incomplete");
  }
  for (const category of ["trustedIdentity", "providerInternals", "credentials"]) {
    if (!Array.isArray(descriptor.forbiddenPublicFields?.[category]) || descriptor.forbiddenPublicFields[category].length === 0) {
      throw new Error(`huddles.json must define ${category} exclusions`);
    }
  }
}

function replaceSet(source, name, values) {
  const pattern = new RegExp(`const ${name} = new Set\\(\\[[\\s\\S]*?\\]\\);`);
  if (!pattern.test(source)) throw new Error(`huddle TypeScript template is missing ${name}`);
  return source.replace(pattern, `const ${name} = new Set([\n${[...new Set(values.map(normalizeAlias))].map((value) => `  ${JSON.stringify(value)},`).join("\n")}\n]);`);
}
function dartSetValues(values) { return [...new Set(values.map(normalizeAlias))].map((value) => `  '${value}',`).join("\n"); }
function normalizeAlias(value) { return value.replaceAll(/[^a-zA-Z0-9]/g, "").toLowerCase(); }
function numberLiteral(value) { return value >= 1000 ? value.toLocaleString("en-US").replaceAll(",", "_") : String(value); }
function equal(actual, expected, label) { if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error(`huddles.json has unsupported ${label}`); }
function render(name, values) {
  let template = readFileSync(resolve(templateRoot, name), "utf8");
  for (const [key, value] of Object.entries(values)) template = template.replaceAll(`{{${key}}}`, value);
  if (/\{\{[A-Z_]+\}\}/.test(template)) throw new Error(`${name} contains an unresolved placeholder`);
  return template;
}
function parseArguments(args) {
  let check = false;
  let root = repositoryRoot;
  for (let index = 0; index < args.length; index += 1) {
    if (args[index] === "--check") check = true;
    else if (args[index] === "--root" && args[index + 1]) root = resolve(args[++index]);
    else throw new Error(`Unknown argument: ${args[index]}`);
  }
  return { check, root };
}
async function main() {
  const options = parseArguments(process.argv.slice(2));
  const drifted = await generateHuddles(options);
  if (options.check && drifted.length > 0) {
    console.error(`Generated huddle contracts are out of date:\n${drifted.map((path) => `- ${relative(options.root, resolve(options.root, path))}`).join("\n")}\nRun npm run generate:huddles.`);
    process.exitCode = 1;
  } else if (options.check) console.log("Generated huddle contracts are up to date.");
}
if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) await main();
